### ISSUE TITLE
Installation issue -  'SymfonyRequirements.php' is missing

### ISSUE THREAD

**Issue by apcloic** [Cocolabs-SAS/cocorico#1]
Hi,
First, as a cocolabs customer, I'm really glad to see this Open Source project finally out on github, congratulations !

Server : Ubuntu Server 14.04 LTS
Web server : Apache2
Database server : MySQL

Here's some problems encountered during my first attempt to install Cocorico  :

1/ It looks like Symfony/app/SymfonyRequirements.php is missing so it's not possible to run the following commands :
php app/check.php
http://[cocorico.dev]/config.php

Let me know if you need more informations.
Regards,

**Comment by cocolabssas** [comment]
Thanks for your feedback!

This file is part of Symfony and is automatically created while cocorico installation.
It seems that some installation steps have been ignored.
The following command should resolve your problem: 
`php composer.phar install --prefer-dist -vvv`
If the problem still exists could you give me the complete error message.

**Comment by apcloic** [comment]
Problem solved, I have a working cocorico instance now ;)
Thanks !
