### ISSUE TITLE
 [BUG] Date non reset

### ISSUE THREAD

**Issue by AxelBriche** [Cocolabs-SAS/cocorico#10]
Bonjour, quand on sélectionne une date dans une annonce, celle-ci semble stocké dans un cookie ou en session, ces données sont réinitialisée lorsque l'on passe sur le listing à nouveau en refaisant une recherche.

J'ai trouvé un bug dans le cas ou on ouvre deux onglets avec deux annonces différentes, lorsque l'on choisi une date sur une des annonce et que l'on refresh l'autre onglet, la date affichée n'a pas été réinitialisé, il semble que le reset se fasse donc sur le listing mais pas sur la page des annonces, ce qui repercute la date selectionné d'une annonce à l'autre lorsque l'on ne repasse pas entre deux sur la page listing.

Voilà c'est pour signaler le petit souci, car ça ressemble fort à un bug ou du moins à un comportement non voulu qui n'a pas été remarqué. Le problème est également présent sur votre dernière demo.

Bonne journée.

**Comment by cocolabssas** [comment]
Thanks for this remark but if i have correctly understood this is not a bug but a normal behavior.
The date is persisted between listings navigation.
