### ISSUE TITLE
Try To ADD Categories show in Backed but not show in Front End

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#101]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| Support request? | yes

Hi, 
hope you are good and doing well!

I just added new categories but unfortunately,  I can't see the new categories in my frontend. All categories are saved properly in the backend.

**Comment by Atranaz** [comment]
@cocolabssas In my case, I only use one language and it's English.

**Comment by Atranaz** [comment]
@cocolabssas also when delete category it's not deleted from the front end, its show kind of cache issue but I clear the cache but nothing happened.

**Comment by cocolabssas** [comment]
@Atranaz 

This problem seems to be specific to your project.

From our side : 
- we can add category in backend and see it in frontend. 
- we can delete category in backend and don't see it anymore in frontend.

**Comment by Atranaz** [comment]
@cocolabssas its work like if I have only5 categories after that I got this issue any specific required need after creating a new category from the backend ?

**Comment by cocolabssas** [comment]
Maybe a problem of APCu cache.

Look at `\Cocorico\CoreBundle\Repository\ListingCategoryRepository::findCategoriesByIds`, Categories SQL query use ResultCache. APCu cache is enabled only in prod env. If you are in prod env clear your APCu cache.

**Comment by Atranaz** [comment]
@cocolabssas ok I'll check and update you.

**Comment by Atranaz** [comment]
@cocolabssas Its APCu Cache issue thanks it worked :)

**Comment by cocolabssas** [comment]
Great!

I close the issue
