### ISSUE TITLE
Everything work but I got some errors. Is it normal?

### ISSUE THREAD

**Issue by nvirin** [Cocolabs-SAS/cocorico#102]
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Cocorico\CoreBundle\Entity\Listing object not found." at /****/src/Cocorico/CoreBundle/Request/ListingParamConverter.php line 75 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Cocorico\\CoreBundle\\Entity\\Listing object not found. at /****/src/Cocorico/CoreBundle/Request/ListingParamConverter.php:75)"}

**Comment by cocolabssas** [comment]
If you look the line of the error message you will see that you are trying to find a listing by a slug and locale  which don't exist.
