### ISSUE TITLE
Admin notation and status of listing explanation

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#104]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? |no
| Support request? | yes

Hello,

Could you explain the different status ( difference between published and new for exemple ) and what is Admin notation ?

If status is hidden , does it mean it won't be crawlable by google bot ,?
Thank you

**Comment by cocolabssas** [comment]
Hello,

- STATUS_NEW is the default status of a new listing. The listing is not publicly accessible. 
- STATUS_PUBLISHED means listing is published and is publicly accessible.
- STATUS_SUSPENDED means the listing is temporary unpublished. The owner can publish it when he wants.
- STATUS_DELETED means listing will not be accessible by anyone except by admin.
- STATUS_INVALIDATED means admin has invalidated the listing and can not be published by the owner. The owner have to correct his listing informations and then change the status to STATUS_TO_VALIDATE before admin eventually publish his listing
- STATUS_TO_VALIDATE means listing has to be validated by admin before being published.

If status is not published the listing is not crawlable. 

Admin notation is a note given by the admin on a listing. This notation is used in the `order by` clause of the listing search query.
