### ISSUE TITLE
End time must be after the start time

### ISSUE THREAD

**Issue by nvirin** [Cocolabs-SAS/cocorico#105]
Hello,
I want to create listing than less 1 hour (45 minutes, 30 minutes...)

When I fill a book from 08.00 to 08.45 for example. I got this message: "End time must be after the start time".

Can you help me and tell me where I can configure this?
Thank you
/en/listing/test-1610626763/show

**Comment by cocolabssas** [comment]
Hello,

This feature allowing booking less than one hour is not yet published but in the meanwhile you can just 
replace in web/js/common.js:525 the function `timesAreValid `by this one :

```
function timesAreValid(startHour, endHour, startMinute, endMinute) {
    if (startHour.length && endHour.length) {
        if (!$.isNumeric(startHour.val()) || !$.isNumeric(endHour.val()) ||
            !$.isNumeric(startMinute.val()) || !$.isNumeric(endMinute.val())) {

            return false;
        }
    }

    return true;
}

```

Furthermore you will need to replace also this translation in app/Resources/translations/cocorico.fr.xliff:420 and cocorico.en.xliff

```
<trans-unit id="f1d24cf913356e9f49b26d914a31742608c9cb6b" resname="time_unit_hour">
    <source>time_unit_hour</source>
    <target state="new">{-3} par heure|{-1} heure(s)|[0,1] %count% heure|]1,Inf]%count% heures</target>
    <jms:reference-file line="213">CoreBundle/Twig/CoreExtension.php</jms:reference-file>
</trans-unit>
```

**Comment by nvirin** [comment]
Thank you for your answer!
