### ISSUE TITLE
PHP7 anyone tested Cocorico with it?

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#106]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| Support request? | yes

anyone use Cocorico with PHP 7 if yes kindly let me know about experience?

Thanks in Advance!

**Comment by cocolabssas** [comment]
Hello,

We are working on Cocorico / PHP 7 compatibility. This will be available very soonly.

**Comment by Atranaz** [comment]
that's great you guys update Symfony too?

**Comment by cocolabssas** [comment]
Yes will upgrade as soon as the last Symfony LTS will be released.

**Comment by Atranaz** [comment]
that's great news :)

**Comment by cocolabssas** [comment]
Hi,

As expected Cocorico is now compatible with PHP 7.1 :)

**Comment by Atranaz** [comment]
That's great :)

**Comment by fakelefteye** [comment]
Hello; I upgraded to PHP7.1 and I get this : 

PHP Fatal error:  Uncaught RuntimeException: Unable to use ApcClassLoader as APC is not installed

I did this :  apt-get install php-pear
pecl install apcu_bc-beta
echo "extension=apc.so" > /etc/php/mods-available/apcu_bc.ini
phpenmod -v 7.0 -s ALL apcu_bc
 and installed php 7.1-dev

but got the same error... thanks you
