### ISSUE TITLE
No route found for "GET /_configurator/"

### ISSUE THREAD

**Issue by NJCalvo** [Cocolabs-SAS/cocorico#107]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

After open to config.php file I clic "Configure your Symfony Application online" (I have only 3 recommendations: Requirements file should be up-to-date, intl extension should be available and PDO should have some drivers installed (currently available: none))
But after clic I receive this error: No route found for "GET /_configurator/"

What can I do?
Thanks

**Comment by cocolabssas** [comment]
Look at stackoverflow for example:
- https://stackoverflow.com/questions/33298789/synfony-demo-no-route-found-for-get-configurator-resourcenotfoundexcepti
