### ISSUE TITLE
On listing Image upload save name in DB but can't create image file

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#108]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| Support request? | yes

I having a weird issue and it's suddenly occurred. what happens Listing can't show the image when I inspect in source code get this path "**/en/media/cache/resolve/listing_xxmedium/uploads/listings/images/824c4ac68f2e982e215eff7e4e7b42b1d9754abb.jpg**" when I check folder I can't find this name image.

**Comment by cocolabssas** [comment]
Do you have GD or Imagick PHP extension enabled according to your `cocorico.image_driver` parameter value in `app/config/parameters.yml`:26?
Did  you check your logs to see if there are any relevant errors?

**Comment by vishaldudhatra009** [comment]
Hi

I have facing same issue, see in screen shot https://www.screencast.com/t/EYQ5J3NgSQ and same name file generate on path **web\uploads\users\images\19643349cdeb276f3bb4e183db71ecbdfa30e15b.jpg**

GD and Imagick extension both are enable in my php. 
**cocorico.image_driver: imagick** parameter is set in  **app/config/parameters.yml** file

**Comment by cocolabssas** [comment]
@vishaldudhatra009 From your error screen i guess you are on Windows. 
I 'd recommended you to use GD instead of Imagick on Windows. Making PHP and Imagick work on Windows is quite difficult.

**Comment by Atranaz** [comment]
Its GD or Imagick PHP extension and fixed :)
