### ISSUE TITLE
Editing content

### ISSUE THREAD

**Issue by ItsJoker50** [Cocolabs-SAS/cocorico#109]
Posted to stackoverflow with no help. I am completely new to coding and have gotten the system up and running. However, when I try to edit the homepage content and default currency I am unable to open find anything in the admin dashboard or in any of the files via ftp. Any assistance would be helpful on where to look. 

| ---------------- | -----
| Bug report?      | No
| Feature request? | no
| Support request? | yes

**Comment by eshelf** [comment]
Hi!

For changing the default currency, change the property "cocorico.currency" in the file \src\Cocorico\CoreBundle\Resources\config\parameters.yml.

For changing the homepage, edit \src\Cocorico\CoreBundle\Resources\views\Frontend\Home\index.html.twig

**Comment by ItsJoker50** [comment]
Thank you.
