### ISSUE TITLE
SMTP mailing stopped working (TokenStorage being populated with an anonymous Token)

### ISSUE THREAD

**Issue by eshelf** [Cocolabs-SAS/cocorico#111]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

Hey everyone!

I used to be able to send mails using my gmail account, but recently it stopped working. Please find below the error I'm getting:

`[2017-11-22 19:09:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []`

`[2017-11-22 19:09:09] app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host smtp.gmail.com [ #0] [] []`

As I thought it could be a gmail problem, I created an alternative account in sparkpostmail, but then I've got the same error...

`[2017-11-22 19:55:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []`

`[2017-11-22 19:55:04] app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host smtp.sparkpostmail.com [ #0] [] []`

I believe that the problem is this **TokenStorage** being populated with an **anonymous Token**, but i don't properly understand what it means and I couldn't find it in anywhere.

Does someone know how to solve it?

Thanks in advance!

**Comment by cocolabssas** [comment]
I don't think there is a relation between your mail problem and the message about TokenStorage Info.
It seems to be related to a connection problem with the host of your email provider. 

Some verifications you can do:

- Ping host
- Check if you allow less secure apps or use app password with 2 step verification on your gmail account.
- Check if your antivirus or firewall block access
- Check your mailer parameters (https://github.com/dancostinel/symfony-email)

**Comment by eshelf** [comment]
I've tried to ping sucessfully, the gmail account configuration was correct, I turned-off the firewall and the mailer parameters were configured as recommended.

This [post](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) helped me.

And this was the [solution ](https://stackoverflow.com/questions/26896265/php-swiftmailer-using-starttls-and-self-signed-certificates)I finaly used.
