### ISSUE TITLE
GDPR - General Data Protection Regulation 

### ISSUE THREAD

**Issue by doydoy44** [Cocolabs-SAS/cocorico#112]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

 Hello,

I would like to know if the project is in compliance with [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation).

Thank you in advance

**Comment by La-Meche** [comment]
Hi @doydoy44, we're not putting "country" specific regulatory requirements directly into Cocorico, instead we're adding those features through bundles which we're beginning to release in January 2018. The idea is that different users will have different requirements depending on where they're based. Currently we're working on bundles that enable Cocorico to match regulatory requirements in France such as the "loi du 29 décembre 2015 de finances pour l’année 2016" (see https://www.legifrance.gouv.fr/eli/loi/2015/12/29/FCPX1519907L/jo). We're hoping GDPR compliance will be complete in January, in time with the expected implementation date of 25/05/2018.

**Comment by doydoy44** [comment]
Thank you for your response.

What will the bundle price be?

**Comment by La-Meche** [comment]
Hopefully the bundle will be open source (MIT) and free.

**Comment by doydoy44** [comment]
Yes hopefully :)
