### ISSUE TITLE
$booking->setStatus(BookingBankWire::STATUS_DONE);

### ISSUE THREAD

**Issue by nvirin** [Cocolabs-SAS/cocorico#113]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? |no
| Support request? | yes

I just want to understand something.
**1) When the cron cocorico:bookings:validate is called.**
It call this:
[https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Event/BookingValidateSubscriber.php](https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Event/BookingValidateSubscriber.php)

**2) I want to set the bookbankwire status to STATUS_DONE (1)**

So I add this   $booking->setStatus(BookingBankWire::STATUS_DONE) here
[https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Event/BookingValidateSubscriber.php](https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Event/BookingValidateSubscriber.php) on line 38

_public function onBookingValidate(BookingValidateEvent $event)
    {
        $booking = $event->getBooking();
     _**$booking->setStatus(BookingBankWire::STATUS_DONE);**_
        $bankWire = $this->bookingBankWireManager->create($booking);
        $this->bookingBankWireManager->save($bankWire);
        $event->setValidated(true);
        $event->setBooking($booking);
        $event->stopPropagation();
    }_

**3) But it is not set on my database. Have you any idea about how to set this  status ?**

**Comment by cocolabssas** [comment]
Hi,

To set the bookingBankWire status to `STATUS_DONE` you should called `setStatus` on the bankWire object instead of the booking object:

```
public function onBookingValidate(BookingValidateEvent $event)
{
    $booking = $event->getBooking();
    $bankWire = $this->bookingBankWireManager->create($booking);
    $bankWire->setStatus(BookingBankWire::STATUS_DONE);
    $this->bookingBankWireManager->save($bankWire);
    $event->setValidated(true);
    $event->setBooking($booking);
    $event->stopPropagation();
}
```

**Comment by nvirin** [comment]
Thank you!
