### ISSUE TITLE
Problem with geocoding routes when using new languages

### ISSUE THREAD

**Issue by eshelf** [Cocolabs-SAS/cocorico#118]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

Hi!

I'm customizing Cocorico to use in Spanish and Brazilian portuguese, besides English and French. I'm having problems with the auto-generated routes for the geocoding service.

When I look into the auto generated class appProdUrlGenerator in prod cache (I'm using prod to make it faster), the routes generated are the same, but for the non default languages, the controler parameters in the first entry of the array are **slug** and not **id** as for English and French.

Does anyone have an  idea on where to change the code to generate the routes exactly the same way?

`'es__RG__cocorico_geo_create' => array (  0 =>   array (    0 => **'slug'**,  ),  1 =>   array (    '_controller' => 'Cocorico\\GeoBundle\\Controller\\GeocodingController::createAction',    '_locale' => 'es',  ),  2 =>   array (    'slug' => '[a-z0-9-]+',    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/create',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[a-z0-9-]+',      3 => 'slug',    ),    2 =>     array (      0 => 'text',      1 => '/es/geocoding',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),`

`'en__RG__cocorico_geo_create' => array (  0 =>   array (    0 => **'id'**,  ),  1 =>   array (    '_controller' => 'Cocorico\\GeoBundle\\Controller\\GeocodingController::createAction',    '_locale' => 'en',  ),  2 =>   array (    'slug' => '[a-z0-9-]+',    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/create',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/en/geocoding',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),`

`'pt_BR__RG__cocorico_geo_create' => array (  0 =>   array (    0 => **'slug'**,  ),  1 =>   array (    '_controller' => 'Cocorico\\GeoBundle\\Controller\\GeocodingController::createAction',    '_locale' => 'pt_BR',  ),  2 =>   array (    'slug' => '[a-z0-9-]+',    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/create',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[a-z0-9-]+',      3 => 'slug',    ),    2 =>     array (      0 => 'text',      1 => '/pt_BR/geocoding',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),`

`'fr__RG__cocorico_geo_create' => array (  0 =>   array (    0 => **'id'**,  ),  1 =>   array (    '_controller' => 'Cocorico\\GeoBundle\\Controller\\GeocodingController::createAction',    '_locale' => 'fr',  ),  2 =>   array (    'slug' => '[a-z0-9-]+',    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/create',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/fr/geocoding',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),`

**Comment by cocolabssas** [comment]
Hi,

We are fixing this issue.
In the meanwhile comment these lines : `Cocorico/CoreBundle/Resources/views/Frontend/Listing/show.html.twig:539-541`.
And clear your cache.

**Comment by eshelf** [comment]
Thanks for the prompt answer. I was able to fix it translating one key, as show in the picture below:

<img width="738" alt="slugidgeocoding" src="https://user-images.githubusercontent.com/31776829/33432044-4bc2fe38-d5b5-11e7-96e8-a2eebfd504e6.png">

**Comment by fakelefteye** [comment]
you have to change in the translation and put {id} instead of {slug} (like in the other languages on the right)
