### ISSUE TITLE
Support request - Someone could give a nginx conf file exemple?

### ISSUE THREAD

**Issue by zobba** [Cocolabs-SAS/cocorico#119]
| Q                | A
| ---------------- | -----

| Support request | yes

I don't know how to create rewrite rules...someone could give me un exmple?

Thank a lot!!!!

**Comment by cocolabssas** [comment]
Hi,

It should help you : https://symfony.com/doc/2.8/setup/web_server_configuration.html#nginx

**Comment by zobba** [comment]
hi, 

Thanks for these informations, it works for me! 

Cordialement

**Comment by cocolabssas** [comment]
Great :)
