### ISSUE TITLE
 Base table or view not found

### ISSUE THREAD

**Issue by khadija** [Cocolabs-SAS/cocorico#12]
Hello,

I installed the project to test crowing , but I don't find the script of the database in the source code , I get the following error appears:
Base table or view not found: 1146 Table ' cocorico_dev.listing_category ' does not exist "
Can you help me please ?

 Thanks

**Comment by khadija** [comment]
I have found the solution by running :
 ./bin/init-db php --env=dev

**Comment by cocolabssas** [comment]
Indeed you can find the answer in the README :)
https://github.com/Cocolabs-SAS/cocorico#initialize-the-sql-and-nosql-database
