### ISSUE TITLE
DO WE HAVE text field Characteristic?

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#120]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes
| Support request? | yes

Hello @cocolabssas  first of all congrats for php7 and I am looking fwd to symfony3 with it :)

I am working on it and find we have three type of Characteristic. Now my question is can we have text field Characteristic there the user can add data?

regards

**Comment by cocolabssas** [comment]
Hi @Atranaz 

Thanks and glad you like it :) 
For now this feature is not available. But indeed it could be an interesting functionality to add.

Hope it will be released soon.

**Comment by Atranaz** [comment]
@cocolabssas my pleasure Yes I am looking fwd for this.
