### ISSUE TITLE
already rent one option in Listing, Which table field responsible for this?

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#121]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| Support request? | yes

@cocolabssas hope you doing well and I hope everyone going well with cocorico 👍 

Need to ask one question? **already rent option** work with listing or user? If listing then which the table field responsible for chanege its status :) bcause right now I think i missed that field.

**Comment by cocolabssas** [comment]
Hi @Atranaz 

I hope you too :)

The "already rent option" depends on the User entity property "nbBookingsOfferer". This property contains the numbers of booking the user has made as offerer.
