### ISSUE TITLE
Issue while installing in Linux

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#123]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| Support request? | yes/no

I try to install this on linux ubuntu.
Everything going well but when i start install give me this error.

Problem 1
    - Installation request for alcaeus/mongo-php-adapter 1.1.3 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb has the wrong version (1.1.5) installed.
  Problem 2
    - Installation request for mongodb/mongodb 1.2.0 -> satisfiable by mongodb/mongodb[1.2.0].
    - mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb has the wrong version (1.1.5) installed.

I think have to update.
- Apache2
- Php 7.0

**Comment by eshelf** [comment]
Hi Atranaz,

You either don't have Mongo installed or it's not activated in the php.ini of your Apache server. Access your phpinfo and make sure that mongodb is configured to be used by your server. If not, follow these procedures:

- [ ] http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/?_ga=1.159299576.319082154.1425377029
- [ ] https://docs.mongodb.com/manual/mongo/

I'm using php 5.6 and Apache2 and it's working perfectly.

**Comment by cocolabssas** [comment]
Hi Atranaz,

Your error say:

> mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb has the wrong version (1.1.5) installed.

So the solution is to update your php **mongodb** (not mongo) extension to 1.3.x.

**Comment by Atranaz** [comment]
@eshelf  Yes, I try to install 1.3.0 but I don't know it's not installing don't know why.

Like I tried in Linux LAMP and Windows WAMP both sides it's not Installed.

I try to Install 1.2.0 its work fine but same error.

Any help from your site will be appreciated.

Current state
**Windows 10**
wamp with running two PHP
apache 2.4.23 / PHP 5.6.25 / PHP 7.0

**Linux Ubuntu 16.04** on virtual box 
Apche2 / Php 7

regards

**Comment by cocolabssas** [comment]
Hi @Atranaz 

Could you check the answer of tsounabe on SO?

**Comment by Atranaz** [comment]
@cocolabssas not yet but Yes tonight I'll check and update here as well :)

**Comment by Atranaz** [comment]
@cocolabssas Issue fixed but Yes with PHP 7.1 and I think its better :) now moving forward.
