### ISSUE TITLE
 Search while i drag the map

### ISSUE THREAD

**Issue by Damiano1376** [Cocolabs-SAS/cocorico#125]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Support request? | yes

In http://demo.cocorico.io i can see a box " Search while i drag the map" on the top of the google map. This option shows new results while moving on the map. What do i have to do to activate it?

**Comment by cocolabssas** [comment]
Hi Damiano1376,

For now this functionality is not yet on the Community edition. It should be added in the first quarter 2018.
