### ISSUE TITLE
Error in Booking Insertion 

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#127]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| Support request? | yes

Hello @cocolabssas  team, 

hope you are fine and happy new year :)

I have a issue during the booking I added new payment module its working fine but suddenly this user_id missing error is come and booking not working. Can you tell me why this happened.

Error
Error! An exception occurred while executing 'INSERT INTO booking (id, start, end, start_time, end_time, status, validated, amount, amount_fee_as_asker, amount_fee_as_offerer, amount_total, cancellation_policy, new_booking_at, payed_booking_at, refused_booking_at, canceled_asker_booking_at, alerted_expiring, alerted_imminent, message, createdAt, updatedAt, user_id, listing_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [44755462, "2018-01-04 00:00:00", "2018-01-05 00:00:00", "1970-01-01 06:00:00", "1970-01-01 07:00:00", 1, 0, 10000, 1000, 500, 11000, 1, "2018-01-03 09:06:30", null, null, null, 0, 0, "payment done", "2018-01-03 09:06:30", "2018-01-03 09:06:30", null, 1321209154]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column **'user_id' cannot be null**

**Comment by cocolabssas** [comment]
Hi Atranaz,

Happy new year to you too :)

Unfortunately we do not have time to debug custom developments on cocorico. I recommend you to debug what is happening when you create a new booking and why the user id is missing.
Ensure that booking user_id is equal to the user id making the booking request while booking creation.
Check booking initialization here https://github.com/Cocolabs-SAS/cocorico/blob/6d8b531309f45415dd716036cb84785063895677/src/Cocorico/CoreBundle/Controller/Frontend/BookingController.php#L77.
This is where the user id is set.

**Comment by Atranaz** [comment]
thanks :)
