### ISSUE TITLE
clean test messages, profiles, listings... to launch!

### ISSUE THREAD

**Issue by pruffier** [Cocolabs-SAS/cocorico#128]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

hello,

how can I clean the data, such as messages, profiles, listings...

because the majority of the data was to test the platform. wanted to clean that data.

thank you!

**Comment by cocolabssas** [comment]
Hello,

You can execute `php app/console doctrine:fixtures:load`. This will remove all your existing DB data and replace them by default data fixtures (asker, offerer and admin user, one listing, ...). 
See files in Cocorico/CoreBundle/DataFixtures/ORM/ to know what are the fixtures.
**Don't hesitate to backup your DB before in case you need to keep some data.**

**Comment by pruffier** [comment]
great!! thank you!!
