### ISSUE TITLE
New Search Filter 

### ISSUE THREAD

**Issue by amaurybrisou** [Cocolabs-SAS/cocorico#13]
Bonjour,

J'ai besoin d'ajouter un addOrderBy('certified', 'DESC'); dans Model\Manager\ListingSearchManager:search.

Il est bien intégré à la requête doctrine mais d'autre orderBy sont ajoutés après lui sans que je comprenne vraiment pourquoi ni comment ils arrivent.  voici un sample du code que j'ai : 

```
        $certified = $listingSearchRequest->getCertified();
        if($certified){
            $queryBuilder->addOrderBy('l.certified', 'DESC');
        }

        //Query
        $query = $queryBuilder->getQuery();
        $query->setHydrationMode(Query::HYDRATE_ARRAY);

        return new Paginator($query);
```

Auriez-vous une idée ?

Par ailleurs je ne trouve pas de Listener aux events : 

    const LISTING_SEARCH = 'cocorico.listing_search';
    const LISTING_SEARCH_ACTION = 'cocorico.listing_search.action';

Pourriez-vous m'aiguiller ?

merci d'avance

**Comment by ClemSche** [comment]
Bonjour,

Je suis en congés annuels du 06/07/16 au 15/07/16 inclus. Votre message a été transmis à Anthoni Noyon.

Clément Schereck

**Comment by cocolabssas** [comment]
Hello,

The query is overridden by CocoricoListingSearch Bundle in vendor directory.
Look at the ListingSearchSubscriber and you fill find how the query is overridden.

You can create your own subscriber listening LISTING_SEARCH event and override yourself the query.
