### ISSUE TITLE
Creating cocoricodocker_php-cli_1    ... error

### ISSUE THREAD

**Issue by ervanm** [Cocolabs-SAS/cocorico#134]
hey guys, 

When using docker install on a aws FT, i get this  error : Creating cocoricodocker_php-cli_1    ... error

ERROR: for php-cli  Cannot create container for service php-cli: create .: volume name is too short, names should be at least two alphanumeric characters

How can i get over it ?

Cheers

**Comment by giorgio654** [comment]
Hello @ervanm,

Thanks for the feedback, this issue will be fixed soon.
Could you post your docker issues in the [related repository](https://github.com/Cocolabs-SAS/cocorico-docker) in the future?
