### ISSUE TITLE
Error when add to Favourite 

### ISSUE THREAD

**Issue by rterreroalares** [Cocolabs-SAS/cocorico#135]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Support request? | no

Variable "form" does not exist in @CocoricoCore/Frontend/ListingResult/result.html.twig at line 55 when press "Favorites" link:

Level | Channel | Message
-- | -- | --
INFO                                                 13:30:00 | request | Matched route "cocorico_listing_favourite".                                           Context: { "route_parameters":  {"_controller":  "Cocorico\\CoreBundle\\Controller\\Frontend\\ListingFavouriteController::indexFavouriteAction",  "_locale": "en", "_route": "cocorico_listing_favourite"  },"request_uri": "http://cocorico.dev/en/listing/favourite" }
INFO                                                 13:30:00 | security | Populated the TokenStorage with an anonymous Token.
CRITICAL                                                 13:30:01 | request | Uncaught PHP Exception  Twig_Error_Runtime: "Variable "form" does not exist in  "@CocoricoCore/Frontend/ListingResult/result.html.twig" at line 55" at  /var/www/cocorico/Symfony/app/cache/dev/classes.php line 4953                                           Context: { "exception": "Object(Twig_Error_Runtime)" }

**Comment by cocolabssas** [comment]
Hi,

You can fix it by adding `'form' => $form->createView(),` in `Cocorico/CoreBundle/Controller/Frontend/ListingFavouriteController.php:61` : 

```
...
return $this->render(
            '@CocoricoCore/Frontend/ListingResult/result.html.twig',
            array(
                'form' => $form->createView(), //here is the fix
                'listings' => $listings,
...
```

And by changing the scope of the method  `\Cocorico\CoreBundle\Controller\Frontend\ListingSearchController::createSearchResultForm` from public to protected line 112:

```
...
protected function createSearchResultForm(ListingSearchRequest $listingSearchRequest)
    {
        $form = $this->get('form.factory')->createNamed(
...
```

It would be helpful you'd make a PR with this modifications to fix this issue.

Thanks for this feedback.

**Comment by rterreroalares** [comment]
After applying the fix:

```
Neither the property "price_range" nor one of the methods "price_range()", "getprice_range()"/"isprice_range()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView".
500 Internal Server Error - Twig_Error_Runtime
```
Stack Trace
in src/Cocorico/CoreBundle/Resources/views/Frontend/ListingResult/form_search_filters.html.twig at line 7   -

```
4    <!-- range-area -->
5    <div class="range-area">
6        <!-- range-holder -->
7        {{ form_widget(form.price_range) }}
8
9        {% if bundleExist('CocoricoDeliveryBundle') %}
10            {% include '@CocoricoDelivery/Frontend/ListingResult/_form_delivery.html.twig' with {
```

at Twig_Template ->getAttribute (object(FormView), 'price_range', array()) 
in app/cache/dev/twig/87/87a7a9e6b64e0895c7917fa6695f40e4555e832f1e6c0329e11671d7a918e70e.php at line 29  

```
26        <!-- range-holder -->
27        ";
28        // line 7
29        echo $this->env->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')->renderer->searchAndRenderBlock($this->getAttribute(($context["form"] ?? $this->getContext($context, "form")), "price_range", array()), 'widget');
30        echo "
31
32        ";

```

**Comment by cocolabssas** [comment]
I missed to add this modification : 

In `Cocorico/CoreBundle/Controller/Frontend/ListingFavouriteController.php:37 :`

Replace:

`$form = $this->createSearchForm($listingSearchRequest);` by

`$form = $this->createSearchResultForm($listingSearchRequest);`

Once it works on your side we will be glad to have a PR :)

Thanks

**Comment by rterreroalares** [comment]
Ok! 
Thanks. You have a PR :+1:

**Comment by cocolabssas** [comment]
Thanks rterreroalares :) I reopen it because it is not already merged. It will be merged in a few instants ;)
