### ISSUE TITLE
Template Overriding in Cocorico

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#139]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

Hello @cocolabssas team,

hows going waiting for your new release for symfony latest version then definitely create video how to install Cocorico because it most asked question :) & I hope you guys help me in this.

Now my Question is how I can override Cocorico and already overridden template and controller?

Normally in Symfony we create same directory in **src** file for this task but in cocorico case we have lots of bundle already overridden & cocorico is also in **src** directory so how can i Override this template and Controller???

I hope you can understand my Question :)

**Comment by cocolabssas** [comment]
Hi @Atranaz

We will communicate on Cocorico SF 3.4 upgrade as soon as it will be available no later than the second quarter of 2018.
Furthermore we are going to publish a new web site dedicated to Cocorico documentation and tutorials. 
You can follow https://twitter.com/cocorico_rocks to keep informed on all of this.

To answer to your clear ;) question you can override templates as Symfony [describe it](https://symfony.com/doc/2.8/bundles/inheritance.html) :
either in app/Resources/ or you can create bundles overriding Cocorico ones in a src/App folder like this for example : src/App/CocoricoCoreBundle/.

Thanks!

**Comment by Atranaz** [comment]
@cocolabssas Thanks, waiting for that & I will check template overriding and update you :)

**Comment by Atranaz** [comment]
@cocolabssas  In your example is pretty simple example that i practice already now my question is

you already override sonataadminbundle with **src/Cocorico/SonataAdminBundle** and now how I can override this **bundle**

**Comment by cocolabssas** [comment]
@Atranaz It is as pretty simple as my example and Symfony bundle overriding practice you already now.

For example to override Cocorico/SonataAdminBundle templates : 

1. Create the following : 

- src/App/SonataAdminBundle
- src/App/SonataAdminBundle/AppSonataAdminBundle.php
```
<?php
namespace App\SonataAdminBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppSonataAdminBundle extends Bundle
{
    public function getParent()
    {
        return 'CocoricoSonataAdminBundle';
    }

}
```

2. Add it to your AppKernel.php

```
...
public function registerBundles()
    {
        $bundles = array(
            ...
            new \App\SonataAdminBundle\AppSonataAdminBundle(),
        );
...
```

3. Create the following folder `src/App/SonataAdminBundle/Resources/views/` and add for example `standard_layout.html` in it if you want to override Cocorico standard_layout.html.

Hope it helps

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
