### ISSUE TITLE
composer install errors

### ISSUE THREAD

**Issue by bailoo** [Cocolabs-SAS/cocorico#140]
| Support request? | yes

Hi there :)

I am exploring cocorico for my marketplace. Before going for the enterprise edition, I want to play around with the community edition so that I can get a feel for it. 

When I run composer install I run into this error. 

Problem 1
    - Installation request for alcaeus/mongo-php-adapter 1.1.3 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
  Problem 2
    - Installation request for mongodb/mongodb 1.2.0 -> satisfiable by mongodb/mongodb[1.2.0].
    - mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb is missing from your system.

When I have manually installed php mogodb extension, I run into another error. 

Apparently, this is related to https://github.com/alcaeus/mongo-php-adapter/issues/30 

Please help me move ahead?

Thanks in advance,
Abhishek

**Comment by cocolabssas** [comment]
Hi @bailoo,

Could you ensure that you have php 7.1 and PHP mongodb 1.3 (not mongo) extension enabled?
Could you also communicate the another error you have when you have installed PHP mongodb extension.

Thanks!

**Comment by cocolabssas** [comment]
Feel free to reopen it if your problem still exists.
