### ISSUE TITLE
Import Large Dataset of Listings / REST API

### ISSUE THREAD

**Issue by bailoo** [Cocolabs-SAS/cocorico#144]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

I want to import a large dataset of around 17k listings and users into Cocorico. What method would you recommend ? 

On a related note, I was looking for REST API for Cocorico, but I could not find it. Will it be a good idea to have a REST API for all the methods ? That would make it easy to separate the front end from the back end and make things more modular, making such import / export tasks super easy. Any ideas around the best way to make a REST API would be welcome too.

**Comment by cocolabssas** [comment]
Hi bailoo,

Indeed we are already planning to APIfy Cocorico. In the meanwhile you can implement for example a  Symfony command that will migrate your listings and users from your DB into Cocorico DB.
Some of the important work (API or not) should be to make the relations between your data structure and the Cocorico one. 

Hope it helps!

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
