### ISSUE TITLE
Back Guideline Need it

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#146]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ Yes]

Hello @cocolabssas  hope you are fine and doing good!

I need guide line to how modified backed & add some new feature in it e.g create user change status of listing from backend

**Comment by cocolabssas** [comment]
Hi @Atranaz 

We hope you are doing good too :)

Backend is made with [SonataAdmin ](https://sonata-project.org/bundles/admin/3-x/doc/index.html). You will find plenty informations on its documentation and in stackoverflow for example. 

To answer to  your question about adding a user in backend you need to : 
- Allow users creation by commenting this line : 
[ Cocorico/UserBundle/Admin/UserAdmin.php:458](https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/UserBundle/Admin/UserAdmin.php#L458)

- Allow modification of required fields by removing ` 'disabled' => true,` in corresponding form fields. Example for first name field : 
[Cocorico/UserBundle/Admin/UserAdmin.php:69](https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/UserBundle/Admin/UserAdmin.php#L69) 

Concerning listing status modification in backend it is already possible.

Hope it helps!

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
