### ISSUE TITLE
Sql query error in main page

### ISSUE THREAD

**Issue by superalex88** [Cocolabs-SAS/cocorico#148]
| Q                | A
| ---------------- | -----
| Bug report?      | [X ]
| Feature request? | [ ]
| Support request? | [X ]

Hi I'm trying cocorico but I'm facing this problem: if I deploy using docker all works well but if i deploy in standalone mode the main page doesn't work.
Checking in prod-xxx.log file i see this error:

`[2018-03-02 16:20:34] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT DISTINCT id_1 FROM (SELECT '' AS sclr_0, l0_.id AS id_1, l0_.price AS price_2, l0_.certified AS certified_3, l0_.average_rating AS average_rating_4, l0_.createdAt AS createdAt_5, l1_.title AS title_6, l1_.description AS description_7, l1_.slug AS slug_8, l1_.locale AS locale_9, l1_.id AS id_10, l2_.id AS id_11, l3_.id AS id_12, l3_.lft AS lft_13, l3_.lvl AS lvl_14, l3_.rgt AS rgt_15, l3_.root AS root_16, l4_.name AS name_17, l4_.locale AS locale_18, l4_.id AS id_19, l5_.id AS id_20, l5_.name AS name_21, u6_.id AS id_22, u6_.first_name AS first_name_23, u7_.id AS id_24, u7_.name AS name_25, l8_.id AS id_26, l8_.country AS country_27, l8_.city AS city_28, l8_.route AS route_29, g9_.id AS id_30, g9_.lat AS lat_31, g9_.lng AS lng_32, l4_.locale AS locale_33, u7_.position AS position_34, l1_.locale AS locale_35, l0_.status AS status_36, l0_.createdAt AS createdAt_37 FROM listing l0_ LEFT JOIN listing_translation l1_ ON l0_.id = l1_.translatable_id LEFT JOIN listing_listing_category l2_ ON l0_.id = l2_.listing_id LEFT JOIN listing_category l3_ ON l2_.listing_category_id = l3_.id LEFT JOIN listing_category_translation l4_ ON l3_.id = l4_.translatable_id AND (l4_.locale = ?) LEFT JOIN listing_image l5_ ON l0_.id = l5_.listing_id LEFT JOIN `user` u6_ ON l0_.user_id = u6_.id LEFT JOIN user_image u7_ ON u6_.id = u7_.user_id AND (u7_.position = 1) LEFT JOIN listing_location l8_ ON l0_.location_id = l8_.id LEFT JOIN geo_coordinate g9_ ON l8_.coordinate_id = g9_.id WHERE l1_.locale = ? AND l0_.status = ? ORDER BY l5_.position asc, u7_.position asc) dctrn_result ORDER BY createdAt_5 DESC LIMIT 6' with params ["en", "en", 2]:  SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.createdAt_5' which is not in SELECT list; this is incompatible with DISTINCT" at /var/www/35.195.52.79/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT DISTINCT id_1 FROM (SELECT '' AS sclr_0, l0_.id AS id_1, l0_.price AS price_2, l0_.certified AS certified_3, l0_.average_rating AS average_rating_4, l0_.createdAt AS createdAt_5, l1_.title AS title_6, l1_.description AS description_7, l1_.slug AS slug_8, l1_.locale AS locale_9, l1_.id AS id_10, l2_.id AS id_11, l3_.id AS id_12, l3_.lft AS lft_13, l3_.lvl AS lvl_14, l3_.rgt AS rgt_15, l3_.root AS root_16, l4_.name AS name_17, l4_.locale AS locale_18, l4_.id AS id_19, l5_.id AS id_20, l5_.name AS name_21, u6_.id AS id_22, u6_.first_name AS first_name_23, u7_.id AS id_24, u7_.name AS name_25, l8_.id AS id_26, l8_.country AS country_27, l8_.city AS city_28, l8_.route AS route_29, g9_.id AS id_30, g9_.lat AS lat_31, g9_.lng AS lng_32, l4_.locale AS locale_33, u7_.position AS position_34, l1_.locale AS locale_35, l0_.status AS status_36, l0_.createdAt AS createdAt_37 FROM listing l0_ LEFT JOIN listing_translation l1_ ON l0_.id = l1_.translatable_id LEFT JOIN listing_listing_category l2_ ON l0_.id = l2_.listing_id LEFT JOIN listing_category l3_ ON l2_.listing_category_id = l3_.id LEFT JOIN listing_category_translation l4_ ON l3_.id = l4_.translatable_id AND (l4_.locale = ?) LEFT JOIN listing_image l5_ ON l0_.id = l5_.listing_id LEFT JOIN `user` u6_ ON l0_.user_id = u6_.id LEFT JOIN user_image u7_ ON u6_.id = u7_.user_id AND (u7_.position = 1) LEFT JOIN listing_location l8_ ON l0_.location_id = l8_.id LEFT JOIN geo_coordinate g9_ ON l8_.coordinate_id = g9_.id WHERE l1_.locale = ? AND l0_.status = ? ORDER BY l5_.position asc, u7_.position asc) dctrn_result ORDER BY createdAt_5 DESC LIMIT 6' with params [\"en\", \"en\", 2]:\n\nSQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.createdAt_5' which is not in SELECT list; this is incompatible with DISTINCT at /var/www/35.195.52.79/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.createdAt_5' which is not in SELECT list; this is incompatible with DISTINCT at /var/www/35.195.52.79/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.createdAt_5' which is not in SELECT list; this is incompatible with DISTINCT at /var/www/35.195.52.79/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []`

![cocorico_error_1](https://user-images.githubusercontent.com/5698133/36909535-8aafabf6-1e3e-11e8-8bf1-c5a3f0d07cae.png)

So it seems that somewhere an sql query is written in a wrong way. In fact if i execute that query directly on sql server it tells me the same thing. If i remove the ORDER BY part the query works. 
Am i missing something?

thanks

**Comment by cocolabssas** [comment]
This is related to a doctrine / mysql version bug. See #124 to know how to fix the issue.

**Comment by superalex88** [comment]
ok i fixed..maybe will be useful adding the bug reference in the installation guide.
