### ISSUE TITLE
[Docker installation / SQL issue] Base table or view not found: 1146 Table 'cocorico.user' doesn't exist

### ISSUE THREAD

**Issue by matino34** [Cocolabs-SAS/cocorico#149]
| Bug report?      | [ ]

I'm using  Docker installation msg error on main page : 
An exception occurred while executing 'SELECT DISTINCT id_1 FROM (SELECT '' AS sclr_0, l0_.id AS id_1, l0_.price AS price_2, l0_.certified AS certified_3, l0_.average_rating AS average_rating_4, l0_.createdAt AS createdAt_5, l1_.title AS title_6, l1_.description AS description_7, l1_.slug AS slug_8, l1_.locale AS locale_9, l1_.id AS id_10, l2_.id AS id_11, l3_.id AS id_12, l3_.lft AS lft_13, l3_.lvl AS lvl_14, l3_.rgt AS rgt_15, l3_...

**Comment by cocolabssas** [comment]
Hello Matino,

It sounds like the installation was not finished when you accessed localhost. Could you wait to see  

> [OK] Server running on http://0.0.0.0:8000

in the progress of the installation [http://localhost:9001/logtail/cocorico](http://localhost:9001/logtail/cocorico) before accessing localhost.

PS: For your eventual next issue on cocorico-docker please add it to the https://github.com/Cocolabs-SAS/cocorico-docker repository.

Thanks,

**Comment by giorgio654** [comment]
Hello Matino,
A new issue has been created https://github.com/Cocolabs-SAS/cocorico-docker/issues/4 relating to yours.
