### ISSUE TITLE
Fix who received notifications message by Email 

### ISSUE THREAD

**Issue by sfmok** [Cocolabs-SAS/cocorico#150]
https://github.com/Cocolabs-SAS/cocorico/blob/2147e2e5931170097a6a3b09041b5adf6728beb0/src/Cocorico/MessageBundle/Model/ThreadManager.php#L173

NB : This is not issue. It's only a minor fix for who received mail notification when reply by message : 

```
$user = $this->tokenStorage->getToken()->getUser();`
$receiver = $booking->getUser() == $user 
            ? $booking->getListing()->getUser() // offerer
            : $booking->getUser() ; // asker
        
$this->mailer->sendNotificationForNewMessageToUser($receiver, $thread);
````

You need to inject tokenStorage.

Thanks

**Comment by cocolabssas** [comment]
Hi @sfmok 

Thanks for this suggestion :)
We did it in a recent commit c8c3e8cdb8de92e4da6b649acc8cdd72e33abb47.
