### ISSUE TITLE
affiliate code

### ISSUE THREAD

**Issue by pruffier** [Cocolabs-SAS/cocorico#152]
| Q                | A
| ---------------- | -----
| Bug report?      | [no ]
| Feature request? | [ yes ]
| Support request? | [no ]

is there any solution for affiliate code?

**Comment by cocolabssas** [comment]
Hello pruffier,

For now there is no affiliate code functionality in Cocorico.
Maybe it will be useful to precise your need if someone want to implement it.

Thanks,
