### ISSUE TITLE
Problem of putting into production

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#154]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi,

I have a problem when I want to put the project into production, yet when it is in mode dev everything is ok.

When he is in prod in the symfony logs I have:

> Fatal error: Call to undefined function Doctrine\Common\Cache\apc_fetch()

and the page sends me a error 503 .

Yet "opcache" is installed when I type "php -m" , zend opcache is in the list.

here is my conf nginx:

```
server {
        listen 443 ssl;
        root /var/www/dev/Symfony/web;
        server_name dev.test.fr;
        ssl_certificate /etc/letsencrypt/live/dev.test.fr/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dev.test.fr/privkey.pem;
 
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
 
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers EECDH+AESGCM:EECDH+AES;
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;
 
        # Autres directives ici
 
        satisfy any; allow all;
 
        location / {
        # try to serve file directly, fallback to app.php
          try_files $uri /app_dev.php$is_args$args;
          #try_files $uri /app.php$is_args$args;
        }
        # DEV
        # This rule should only be placed on your development environment
        # In production, don't include this and don't deploy app_dev.php or config.php
        location ~ ^/(app_dev|config)\.php(/|$) {
          include /etc/nginx/fastcgi_params;
          fastcgi_pass unix:/var/run/php-fpm.socket;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         }
         # PROD
        location ~ ^/app\.php(/|$) {
          fastcgi_pass unix:/var/run/php-fpm.socket;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include /etc/nginx/fastcgi_params;
         # When you are using symlinks to link the document root to the
         # current version of your application, you should pass the real
         # application path instead of the path to the symlink to PHP
         # FPM.
         # Otherwise, PHP's OPcache may not properly detect changes to
         # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
         # for more information).
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
 
         # Prevents URIs that include the front controller. This will 404:
         # http://domain.tld/app.php/some-path
         # Remove the internal directive to allow URIs like this
 
         #internal;
      }
 
         # return 404 for all other php files not matching the front controller
         # this prevents access to other php files you don't want to be accessible.
        location ~ \.php$ {
          return 404;
      }
 
      error_log /var/log/nginx/project_error.log;
      access_log /var/log/nginx/project_access.log;
}

```

I do not know where it may come from, thank you for your future help.

I have a second question about the registration form in the demo we see the choice of radio buttons "You are: a person a company" but in mine it is missing. see : http://i.imgur.com/8rduChO.png

Good job cocorico :)

**Comment by cocolabssas** [comment]
Hello @gonzasylv,

Thanks for the compliment :)
To resolve your APC related issue you need to install PHP module APCu.
Concerning the person type in registration form for now it is available on Enterprise edition. It will be available in Community edition in a while.  In the meanwhile  you can add this field in the registration form. 

Hope it helps

**Comment by gonzasylv** [comment]
I have yet "apcu" when I do php -m, there is there a setting in particular to perform?

here is my mistake:

> root@mx:/var/www/dev/Symfony# tail -f app/logs/prod-2018-04-09.log
[2018-04-09 21:29:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Fatal error: Call to undefined function Doctrine\Common\Cache\apc_fetch()" at /var/www/dev/Symfony/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php line 41 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Fatal error: Call to undefined function Doctrine\\Common\\Cache\\apc_fetch() at /var/www/dev/Symfony/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php:41)"} []

[2018-04-09 21:29:29] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "cocorico_user.user_manager", path: "sonata.admin.listing -> validator -> validator.builder -> cocorico_user.user_manager -> twig.controller.exception -> twig -> security.authorization_checker -> security.authentication.manager". at /var/www/dev/Symfony/app/bootstrap.php.cache line 2173) {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceCircularReferenceException(code: 0): Circular reference detected for service \"cocorico_user.user_manager\", path: \"sonata.admin.listing -> validator -> validator.builder -> cocorico_user.user_manager -> twig.controller.exception -> twig -> security.authorization_checker -> security.authentication.manager\". at /var/www/dev/Symfony/app/bootstrap.php.cache:2173)"} []

**Comment by gonzasylv** [comment]
It's ok thanks :)

The bundle for payment will be available soon? mangopay? it's really the only thing missing, you really do a good job!
