### ISSUE TITLE
Put into production

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#155]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi cocolabs,

Where is the config for setting up the port for project deployment?

When I type:

> php app/console project:deploy --go prod

I have like return ::

> root@mx:/var/www/dev/Symfony# php app/console project:deploy --go prod
> Deploying on prod server with rsync  -azC --force --delete --progress -h --checksum --exclude-from="/var/www/dev/Symfony/app/config/rsync_exclude.txt" -e "ssh -p 22" ./ wedder@dev.test.fr:/var/www/dev/Symfony command
> 
> START deploy
> --------------------------------------------
> ERR > ssh: connect to host dev.test.fr port 22: Connection refused
> ERR > rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
> 
> END deploy
> --------------------------------------------
> 
> Deployed on prod server!

I work on another port than the 22

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

You can change it here :  `src/Cocorico/CoreBundle/Resources/config/config_dev.yml:16`

**Comment by gonzasylv** [comment]
Its ok , thanks.

**Comment by enuelmorales-snoop** [comment]
Hi!  It happens to me that when deploying production with the command deploy that is in the doc it returns "rsync not found" I am using the image of Docker cocorico, I enter by sh to the container and run the deploy ... Anything idea?
