### ISSUE TITLE
Bundle payment 

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#156]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi,

I had a request for another issue but I will make a separate property.

The bundle for payment (mangopay) will be available soon? cocorico is a very good platform but it lacks the final touch which is the payment.

Can we know the reasons for the lack of its module and if it will be available to the community soon?

I think this is a request expected by many people.

Thank you :)

**Comment by cocolabssas** [comment]
Hello @gonzasylv 

The payment bundle Mangopay will be available to the community shortly (normally in the second Quarter 2018). We will communicate on it as it will be available.

Thanks again for your compliments and your star ;)

**Comment by gonzasylv** [comment]
Ok, we are looking forward to the announcement :)

**Comment by fgouzi** [comment]
Hello Cocolabssas

I'm looking for your payment bundle Mangopay. Are you still looking to put it into the community edition? Do you have any information about the availability date?

Tanks and best regards

**Comment by ElwardFletcher** [comment]
According to Mangopay's website, Cocolabs is an official partner, so I imagine there's already a solution out there, no?
