### ISSUE TITLE
Cannot create user, error message " UnexpectedValueException"

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#157]
| Q                | A
| ---------------- | -----
| Bug report?      | [ X]
| Feature request? | [ ]
| Support request? | [ ]

Hi, i tried to create a new user via CLI with this command like described in the docs:

php app/console fos:user:create testuser test@example.com p@ssword

But whenever i try i get the following error:

[UnexpectedValueException]                                                                   
Sluggable expects to have at least one usable (non-empty) field from the following: [ 0,1 ] 

Do i have to escape the input or put them in quotes?

I also tried the command with direct input requests but the same result. 

Thanks in advance

Edit: As far as I can tell the FOSUserBundle had been correctly installed. At least the rest of cocorico is working, that install worked well and I followed all steps.

**Comment by cocolabssas** [comment]
Hello,

Cocorico users have many specificities comparing to FOS User Bundle and does not embed yet the corresponding FOS User creation command. 
For now Cocorico allow you to add user from registration page, Symfony fixture command (See Cocorico/CoreBundle/DataFixtures/ORM/UserFixtures.php ) or SQL. 
If you really need it i suggest you to look at Cocorico User Fixtures and FOS User command to create  your own command.

**Comment by handmade-it** [comment]
Hi, thanks for the reply and the clarification. What I don't understand is, why you put the command I referred to into the documentation? Thanks in advance, Thomas

**Comment by cocolabssas** [comment]
This command is not in the Cocorico documentation but in the Fos User bundle documentation.

**Comment by handmade-it** [comment]
Hi, thanks for the clarification.
