### ISSUE TITLE
Deleting a user account

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#158]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

Hi, could you please point out how to delete a user. The docs only speak about user roles and activation, de-activation but I'd like to completely delete a user. Is this possible and how. Thanks in advance!

**Comment by cocolabssas** [comment]
Hello,

In Cocorico admin most of entities deletion is not enabled. 
If you want to allow user deletion from admin you just have to comment this line : `Cocorico/UserBundle/Admin/UserAdmin.php:459:  $collection->remove('delete');`
You will then have a delete button in User form.

**Comment by handmade-it** [comment]
Thanks that solves my problem!
