### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#159]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x ]

Hello,

I must have a problem with apcu (cache system) when I add a category or an ad, it takes a few hours to be available on the site, someone to already solve the problem?

I saw this issue:

https://github.com/Cocolabs-SAS/cocorico/issues/101

but I did not understand how he settled the worry.

Thanks !

**Comment by cocolabssas** [comment]
Hello @gonzasylv,

To fix your problem you can either : 

- clear cache
- decrease cache time on result cache queries by finding and modifying corresponding `useResultCache` method calls. 

Ex for categories: 
```
#Cocorico/CoreBundle/Repository/ListingCategoryRepository.php:50:
#Decrease cache expiration time
$query->useResultCache(true, 43200, 'findCategories');

#Cocorico/CoreBundle/Repository/ListingCategoryRepository.php:68
$query->useResultCache(true, 43200, 'findCategoriesByIds');
```

- implement an invalidation cache mechanism


Hope it helps!

**Comment by gonzasylv** [comment]
Ok thanks :)

**Comment by gonzasylv** [comment]
For categories, it's good, I also want to change the value of the cache on the "New Ads" on the home page?

Which file should it be modified?
