### ISSUE TITLE
JS is not compiled

### ISSUE THREAD

**Issue by ARogovsky** [Cocolabs-SAS/cocorico#16]
Hi!
I have issue - js is not compiled.
http://www.sharyng.com/js/compiled/all_bootstrap-multiselect_1.js

How to fix it?

**Comment by BenjaminPE** [comment]
Bonjour,

Je serais en congés jusqu'au 31/08/2016 inclus. Votre mail sera traité par Henri Phe.

Cordialement,

Benjamin Perrault

**Comment by cocolabssas** [comment]
Hi,

This functionality will be available soon. In the meanwhile you can do the following tasks:

1. `composer require patchwork/jsqueeze`
# app/config/config.yml
assetic:
    filters:
        jsqueeze: ~
        # ...

**Comment by BenjaminPE** [comment]
Bonjour,

Je serais en congés jusqu'au 31/08/2016 inclus. Votre mail sera traité par Henri Phe.

Cordialement,

Benjamin Perrault

**Comment by SOFRACS** [comment]
Bonjour,

Suivant l'heure je suis actuellement en boite de nuit ou à la plage. Je serai de retour le 30/08.

D'ici là vous pouvez contacter les personnes suivantes:

Dossiers commerciaux > Clément Schereck : schereck@sofracs.com
Projets et productions en cours > Henri Phe : phe@sofracs.com
Comptabilité > Astrid Spiegl : spiegl@sofracs.com

Pensant fort à vous,

Anthoni Noyon

**Comment by cocolabssas** [comment]
Bonjour,

Suivant l'heure je suis actuellement en boite de nuit ou à la plage. Je serai de retour le 30/08.

D'ici là vous pouvez contacter les personnes suivantes:

Dossiers commerciaux > Clément Schereck : schereck@sofracs.com
Projets et productions en cours > Henri Phe : phe@sofracs.com
Comptabilité > Astrid Spiegl : spiegl@sofracs.com

Pensant fort à vous,

Anthoni Noyon

**Comment by cocolabssas** [comment]
Hi,

This functionality will be available soon. In the meanwhile you can do the following tasks:

1 Execute:
```bash
composer require patchwork/jsqueeze`
```

2 Edit app/config/config.yml

```yaml
assetic:
    filters:
        jsqueeze: ~
```

3 Edit base.html.twig and replace 
```twig
output='js/compiled/all.js'
```
 by

```twig
filter='?jsqueeze' output='js/compiled/all.js'
```

The ? in jsqueeze tells to only compile in prod env.
