### ISSUE TITLE
Price bracket

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#160]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi,

There is a possibility to set the price bracket? http://imgur.com/QJE3nYxl.png

The increase of 10 000 € for example

I did not find in the parameters.yml

Thanks.

**Comment by cocolabssas** [comment]
Hello,

Yes you can.
You can change the value of `cocorico.listing_price_max parameter` here   Cocorico/CoreBundle/Resources/config/parameters.yml:124. 

Hope it helps.

Thanks

**Comment by gonzasylv** [comment]
Its ok, thank you for your reactivated :)
