### ISSUE TITLE
Disable FB auth 

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#161]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi, is it possible to deactive the FB oauth via any configuration or is it enough to not set the cocorico.facebook.app_id and secret? I kept them empty but the login still appears in the frontend. Did this mean that i have to remove it by hand from the twig templates? 

Thanks in advance

**Comment by cocolabssas** [comment]
Hello, 

You can disable the FB button by **setting the id / secret parameters  to false**  and by following these steps :

1. Create this template:
`src/Cocorico/UserBundle/Resources/views/Frontend/Common/_login_facebook.html.twig`

2. Add this content in it:
```
{% trans_default_domain 'cocorico_user' %}

<div class="column">
    {% if cocorico_facebook_id %}
    <h3>{{ 'user.facebook.login.title'|trans }}</h3>
    <a href="#" onclick="fb_login();" class="btn-facebook">
        <i class="icon-facebook"></i>
        {{ 'user.facebook.login'|trans }}
    </a>

    <div id="fb-root"></div>
    {% endif %}
</div>
```

3. Replace the div block in 
`src/Cocorico/UserBundle/Resources/views/Frontend/Common/_login.html.twig:46` and `src/Cocorico/UserBundle/Resources/views/Frontend/Common/_register.html.twig:170`  
by that:
`{% include '@CocoricoUser/Frontend/Common/_login_facebook.html.twig'  only %}`

We would need you make a Pull Request to add this new functionality to Cocorico :)

Thanks in advance!

**Comment by handmade-it** [comment]
Hi, thanks for the code. It worked!
I only changed your suggested _login_facebook.html.twig to look like this

{% trans_default_domain 'cocorico_user' %}

{% if cocorico_facebook_id %}
<div class="column">
    <h3>{{ 'user.facebook.login.title'|trans }}</h3>
    <a href="#" onclick="fb_login();" class="btn-facebook">
        <i class="icon-facebook"></i>
        {{ 'user.facebook.login'|trans }}
    </a>

    <div id="fb-root"></div>
</div>
{% endif %}

This avoids the empty column where the FB login had been
