### ISSUE TITLE
Restrict new listing to authenticated users only

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#162]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi, I try to find an option that you obviously have enabled at your demo site. I would like to restrict the creation of new listing to accounts that are logged in or redirect user from .../listing/new to the login page. But I cannot find this settings. 

Any advice is highly appreciated.
Thanks in advance!

**Comment by cocolabssas** [comment]
Hi,

This feature will be available in Community edition shortly. We will communicate on it as it will be available.

**Comment by handmade-it** [comment]
Hi, I found a workaround for this problem. I changed the new.html.twig to include an if statement like this

{%- if not is_granted("IS_AUTHENTICATED_FULLY") -%}
...

which decides if the form is getting rendered or not.
