### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#163]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi, sorry to bother you with so many issues but I could neither find anything in your docs nor here in other questions. I would like to create a custom 404-page for invalid urls but so far I only get the Symfony "No route found for "GET ..." message with error trace. Your demo site obviously has such configuration. Could you please point me in the right direction?

Thanks in advance!!

**Comment by cocolabssas** [comment]
Hello,

It is normal that in dev environment you see this debugging error pages. By default custom error pages are displayed only in production environment. Furthermore if you need to customize error pages content in production environment you have to edit these templates : 
`app/Resources/TwigBundle/views/Exception/error404.html.twig`, ...

**Comment by handmade-it** [comment]
Hi, thanks for the clarification. In order to style and check the custom error page it would be necessary to see them in the dev environement. Is this anyhow possible, even if its a "quick hack"?

**Comment by cocolabssas** [comment]
Hi,

It seems to be explained here : https://symfony.com/doc/2.8/controller/error_pages.html#testing-error-pages-during-development

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
