### ISSUE TITLE
Add APIs for sells & cutomers

### ISSUE THREAD

**Issue by bricemaurin** [Cocolabs-SAS/cocorico#164]
When a purchase is made, it's often useful to be able to push the customer to a CRM, mailchimp or any other tool.

It would be great if we could add an API to cocorico so that we can pull data from the back, such as:
- customers (sorted by purchase date desc ?)
- orders (sorted by purchase date desc ?)

This is the bare minimum, but I'm sure adding more apis would really help shop owners drive more loyalty & sells

Thks
Brice

**Comment by cocolabssas** [comment]
Hello Brice,

We already have planned to API-fy Cocorico. See [ROADMAP](https://github.com/Cocolabs-SAS/cocorico/blob/master/ROADMAP.md#architecture-evolution).
We will implement it as soon as possible. 

Thanks!

**Comment by bricemaurin** [comment]
Great news !

The roadmap doesn't mention any ETA, do you have any idea about when it
could be released?
-- 
[image: deux.io]
Brice Maurin  Fondateur

deux.io | growth marketing agency
m: +33.6.01.18.94.59 <javascript:void(0);>
w: deux.io
e: brice@deux.io
a: 8 rue du caire, 75002 Paris
Follow us:
[image: facebook] <https://www.facebook.com/deuxio> [image: linkedin]
<https://www.linkedin.com/company/deux-io> [image: twitter]
<https://twitter.com/deuxio>

**Comment by cocolabssas** [comment]
We don't know yet but it does not have a low priority. We will mention it on the ROADMAP as soon as we will know.

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed

**Comment by bricemaurin** [comment]
Shouldn't you keep it active until resolved ? This is usually the best practice for open source project, to centralize the needs regarding a single feature request.
