### ISSUE TITLE
SEO: Ability to edit SEO basics

### ISSUE THREAD

**Issue by bricemaurin** [Cocolabs-SAS/cocorico#165]
SEO can be a huge benefit for ecommerces. Current version of cocorico doesn't support basic SEO optimisations. Adding these basics would greatly help shop owners drive more sell.

Especially
- edit meta title, description
- add canonical url to all pages
- edit robots.txt file
- edit sitemap.xml file

even better, some advanced seo meta:
- edit json ld schema
- edit href lang per page

Thanks !

**Comment by cocolabssas** [comment]
Hello @bricemaurin ,

You seem to have missed some features of Cocorico:

- Meta title and description are editable. You have to go to the **Administration > translations** menu and choose the "cocorico_meta" domain. You will then be able to edit meta title and description of the application pages like **Home, Result, Listing, Listing deposit, Booking request, ...** in all available languages. You can also completely edit the content of custom pages like **FAQ, Who we are, ...** as well as, their meta titles and description in all available languages of your platform by accessing the menu **Administration > Site > pages** .

- Concerning edition of files like robots.txt or sitemap.xml you can simply edit them on the machine hosting the files of your application. 

Concerning other points we will look into them.

Thanks for your suggestion!

**Comment by bricemaurin** [comment]
Great news ! Could you elaborate on the meta edition ? how to include variables (product.category, product.name) in the results / listings meta data ?

Concerning canonical url & schema, is that on your roadmap ?

**Comment by cocolabssas** [comment]
For now these variables are suffixed to the meta and are not included in them. 
We just add the **enhancement** label to this post.

Thanks for your suggestion!

**Comment by bricemaurin** [comment]
did you implement it finally ?
