### ISSUE TITLE
installation directory not writable

### ISSUE THREAD

**Issue by LucaAghemo** [Cocolabs-SAS/cocorico#166]
| Support request? | [X]

Hello, I apologize from the beginning because this is a REALLY newbie question, but I'm stuck, so...
I'm installing Cocorico on a clean (just installed from scratch) Ubuntu 16.04 server machine. I followed all the steps (all went well) until I have to install Composer.
When I input the command: "curl -s http://getcomposer.org/installer | php", it stops and exit with  this:
"
All settings correct for using Composer
The installation directory "/var/www/cocorico.dev/Symfony" is not writable
"
Of course I tried sudo, chmod on the Symfony directory and whatever else I could think, but this remains the same.
Thx for any help.

**Comment by cocolabssas** [comment]
Hello @LucaAghemo,

You seem to have some permission issues. The user executing your command should have permission to write on your folder. 
So check the permissions of your folder and verify thatthe user executing your composer command has write permission on it.

**Comment by cocolabssas** [comment]
Feel free to open it if needed
