### ISSUE TITLE
Reservation duration calculation

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#167]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi :)

It's normal when we make a reservation of several days, it does a calculation of a few hours? In my example, I made a reservation of 3 days and it indicates me 3 hours?

I do not know if it's normal behavior or I have to change some things in the settings

screen : http://www.turbopix.fr/v/pswuc69jir

Thanks :)

**Comment by gonzasylv** [comment]
How can I modify so that it takes into account the days and not the hours, instead of putting 3 hours, put 3 days ?

**Comment by cocolabssas** [comment]
you have to set `cocorico.time_unit: 1440` here Cocorico/CoreBundle/Resources/config/parameters.yml:64

**Comment by gonzasylv** [comment]
It's perfect :) Thanks
