### ISSUE TITLE
Sending a test email from Cocorico

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#168]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi, I have problems with the E-Mail configuration and didn't find an answer here. My mails are spooled but not send. I am not quite sure if this is a problem with my config or with my server. Therefor I'd like to send a test email from within cocorico. Is there any way to do this? 

Thanks in advance

**Comment by cocolabssas** [comment]
Hi, in dev environment your outgoing mails are stored in app/spool folder and are not send. In other environments your mails are send if you correctly configure your server and your mailer parameters in app/config/parameters.yml:10.

**Comment by cocolabssas** [comment]
Hi,
You can deploy and configure your app on production server without going live and then test mails sending on it. But if you prefer you can also test it on dev by disabling this default behaviour in the section `swiftmailer `in `app/config/config_dev.yml:41`.

**Comment by handmade-it** [comment]
Hi, thanks. That was exactly the necessary information :)

**Comment by gsanchez27** [comment]
@cocolabssas what will be configuration under **app/config/config_dev.yml:41**  on swiftmailer section i have email parameters set in parameters.yml but not receiving the email for password reset
