### ISSUE TITLE
Admin/dashboard

### ISSUE THREAD

**Issue by lnjouguet** [Cocolabs-SAS/cocorico#17]
Hi,

I complete my first attempt to install Cocorico and all seems to work well (browser navigation, login to demandeur/fournisseur account) exept the access to http://[cocorico.dev]/admin/dashboard (page not found in the prod version, no route in the dev version)

Here an excerpt from my logs :
[2016-09-04 19:40:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /admin/dashboard"" at /var/www/cocorico/Symfony/app/cache/prod/classes.php line 2599 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin/dashboard\" at /var/www/cocorico/Symfony/app/cache/prod/classes.php:2599, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/cocorico/Symfony/app/cache/prod/appProdUrlMatcher.php:2214)"} []

I don't understand well the logs and I don't find this path in the folders
Thank for your help, Regards - Hélène

**Comment by SOFRACS** [comment]
I was hoping someone else than the Cocolabs guys would answer this question ;-) 
Have you solved this issue?

**Comment by cocolabssas** [comment]
Bonjour,

Je suis absent du bureau du 05/09/16 au 23/09/2016 compris.

Je n'ai pas accès à ma messagerie pendant cette période. Je prendrai donc connaissance de votre message à mon retour.

En cas d'urgence, vous pouvez contacter Anthoni Noyon.

Arnaud BENATSOU

**Comment by kroshp** [comment]
Bonjour,

Je suis absent du bureau du 05/09/16 au 23/09/2016 compris.

Je n'ai pas accès à ma messagerie pendant cette période. Je prendrai donc connaissance de votre message à mon retour.

En cas d'urgence, vous pouvez contacter Anthoni Noyon.

Arnaud BENATSOU

**Comment by lnjouguet** [comment]
Absolutely not :)
off chance i watched the installation démo : http://demo.cocorico.io/en/admin/dashboard.
No idea if this install should work on this url to access admin pages but openly, this is the same "page not found" wich appears. For example, the url could be managed somewhere in config files ?
...
Thank for your help again - Hélène

**Comment by lnjouguet** [comment]
HI,
I'm always looking for a solution, on your all installs, the admin dashboard is well readable at the url /en/admin/dashboard ?

**Comment by SOFRACS** [comment]
In production you have to change the url of the dashboard (should never be set to /admin/). Does the technical documentation cover this?

**Comment by kroshp** [comment]
Hi,
You just have to set the value of parameter 'cocorico.admin' in 'app/config/parameters.yml'.
You will then be able to access to the admin url by this one: http(s)://yourdomain.tld/[cocorico.admin value]/dashboard.

**Comment by phe-sofracs** [comment]
Bonjour,

Je serais en congés jusqu'au 30/09/2016 inclus. Votre mail sera traité par Benjamin Perrault.

Cordialement,

Henri Phe

**Comment by lnjouguet** [comment]
HI, indeed I have found this option in parameters, I changed it during the install without understanding that this will manage the path to admin...
with many thanks - Hélène
