### ISSUE TITLE
Expiration date question

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#170]
| Q                | A
| ---------------- | -----
| Bug report?      | []
| Feature request? | [ ]
| Support request? | [x ]

hi cocorico,

I have just detected a small mistake regarding a reservation, when it is perform the same day, the expiration date is bad.

http://imgur.com/7uNNdWZl.png

**Comment by cocolabssas** [comment]
Hi gonzasylv,

The booking expire by default 4 hours before it start.

Hope it helps and make you staring the project.

**Comment by gonzasylv** [comment]
Ok thanks :)
