### ISSUE TITLE
URL routing modules in cocorico.

### ISSUE THREAD

**Issue by sarthak-patidar** [Cocolabs-SAS/cocorico#173]
| Q                | A
| ---------------- | -----
| Bug report?      | [No]
| Feature request? | [No]
| Support request? | [Yes]

@cocolabssas In current version of cocorico search feature points to urls like
http://cocorico.dev/en/listing/search_result?categories[]=30&location[address]=India&location[country]=IN&date_range[start]=16%2F05%2F2018&date_range[end]=16%2F05%2F2018

i want to route them to something like
http://cocorico.dev/location/category/date-time-start/date-time-end

For this currently i am considering two routing modules namely

- Symfony's in-built routing module : [symfony/routing](https://packagist.org/packages/symfony/routing)
- Module natively used in cocorico : [jms/i18n-routing-bundle
](https://packagist.org/packages/jms/i18n-routing-bundle)

Could you please suggest which one should i  prefer.

**Comment by cocolabssas** [comment]
Hi @sarthak-patidar,

You can use the i18n jms routing bundle. It only allows to add the routing internationalization to the Symfony routing. 
If you change the `cocorico_listing_search_result` route, don't forget to change it also in `app/Resources/translations/routes.xxx.xliff` files and every where this route name is called.

**Comment by sarthak-patidar** [comment]
Thanks a lot.
Also, @cocolabssas where can i configure method and action attributes of forms in cocorico as i did not got any controller for them?

**Comment by cocolabssas** [comment]
Hi @sarthak-patidar,

You already have controllers for forms implemented in the [Symfony way](https://symfony.com/doc/3.4/form/action_method.html) allowing to add action and method. 

For example for `searchAction` you have in the controller `Cocorico/CoreBundle/Controller/Frontend/ListingSearchController.php:44` the call to the `createSearchResultForm` method creating the form and configuring the method and the action of the form.
```
    protected function createSearchResultForm(ListingSearchRequest $listingSearchRequest)
    {
        $form = $this->get('form.factory')->createNamed(
            '',
            'listing_search_result',
            $listingSearchRequest,
            array(
                'method' => 'GET',
                'action' => $this->generateUrl('cocorico_listing_search_result'),
            )
        );

        return $form;
    }
```

**Comment by sarthak-patidar** [comment]
Thanks that would work.
There's one another thing i am importing listings from a csv file into all concerned tables, and i see that a new listing is converted into form entity and then it is saved into database, is there any way to directly save the listing into database without actually converting it to form. Below is the code of the controller and some other functions which i used to save listing.
`    public function import(Request $request)
    {
        $rowNo = array();
        $collection = array();
        $inserted_id = array();
        $rowNo[0] = 0;
        $i = 0;
        // $fp is file pointer to file listing.csv
        if (($fp = fopen("listing.csv", "r")) !== FALSE) {
            while (($row = fgetcsv($fp, 1000, ",")) !== FALSE) {
                $listingHandler = $this->get('cocorico.form.handler.listing');
                $listing = $listingHandler->init();
//                $form = $this->createCreateForm($listing);
                $success = $listingHandler->processImport($listing);
                $id = $listing->getId();
                $num = count($row);
                $rowNo[$i] = $num;
                $i++;
                array_push($collection,$row);
                if(!$success)
                {
                    break;
                }
                else
                {
                    array_push($inserted_id,$id);
                }
            }
            fclose($fp);
        }

        return $this->render(
            'CocoricoCoreBundle:Frontend/Listing:import.html.twig',
            array(
                'collection' => $collection,
                'insert_id' => $inserted_id,
            )
        );
    }`

`  public function processImport(Listing $listing){
        return $this->importListing($listing);
    }`

`   private function importListing(Listing $listing){
        $this->listingManager->save($listing);
        return true;
    }`
