### ISSUE TITLE
Is google crawling search url when filters are changed

### ISSUE THREAD

**Issue by himanshustar** [Cocolabs-SAS/cocorico#174]
Hi

I want to know whether google can crawl the urls when in a search made by the user when   filters are changed.

For eg: https://artist.live/fr/prestations?categories=3&location%5Baddress%5D=France&location%5Blat%5D=46.227638&location%5Blng%5D=2.213749000000007&location%5Bviewport%5D=%28%2841.3423276%2C+-5.14214190000007%29%2C+%2851.0891658%2C+9.55979339999999%29%29&location%5Bcountry%5D=FR&location%5BaddressType%5D=country%2Cpolitical&page=1

Whenever filters are changed in the search,the url are being changed. So are they being crawled,indexed by google or not

**Comment by himanshustar** [comment]
https://www.sparklogix.com/check-if-a-web-page-has-been-indexed-tool/

Hi I tried this tool for checking whether your filter page is being indexed by google or not
 
for the link : http://demo.cocorico.io/en/listing/search_result?location%5Baddress%5D=hiuhiuh%2C+Italy&location%5Blat%5D=41.87194&location%5Blng%5D=12.567379999999957&location%5Bviewport%5D=%28%2835.4897%2C+6.626720100000057%29%2C+%2847.092%2C+18.797599900000023%29%29&location%5Bcountry%5D=IT&location%5Barea%5D=&location%5Bdepartment%5D=&location%5Bcity%5D=&location%5Bzip%5D=&location%5Broute%5D=&location%5BstreetNumber%5D=&location%5BaddressType%5D=country%2Cpolitical&date_range%5Bstart%5D=&date_range%5Bend%5D=&time_range%5Bstart_picker%5D=&time_range%5Bstart%5D%5Bhour%5D=&time_range%5Bstart%5D%5Bminute%5D=&time_range%5Bnb_minutes%5D=&time_range%5Bend%5D%5Bhour%5D=&time_range%5Bend%5D%5Bminute%5D=&page=1

This is the result:

![untitled](https://user-images.githubusercontent.com/39294718/40125626-fbb7041c-5948-11e8-8364-f13e036fede2.png)


For the link : http://demo.cocorico.io/en/listing/sarthak-373733152/show

It is being indexed by google : 
![untitled-1](https://user-images.githubusercontent.com/39294718/40125773-5aa3f070-5949-11e8-9754-107ab27a2ed8.png)


I tried the same for artist.live

The result is the same

**Comment by cocolabssas** [comment]
Hi,

The search form can possibly generate an "infinity" of urls (date, location, ...). Google should not want to generate so much urls.  

Listings are discovered through home page and then through breadcrumbs links of listings pages.
 
Hope it helps.

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed.
