### ISSUE TITLE
deactivated end of reservation

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#176]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi,

Is it possible to deactivate the end date of a reservation and keep that the date of the beginning of reservation?

Thanks

**Comment by cocolabssas** [comment]
Hi,

Could you precise what you mean by deactivate the end date of reservation?

**Comment by gonzasylv** [comment]
Is it possible to only indicate the departure date and remove the end date here: 

http://imgur.com/9SDFR0Yl.png

**Comment by cocolabssas** [comment]
Yes,
In Cocorico/CoreBundle/Resources/config/parameters.yml:71, 77
Set `cocorico.days_display_mode` parameter value to `duration `and `cocorico.days_max` to `1`.

**Comment by gonzasylv** [comment]
Thanks, it's perfect.
