### ISSUE TITLE
How to create a PDF using wkhtmltopdf?

### ISSUE THREAD

**Issue by rterreroalares** [Cocolabs-SAS/cocorico#177]
| Q                | A
| ---------------- | -----
| Bug report?      | [No ]
| Feature request? | [No]
| Support request? | [Yes]

We have already installed [WkHtml2PDF](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/wkhtml2pdf.md). How can we use it? Perhaps will we need a bundle like [KnpSnappyBundle](https://github.com/KnpLabs/KnpSnappyBundle)?

**Comment by cocolabssas** [comment]
Hi @rterreroalares,

Exactly you should use KnpSnappyBundle.
