### ISSUE TITLE
How to add a field to the listing?

### ISSUE THREAD

**Issue by cypherfunk** [Cocolabs-SAS/cocorico#179]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

Hey 

Is there anything to help me understand how to add another (mandatory) field into the listing?
I have been digging in the code and it is anything but obvious how would one add a field.

Thanks!

**Comment by giorgio654** [comment]
Hello @cypherfunk,

You can read the [Symfony documentation](https://symfony.com/doc/2.8/form/dynamic_form_modification.html) related to this specific dev.
Otherwise, I strongly advise you to get in touch with [Cocolabs](https://www.cocolabs.io/en/contact-us/) for your specific developments.

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
