### ISSUE TITLE
Missing table error

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#180]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x ]
| Feature request? | [ ]
| Support request? | [ ]

hi @cocolabssas 

I have token errors that appear, someone has already solved the problem or knows where it may come from?

> 
> [2018-05-31 19:37:11] request.INFO: Matched route "cocorico_dashboard_booking_asker". {"route_parameters":{"page":1,"_controller":"Cocorico\\CoreBundle\\Controller\\Dashboard\\Asker\\BookingController::indexAction","_locale":"fr","_route":"cocorico_dashboard_booking_asker"},"request_uri":"https://myndd.fr/fr/tableau-de-bord/demandeur/reservation"} []
> [2018-05-31 19:37:11] security.DEBUG: Read existing security token from the session. {"key":"_security_frontend"} []
> [2018-05-31 19:37:11] security.DEBUG: User was reloaded from a user provider. {"username":"myemail@gmail.com","provider":"Cocorico\\UserBundle\\Model\\UserManager"} []
> [2018-05-31 19:37:11] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT t0.id AS id_1, t0.address AS address_2, t0.city AS city_3, t0.zip AS zip_4, t0.country AS country_5, t0.createdAt AS createdAt_6, t0.updatedAt AS updatedAt_7, t0.booking_id AS booking_id_8 FROM `booking_user_address` t0 WHERE t0.booking_id = ?' with params [1785164823]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB.booking_user_address' doesn't exist") in "@CocoricoCore/Dashboard/Booking/_booking_index.html.twig" at line 3." at /var/www/dev/cocorico/app/cache/prod/classes.php line 5442 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"An exception occurred while executing 'SELECT t0.id AS id_1, t0.address AS address_2, t0.city AS city_3, t0.zip AS zip_4, t0.country AS country_5, t0.createdAt AS createdAt_6, t0.updatedAt AS updatedAt_7, t0.booking_id AS booking_id_8 FROM `booking_user_address` t0 WHERE t0.booking_id = ?' with params [1785164823]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB.booking_user_address' doesn't exist\") in \"@CocoricoCore/Dashboard/Booking/_booking_index.html.twig\" at line 3. at /var/www/dev/cocorico/app/cache/prod/classes.php:5442, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.address AS address_2, t0.city AS city_3, t0.zip AS zip_4, t0.country AS country_5, t0.createdAt AS createdAt_6, t0.updatedAt AS updatedAt_7, t0.booking_id AS booking_id_8 FROM `booking_user_address` t0 WHERE t0.booking_id = ?' with params [1785164823]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB.booking_user_address' doesn't exist at /var/www/dev/cocorico/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB.booking_user_address' doesn't exist at /var/www/dev/cocorico/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB.booking_user_address' doesn't exist at /var/www/dev/cocorico/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
>

**Comment by gonzasylv** [comment]
It is necessary to reset the database to solve this problem.

> chmod 744 bin/init-mongodb
> ./bin/init-mongodb php --env=prod

If someone has another solution, I wait a little before closing the issue.

Have fun :)

**Comment by cocolabssas** [comment]
Hi @gonzasylv,

It seems you did not have booking_user_address table. 
In case you need to update your database structure, instead of resetting database, you can just execute the following command:
`
#dry run:
php app/console doctrine:schema:update --dump-sql --env=dev
#Then
php app/console doctrine:schema:update --force --env=dev
`

**Comment by gonzasylv** [comment]
Ok thanks @cocolabssas
