### ISSUE TITLE
Listing Characterstics and type management

### ISSUE THREAD

**Issue by sarthak-patidar** [Cocolabs-SAS/cocorico#182]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [Y]

Hey @giorgio654, your latest commit regarding listing characterstics and management is very helpful to me, but i do not find any way a to associate any listing characterstic and its value to a listing, so my question is are you working on a way to do so or should i write a code on my own and then give a pull request.

**Comment by cocolabssas** [comment]
Hi @sarthak-patidar,

You can associate listing characteristics and its value to a listing in the dashboard listing characteristics edition page.

![dashboard_listing_edit_characteristic](https://user-images.githubusercontent.com/18029169/41438151-abdfbe6c-7026-11e8-9802-753abb82b316.png)

**Comment by cocolabssas** [comment]
If you want to associate them from admin we will be happy to merge your PR.
Feel free to reopen this issue if needed.

Thanks
