### ISSUE TITLE
Change payment processing

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#184]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Hi, for a custom project I'd like to change the payment from an hour-based calculation to an day-based (rent of technical equipment). Is this any where configurable or changeable in the code?

And I'd like to offer special rates for weekends? Where do I have to look / change the code to define own rules how the total payment amount is calculated?

Many thanks in advance

**Comment by handmade-it** [comment]
Hi, I found one part of my answer hidden in the docs. For every one searching this too, see the documentation in /doc/times.md

But my question concerning the calculation is still relevant. Any hints?

**Comment by cocolabssas** [comment]
Hi,

To pass to hour mode to day mode you have to change time_unit parameter in CoreBundle from 60 to 1440. 

The price calculation is made into `\Cocorico\CoreBundle\Model\Manager\BookingManager::checkBookingAvailabilityAndSetAmounts` method.

But offerer can choose to have different prices for week end or any other days in his dashboard listing calendar edition.
