### ISSUE TITLE
Remove annual revenue from settings

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#186]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi ,

I removed the html data from the twig on `src/Cocorico/UserBundle/Resources/views/Dashboard/Profile/edit_bank_account.html.twig`

```
                            <div class="field-row price-field">
                                {{ form_errors(form.annualIncome) }}
                                <span class="label">{{ form_label(form.annualIncome) }}</span>

                                {{ form_widget(form.annualIncome,{
                                    'attr': {
                                        'class': "numbers-only form-control"
                                    }
                                } ) }}
                            </div>
```
but the field still stays in the page off the form : http://imgur.com/ouchsnUl.png 

Thanks !

**Comment by cocolabssas** [comment]
Hi,

You have to remove it also from this FormType : `Cocorico/UserBundle/Form/Type/ProfileBankAccountFormType.php:75`

**Comment by gonzasylv** [comment]
It's perfect, thanks
