### ISSUE TITLE
Remove the "Characteristic" button and the information message

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#187]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

I'm going in `Cocorico/CoreBundle/Entity/Listing.php:549` to delete the information message to set a feature and at the same time remove the "Characteristic" button .

I deleted : 

```
       $characteristic = 0;
        foreach ($this->getListingListingCharacteristics() as $characteristics) {
            if ($characteristics->getListingCharacteristicValue()) {
                $characteristic = 1;
            }
        }](url)
```
I deleted, but I had no change.

Thanks :)

**Comment by cocolabssas** [comment]
Hi,

could you precise what you mean by 

> to delete the information message to set a feature
> Remove the "Characteristic" button 

with a screenshot for example

**Comment by gonzasylv** [comment]
hi @cocolabssas ,

Since I do not inform any characteristics, I would like to remove the button features located on the left buttons and the information sentence to inform the characteristics : 

http://www.turbopix.fr/v/hsdksscx3m

Thanks :)

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

It's pretty simple : 
- for the menu go to Cocorico/CoreBundle/Resources/views/Dashboard/Listing/_nav_side.html.twig:44
- and for the notification  got to Cocorico/CoreBundle/Resources/views/Dashboard/Listing/_completion_notice.html.twig:37

**Comment by gonzasylv** [comment]
Thanks, it's perfecte @cocolabssas
