### ISSUE TITLE
Unnecessary markup whithin HEAD - META

### ISSUE THREAD

**Issue by mapet68** [Cocolabs-SAS/cocorico#189]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x]

On all the public pages, there is an unnecessary markup, like this; 
<title>home.meta_title - Cocorico</title>
Instead of: <title>Cocorico</title>
Also visible on the demo: http://demo.cocorico.io/en/

and here:
<title>listing.show.meta_title Vasya Events - Petah Tikva - 20 €/hour - Cocorico</title>
http://demo.cocorico.io/en/listing/vasya-events-1534823736/show

By the way: where do I edit the META for the front page?

Regards,
Mapet

**Comment by cocolabssas** [comment]
Hi,

This is not an unnecessary markup. This is the translation key of the meta not already translated. 
You just have to go to the` admin > translation` menu or into `app/Resources/translations`  folder and choose the `cocorico_meta` domain to translate these metas.

**Comment by mapet68** [comment]
Right. Thank you!
