### ISSUE TITLE
Frontend assets issues

### ISSUE THREAD

**Issue by ruizcrp** [Cocolabs-SAS/cocorico#19]
Hello,
I just installed it the first time. Everything has been made according to the guide. The database and the dev-env seems to be working as I can log in via browser to the admin dashboard or register in as a user. But isn't the frontend supposed to look like here http://demo.cocorico.io/en/ ? I actually see everything as simple HTML without any design at all. Also publishing a new listening does not work that way. Sorry, but what am I doing wrong? 
PHP 5.6
Apache 2.4
mongodb 2.6
Kind regards

**Comment by YousssF** [comment]
Hello,

It seems that css and js files are missing. If you take those from demo.cocorico.io, it looks better. Now I don't know why those files are not in the package.

**Comment by cocolabssas** [comment]
Hello,

The css and the js are in in the web folder. I suppose you miss to dump the assets as explained at the end of the README.md :

`php app/console assets:install --symlink web --env=dev`
`php app/console assetic:dump --env=dev`

If this doesn't work, please send more infos like browser console log, ...

**Comment by YousssF** [comment]
Hello,

Thank you, it's working for me. Indeed, I've read the tuto "en diagonale".

Merci !

**Comment by ruizcrp** [comment]
Hello,
thanks for the answers. Yes, I executed the two dump commands as you stated above already several times. The first dump command ends with "[OK] All assets were successfully installed." and the second dump command adds many files [file+] and ends without any error. 

The browser console log of the Symfony Profiler gives the following issues.

- 3 Infos and Errors:

Level 	Channel 	Message
INFO 12:39:04 	request 	Matched route "cocorico_home". Context: { "route_parameters": {"_controller": "Cocorico\\CoreBundle\\Controller\\Frontend\\HomeController::indexAction", "_locale": "en", "_route": "cocorico_home" },"request_uri": "http://localhost:8000/en/" }
INFO 12:39:04 	security 	Populated the TokenStorage with an anonymous Token.
WARNING 12:39:07 	translation 	Translation not found. Context: { "id": "Enter a location", "domain": "cocorico_listing", "locale": "en" } 


- 33 Deprecations:
Time 	Channel 	Message
12:39:04 	php 	The Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.
12:39:04 	php 	The Symfony\Component\Form\Extension\Core\ChoiceList\SimpleChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.
12:39:04 	php 	The possibility to register the same extension twice ("Text") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead.
12:39:04 	php 	The "security.context" service is deprecated since Symfony 2.6 and will be removed in 3.0.
12:39:04 	php 	The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead.
12:39:04 	php 	The Twig_Function_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.
12:39:04 	php 	The Twig_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.
12:39:04 	php 	Using an instance of "Twig_Function_Method" for function "fos_message_is_read" is deprecated since version 1.21. Use Twig_SimpleFunction instead.
12:39:04 	php 	Using an instance of "Twig_Function_Method" for function "fos_message_nb_unread" is deprecated since version 1.21. Use Twig_SimpleFunction instead.
12:39:04 	php 	Using an instance of "Twig_Function_Method" for function "fos_message_can_delete_thread" is deprecated since version 1.21. Use Twig_SimpleFunction instead.
12:39:04 	php 	Using an instance of "Twig_Function_Method" for function "fos_message_deleted_by_participant" is deprecated since version 1.21. Use Twig_SimpleFunction instead.
12:39:04 	php 	Returning a type name from Sonata\AdminBundle\Form\Extension\Field\Type\FormTypeFieldExtension::getExtendedType() is deprecated since version 2.8 and will be removed in 3.0. Return the fully-qualified type class name instead.
12:39:04 	php 	Accessing type "listing_search_home" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Cocorico\CoreBundle\Form\Type\Frontend\ListingSearchHomeType" instead.
12:39:04 	php 	Sonata\AdminBundle\Form\Extension\Field\Type\FormTypeFieldExtension: The FormTypeExtensionInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeExtensionInterface with Symfony 3.0. (2 times)
12:39:04 	php 	Sonata\AdminBundle\Form\Extension\Field\Type\MopaCompatibilityTypeFieldExtension: The FormTypeExtensionInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeExtensionInterface with Symfony 3.0.
12:39:05 	php 	Passing type instances to FormBuilder::add(), Form::add() or the FormFactory is deprecated since version 2.8 and will not be supported in 3.0. Use the fully-qualified type class name instead (Cocorico\CoreBundle\Form\Type\Frontend\ListingLocationSearchType).
12:39:05 	php 	Accessing type "entity" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Bridge\Doctrine\Form\Type\EntityType" instead.
12:39:05 	php 	Accessing type "listing_category" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Cocorico\CoreBundle\Form\Type\ListingCategoryType" instead.
12:39:05 	php 	The form option "empty_value" of the "choice" form type (Symfony\Component\Form\Extension\Core\Type\ChoiceType) is deprecated since version 2.6 and will be removed in 3.0. Use "placeholder" instead.
12:39:05 	php 	Accessing type "hidden" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\HiddenType" instead. (12 times)
12:39:05 	php 	Accessing type "search" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\SearchType" instead.

- Debug 136:
Time 	Channel 	Message
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Lexik\Bundle\CurrencyBundle\EventListener\LocaleListener::setCurrencyFormatterLocale".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Cocorico\CoreBundle\Listener\UserTypeCookieListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "SimpleThings\EntityAudit\Request\CurrentUserListener::handle".
12:39:04 	event 	Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Lexik\Bundle\CurrencyBundle\EventListener\LocaleListener::setCurrencyFormatterLocale".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Cocorico\CoreBundle\Listener\UserTypeCookieListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "SimpleThings\EntityAudit\Request\CurrentUserListener::handle".
12:39:04 	event 	Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
12:39:04 	event 	Notified event "kernel.response" to listener "JMS\I18nRoutingBundle\EventListener\CookieSettingListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Sonata\BlockBundle\Cache\HttpCacheHandler::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SaveSessionListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse".
12:39:04 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".
12:39:04 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelFinishRequest".
12:39:04 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".
12:39:04 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\Security\Http\Firewall::onKernelFinishRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Lexik\Bundle\CurrencyBundle\EventListener\LocaleListener::setCurrencyFormatterLocale".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Cocorico\CoreBundle\Listener\UserTypeCookieListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest".
12:39:04 	event 	Notified event "kernel.request" to listener "SimpleThings\EntityAudit\Request\CurrentUserListener::handle".
12:39:04 	event 	Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
12:39:04 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
12:39:05 	doctrine 	SELECT l0_.id AS id_0, l0_.lft AS lft_1, l0_.lvl AS lvl_2, l0_.rgt AS rgt_3, l0_.root AS root_4, l1_.name AS name_5, l1_.locale AS locale_6, l1_.id AS id_7, l1_.slug AS slug_8, l0_.parent_id AS parent_id_9, l1_.translatable_id AS translatable_id_10 FROM listing_category l0_ LEFT JOIN listing_category_translation l1_ ON l0_.id = l1_.translatable_id WHERE l1_.locale = ? AND l0_.id IN (?) ORDER BY l0_.root ASC, l0_.lft ASC Context: ["en",[]]
12:39:05 	doctrine 	SELECT l0_.id AS id_0, l0_.lft AS lft_1, l0_.lvl AS lvl_2, l0_.rgt AS rgt_3, l0_.root AS root_4, l1_.name AS name_5, l1_.locale AS locale_6, l1_.id AS id_7, l1_.slug AS slug_8, l0_.parent_id AS parent_id_9, l1_.translatable_id AS translatable_id_10 FROM listing_category l0_ LEFT JOIN listing_category_translation l1_ ON l0_.id = l1_.translatable_id WHERE l1_.locale = ? ORDER BY l0_.root ASC, l0_.lft ASC Context: ["en"]
12:39:08 	event 	Notified event "kernel.response" to listener "JMS\I18nRoutingBundle\EventListener\CookieSettingListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Sonata\BlockBundle\Cache\HttpCacheHandler::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SaveSessionListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\Security\Http\Firewall::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Lexik\Bundle\CurrencyBundle\EventListener\LocaleListener::setCurrencyFormatterLocale".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Cocorico\CoreBundle\Listener\UserTypeCookieListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest".
12:39:08 	event 	Notified event "kernel.request" to listener "SimpleThings\EntityAudit\Request\CurrentUserListener::handle".
12:39:08 	event 	Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
12:39:08 	event 	Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
12:39:08 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
12:39:08 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
12:39:08 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
12:39:08 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
12:39:08 	event 	Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
12:39:08 	doctrine 	SELECT l0_.id AS id_0, l0_.status AS status_1, l0_.type AS type_2, l0_.price AS price_3, l0_.certified AS certified_4, l0_.min_duration AS min_duration_5, l0_.max_duration AS max_duration_6, l0_.cancellation_policy AS cancellation_policy_7, l0_.average_rating AS average_rating_8, l0_.comment_count AS comment_count_9, l0_.admin_notation AS admin_notation_10, l0_.availabilities_updated_at AS availabilities_updated_at_11, l0_.createdAt AS createdAt_12, l0_.updatedAt AS updatedAt_13, l1_.title AS title_14, l1_.description AS description_15, l1_.rules AS rules_16, l1_.locale AS locale_17, l1_.id AS id_18, l1_.slug AS slug_19, l2_.id AS id_20, l2_.name AS name_21, l2_.position AS position_22, l3_.id AS id_23, l3_.country AS country_24, l3_.city AS city_25, l3_.zip AS zip_26, l3_.route AS route_27, l3_.street_number AS street_number_28, u4_.username AS username_29, u4_.username_canonical AS username_canonical_30, u4_.email AS email_31, u4_.email_canonical AS email_canonical_32, u4_.enabled AS enabled_33, u4_.salt AS salt_34, u4_.password AS password_35, u4_.last_login AS last_login_36, u4_.locked AS locked_37, u4_.expired AS expired_38, u4_.expires_at AS expires_at_39, u4_.confirmation_token AS confirmation_token_40, u4_.password_requested_at AS password_requested_at_41, u4_.roles AS roles_42, u4_.credentials_expired AS credentials_expired_43, u4_.credentials_expire_at AS credentials_expire_at_44, u4_.id AS id_45, u4_.last_name AS last_name_46, u4_.first_name AS first_name_47, u4_.phone_prefix AS phone_prefix_48, u4_.phone AS phone_49, u4_.birthday AS birthday_50, u4_.nationality AS nationality_51, u4_.country_of_residence AS country_of_residence_52, u4_.profession AS profession_53, u4_.iban AS iban_54, u4_.bic AS bic_55, u4_.bank_owner_name AS bank_owner_name_56, u4_.bank_owner_address AS bank_owner_address_57, u4_.annual_income AS annual_income_58, u4_.phone_verified AS phone_verified_59, u4_.email_verified AS email_verified_60, u4_.id_card_verified AS id_card_verified_61, u4_.has_booking AS has_booking_62, u4_.fee_as_asker AS fee_as_asker_63, u4_.fee_as_offerer AS fee_as_offerer_64, u4_.average_rating_as_asker AS average_rating_as_asker_65, u4_.average_rating_as_offerer AS average_rating_as_offerer_66, u4_.mother_tongue AS mother_tongue_67, u4_.answer_delay AS answer_delay_68, u4_.createdAt AS createdAt_69, u4_.updatedAt AS updatedAt_70, u4_.slug AS slug_71, u5_.description AS description_72, u5_.locale AS locale_73, u5_.id AS id_74, u6_.id AS id_75, u6_.facebook_id AS facebook_id_76, u6_.link AS link_77, u6_.last_name AS last_name_78, u6_.first_name AS first_name_79, u6_.birthday AS birthday_80, u6_.address AS address_81, u6_.verified AS verified_82, u6_.location AS location_83, u6_.location_id AS location_id_84, u6_.hometown AS hometown_85, u6_.hometown_id AS hometown_id_86, u6_.gender AS gender_87, u6_.locale AS locale_88, u6_.timezone AS timezone_89, u6_.nb_friends AS nb_friends_90, u6_.picture AS picture_91, u6_.createdAt AS createdAt_92, u6_.updatedAt AS updatedAt_93, l7_.id AS id_94, l7_.lft AS lft_95, l7_.lvl AS lvl_96, l7_.rgt AS rgt_97, l7_.root AS root_98, l8_.name AS name_99, l8_.locale AS locale_100, l8_.id AS id_101, l8_.slug AS slug_102, l0_.user_id AS user_id_103, l0_.location_id AS location_id_104, l1_.translatable_id AS translatable_id_105, l2_.listing_id AS listing_id_106, l3_.listing_id AS listing_id_107, l3_.coordinate_id AS coordinate_id_108, u5_.translatable_id AS translatable_id_109, u6_.user_id AS user_id_110, l7_.parent_id AS parent_id_111, l8_.translatable_id AS translatable_id_112 FROM listing l0_ LEFT JOIN listing_translation l1_ ON l0_.id = l1_.translatable_id LEFT JOIN listing_image l2_ ON l0_.id = l2_.listing_id LEFT JOIN listing_location l3_ ON l0_.location_id = l3_.id LEFT JOIN `user` u4_ ON l0_.user_id = u4_.id LEFT JOIN user_translation u5_ ON u4_.id = u5_.translatable_id LEFT JOIN `user_facebook` u6_ ON u4_.id = u6_.user_id LEFT JOIN listing_listing_category l9_ ON l0_.id = l9_.listing_id LEFT JOIN listing_category l7_ ON l7_.id = l9_.listing_category_id LEFT JOIN listing_category_translation l8_ ON l7_.id = l8_.translatable_id WHERE l0_.status = ? AND l1_.locale = ? AND l8_.locale = ? GROUP BY l0_.id ORDER BY l0_.createdAt DESC, l2_.position asc LIMIT 6 Context: [2,"en", "en"]
12:39:08 	doctrine 	SELECT t0.code AS code_1, t0.rate AS rate_2, t0.id AS id_3 FROM lexik_currency t0
12:39:08 	doctrine 	SELECT t0.id AS id_1, t0.name AS name_2, t0.position AS position_3, t0.user_id AS user_id_4 FROM user_image t0 WHERE t0.user_id = ? ORDER BY t0.position ASC Context: [1374921718]
12:39:08 	event 	Notified event "kernel.response" to listener "JMS\I18nRoutingBundle\EventListener\CookieSettingListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Sonata\BlockBundle\Cache\HttpCacheHandler::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SaveSessionListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\Security\Http\Firewall::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.response" to listener "JMS\I18nRoutingBundle\EventListener\CookieSettingListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Sonata\BlockBundle\Cache\HttpCacheHandler::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SaveSessionListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".
12:39:08 	event 	Notified event "kernel.finish_request" to listener "Symfony\Component\Security\Http\Firewall::onKernelFinishRequest".

**Comment by cocolabssas** [comment]
@ruizcrp i didn't see any error on the logs, only depreciation which should not break anything.
But i see that you are working on port 8000. I think this is the origin of your problem.
I suggest you to work on port 80 by creating an entry on your hosts file (ex: 127.0.0.2 mysite.dev ) and to modify your vhost and you app/config/parameters.yml accordingly.
If you absolutely want to work on port 8000 i suggest you for now to search on the web how to work with Symfony and assets on specific port.

**Comment by ruizcrp** [comment]
Thank you for your help. I found out what it was!!! in the app/config/parameters.yml file the options
cocorico.assets_base_urls: 'http://cocorico.local'
and
router.request_context.scheme: http
were previously set to https while I had the virtualhost set to http.
Oh my, it took ages to find it. Hopefully this is of help to others out there :)
Woohoo its running!
Kind regards!

**Comment by cocolabssas** [comment]
Great :)
