### ISSUE TITLE
Manual deployment

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#191]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Hi. I try to deploy our dev to a prod system. Unfortunatelly your documentation is very short on what to exactly has to be done. What does the command "php app/console project:deploy prod" does perform in detail and what is necessary for this step. Please elaborate this because currently I have only the change to walk from error to error of this script without knowing if thats right or not. 

Another Option might be if there is any way of "manual" deployment by perform important steps by oneself. Is this possible.

**Comment by cocolabssas** [comment]
Hi @handmade-it 

You can have a look to the DeployBundle documentation:  https://github.com/hpatoio/DeployBundle .

You can also have a look at the Symfony deployment documentation 
https://symfony.com/doc/2.8/deployment.html where you will find others solutions.

Hope it helps

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
