### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#192]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

Is it possible to integrate the rating on the ads in the homepage?

Screen : http://imgur.com/RRIoWLrl.png

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

Of course you can. Analyse the code related to  stars on the listing page for example and adapt it for your need.

**Comment by gonzasylv** [comment]
hi @cocolabssas ,

Can we have the page and the code to export?

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

Look at this : src/Cocorico/CoreBundle/Resources/views/Frontend/ListingResult/result.html.twig:143

**Comment by gonzasylv** [comment]
Ok thanks :)
