### ISSUE TITLE
Setting separate spaces for askers and offerers

### ISSUE THREAD

**Issue by vinflip** [Cocolabs-SAS/cocorico#195]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

How do I set separate spaces for askers and offerers. The documentation says that we there is a parameter for this. I cannot find it.

**Comment by cocolabssas** [comment]
Hi @vinflip 

Not sure to understand your need. Could you give the link of the doc?
