### ISSUE TITLE
Geolocalisation 

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#196]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

What change can be made in geolocation to target a country like France for example in the suggestions?

Capture : https://i.imgur.com/YZquh8bl.png

I want to locate only the addresses of France and not of the whole world.

Thanks :))

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

It is not yet implemented but you can make us a pull request with the following change:

In file `src/Cocorico/GeoBundle/Resources/views/Common/js/_geocoding_js.html.twig` add the following  code:

- line 37 add:

`var countriesEnabled = {{ cocorico_listing_location_countries|json_encode|raw }};`

- line 102 add:

```
if (countriesEnabled.length) {
    autoComplete.setComponentRestrictions(
        {'country': countriesEnabled}
    );
}
```

Don't forget to make a Pull Request :)

Thanks

**Comment by gonzasylv** [comment]
hi @cocolabssas ,

When I make this change here is the error obtained in console:
﻿

> weddingyourself.fr/:691 Uncaught TypeError: Cannot read property 'length' of null
>     at HTMLDocument.<anonymous> (weddingyourself.fr/:691)
>     at j (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at Function.ready (jquery.min.js:2)
>     at HTMLDocument.J (jquery.min.js:2)

Thank you for the investment and help brought :)

**Comment by gonzasylv** [comment]
hi @cocolabssas ,

I restart the issue :)

**Comment by gonzasylv** [comment]
hi @cocolabssas ,

sorry to raise the issue but there is a way to answer it, because I literally block with geolocation and price :/

**Comment by gonzasylv** [comment]
hi , 

I can not make a pull request of a code that is not functional, so I hack to my sauce for it to work.

cocorico_listing_location_countries is nowhere.

it lacks a piece of code so that the code provided by @cocolabssas  is functional

Here is my solution for those who are interested:

```
        autoComplete.setComponentRestrictions(
          {'country': ['fr'] }
        );
```

**Comment by cocolabssas** [comment]
Hi everybody,

Sorry for this late answer. I forgot one line in a file. Here is the correct PR to make:

In file `src/Cocorico/CoreBundle/Resources/config/config.yml` add the following  code:
- line 38 add:
`cocorico_listing_countries: "%cocorico.listing_countries%"`

In file `src/Cocorico/GeoBundle/Resources/views/Common/js/_geocoding_js.html.twig` add the following  code:
- line 37 add:
`var countriesEnabled = {{ cocorico_listing_countries|json_encode|raw }};`

- line 93  add:
```
if (countriesEnabled.length) {
    autoComplete.setComponentRestrictions(
        {'country': countriesEnabled}
    );
}
```

Thanks!

**Comment by gonzasylv** [comment]
hi,

It's good, it works now but it creates an error when adding a photo in the form of adding an ad

https://www.irccloud.com/pastebin/BSpwHNpH/

**Comment by gonzasylv** [comment]
re @cocolabssas ,

Here is the error : http://imgur.com/yH76DBEl.png , he appears in the addition of an ad.

On the index, it works properly.

**Comment by gonzasylv** [comment]
You have to put the condition inside the : 

`if (autoCompleteElt) {`

Code set:

```
            if (autoCompleteElt) {
                autoComplete = new google.maps.places.Autocomplete(
                    autoCompleteElt,
                    {types: ['geocode']}
                );

                if (countriesEnabled.length) {
                autoComplete.setComponentRestrictions(
                {'country': countriesEnabled}
                );
              }
            }
```
I'm going to make a pull request.
