### ISSUE TITLE
Problem with ORM geocoding_js.html.twig

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#199]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x]

Hello, 

I've been searching the internet for hours and trying several things like emptying cache but I cannot find the problem I am on PHP7.1.17 could someone tell me where is my problem?

When I login it gives a 500 error and in app/logs I have this : 
equest.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unrecognized field: type") in "@CocoricoCore/Frontend/ListingResult/js/_geocoding_js.html.twig" at line 20." at /var/www/mysite.com/Symfony/app/cache/prod/classes.php line 5442 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unrecognized field: type\") in \"@CocoricoCore/Frontend/ListingResult/js/_geocoding_js.html.twig\" at line 20. at /var/www/mysite.com/Symfony/app/cache/prod/classes.php:5442, Doctrine\\ORM\\ORMException(code: 0): Unrecognized field: type at /var/www/mysite.com/Symfony/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:101)"} []
[2018-09-03 13:06:27] security.DEBUG: Stored the security token in the session. {"key":"_security_frontend"} []

Thank you

**Comment by cocolabssas** [comment]
Hello,

Could you look at "@CocoricoCore/Frontend/ListingResult/js/_geocoding_js.html.twig" line 20 it seems that an unexisting field "type" has been added. 
FYI: This field "type" does not exist in Cocorico : https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Resources/views/Frontend/ListingResult/js/_geocoding_js.html.twig#L20

**Comment by fakelefteye** [comment]
Thank you it was because i tried to merge  with the newest version and i missed some files now i have another problem
