### ISSUE TITLE
installation solution en local

### ISSUE THREAD

**Issue by elmata5** [Cocolabs-SAS/cocorico#20]
Bonjour,
J'essaie d'installer votre solution opensource mais rencontre un souci avec la dll imagick alors que celle-ci se trouve bien dans mon répertoire en local (je suis sous wampserver en PHP 5.6.19)
Cordialement,

Hi,
I try to install your opensource solution but I encounter an issue with the imagick.dll while this one is well located in my local folder. (I use wampserver with the PHP 5.6.19 version)
Regards,

**Comment by cocolabssas** [comment]
Hello,

I suppose you are on Windows. So the simplest solution is to use "GD" instead "Imagick" by installing "GD" and setting parameter `cocorico.image_driver: gd` in `app/config/parameters.yml`.

**Comment by elmata5** [comment]
Thanks for having reply but it doesn't work :\

Same error... :(

**Comment by eshelf** [comment]
After strugling to make imagick to work, I just followed Cocolabs suggestion. Easier than I thought.
