### ISSUE TITLE
Persistent storage: help wanted

### ISSUE THREAD

**Issue by nvirin** [Cocolabs-SAS/cocorico#201]
| Q                | A
| ---------------- | -----
| Bug report?      | [ NO]
| Feature request? | [NO ]
| Support request? | [ YES]

Hello,

What/where are datas writen from client to my server? 

/app/cache
/app/logs
/web/media
/web/uploads
others?

Thank you :)

N.B. 
I use PAAS like dokku (similar to heroku).
With this kind of deplyment you need to configure the persistent storage
(https://www.quora.com/What-is-persistent-storage)

**Comment by nvirin** [comment]
I use PAAS like dokku (similar to heroku). 
With this kind of deplyment you need to configure the persistent storage
(https://www.quora.com/What-is-persistent-storage)

**Comment by nvirin** [comment]
There is others place where data has to write from the website to the "code":
/app/cache
/app/logs
/web/media
/web/uploads
others?

When the offerer uploads some photos. Where the photos are stocks? what happen?
Could you help me please?

Thank you

**Comment by cocolabssas** [comment]
Hello,

- app/Resources/translations can be updated from admin
- mongodb and sql database
