### ISSUE TITLE
Error invalid locale after extracting transalations

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#203]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x ]

Hello,

After updating some files from the updated original repo to mine, 

I changed the title of the home page to make it translatable . 

Then I extracted the translations php app/console translation:extract en --config=cocorico php app/console cache:clear --env=prod 
but I have this message  [InvalidArgumentException]     
  Invalid "cache:clear" locale

And my site isnt available : 503 service unavailable

In the parameters.yml   #For knp translatable
    locale: en

    cocorico.locale: en
    cocorico.locales:
            - en
            - fr
            - es

Do you know what it could be? config.yml is the same as original....

Thank you

**Comment by cocolabssas** [comment]
Hello,

You have to execute your commands one after the other:
`php app/console translation:extract en --config=cocorico`
then
`php app/console cache:clear --env=prod`

Or in one line:
`php app/console translation:extract en --config=cocorico && php app/console cache:clear --env=prod`

**Comment by fakelefteye** [comment]
Thank you, yes this is what I was thinking i copied and pasted the command
so maybe i ran the whole command unintentionally...
