### ISSUE TITLE
Is there a way to sell items

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#204]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [x ]
| Support request? | [ ]

Is there an option to make it a selling items website without the per day and calendar option? 
Such as real estate?
Thanks

**Comment by cocolabssas** [comment]
Hi @fakelefteye 

There is no simple option to do that. You need to implement it.
