### ISSUE TITLE
Error editing a user account

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#206]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x ]
| Feature request? | [ ]
| Support request? | [ ]

hi @cocolabssas ,

There is an error when you want to edit a user account in the admin panel:

> [2018-09-24 16:24:07] request.INFO: Matched route "admin_cocorico_user_user_edit". {"route_parameters":{"_controller":"Cocorico\\UserBundle\\Controller\\Admin\\UserAdminController::editAction","_sonata_admin":"sonata.user.admin.user","_sonata_name":"admin_cocorico_user_user_edit","id":"273039121","_route":"admin_cocorico_user_user_edit","_locale":"fr"},"request_uri":"https://weddingyourself.fr/admin/user/273039121/edit"} []
> [2018-09-24 16:24:07] security.DEBUG: Read existing security token from the session. {"key":"_security_admin"} []
> [2018-09-24 16:24:07] security.DEBUG: User was reloaded from a user provider. {"username":"super-admin@cocorico.rocks","provider":"Cocorico\\UserBundle\\Model\\UserManager"} []
> [2018-09-24 16:24:07] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Please define a type for field `companyName` in `Cocorico\UserBundle\Admin\UserAdmin`" at /var/www/prod/vendor/sonata-project/doctrine-orm-admin-bundle/Builder/FormContractor.php line 56 {"exception":"[object] (RuntimeException(code: 0): Please define a type for field `companyName` in `Cocorico\\UserBundle\\Admin\\UserAdmin` at /var/www/prod/vendor/sonata-project/doctrine-orm-admin-bundle/Builder/FormContractor.php:56)"} []

**Comment by cocolabssas** [comment]
Hi  @gonzasylv 

I suppose that you missed to update your schema with the following command :

`php  app/console doctrine:schema:update --force --env=xxx`

**Comment by gonzasylv** [comment]
I always have the same mistake, it's since I made the last update with the legal form and the name of the company

**Comment by gonzasylv** [comment]
hi @cocolabssas ,

Replace "null" with "text" so that it can work : 

https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/UserBundle/Admin/UserAdmin.php#L82
