### ISSUE TITLE
Listings not working with new language

### ISSUE THREAD

**Issue by kostek895** [Cocolabs-SAS/cocorico#207]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi @cocolabssas ,

Listings and categories on my page aren't working after adding new language. I have empty space on homepage, and when I'm trying go directly, I have Error 500.

The same problem when I'm adding new currency.

How can I fix it?

**Comment by cocolabssas** [comment]
Hi @kostek895,

Have you executed `php app/console translation:extract xx --config=cocorico`  by replacing xx by your new language code?

Furthermore you need to update your fixtures by translating some texts to your new language:
See for example `src/Cocorico/CoreBundle/DataFixtures/ORM/5_LoadListingData.php:113`

$listing->translate('xx')->setTitle('Listing one translated');
...
$listing->translate('xx')->setDescription('Listing One Description translated');

For currency see if your new currency is in the following list: [http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml](http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml)

And don't forget to clear your cache after theses changes.

**Comment by kostek895** [comment]
When I'm trying execute translation:extract I receive this message:
`[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "translaton" namespace.
  Did you mean this?
      translation`

___________
My new currency is in the following list... ("PLN")

**Comment by cocolabssas** [comment]
These problems don't exist on Cocorico. It seems to be specific to your environment.

Could you send the complete command you execute for translations extraction?

For currency could you execute this command : `php app/console cocorico:currency:update` and send the result.
