### ISSUE TITLE
[Solved] Cocorico installation problem

### ISSUE THREAD

**Issue by giovannix** [Cocolabs-SAS/cocorico#21]
Hello. I'm trying to install Cocorico. When I need to run the command 'php composer.phar install', I receive a message indicating some requirements could not be resolved (please, see the attached image).

![cocorico-problem-1](https://cloud.githubusercontent.com/assets/4057864/22036246/fc1bc9e8-dcd9-11e6-8c70-4cf9ffa2c877.png)

How to resolve this problem?

Best regards,

Giovanni.

**Comment by giovannix** [comment]
The problem was in the configuration of mongodb extension.

**Comment by cocolabssas** [comment]
Indeed as the doc explained it mongo have to be activated in php.ini.
