### ISSUE TITLE
Editing css files

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#210]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

I did not really understand how to correctly modify the css files, in the documentation, I did not find the best way to do it, currently I modify the compiled files directly, and I do not think it's the best way .

Thanks

**Comment by cocolabssas** [comment]
Hi gonzasylv,

Indeed this is not right place to modify css. 
I suggest you to
- create a new css file (my.css) in web/css folder, 
- call it in https://github.com/Cocolabs-SAS/cocorico/blob/master/app/Resources/views/base.html.twig#L39
- dump your assets `php app/console assetic:dump --env=xxx`

**Comment by elhayadi** [comment]
Si php app/console assetic:dump --env=xxx ne fonctionne pas essayez avec :
php bin/console assetic:dump --env=xxx
