### ISSUE TITLE
Error adding city level ad

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#211]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x ]
| Feature request? | [ ]
| Support request? | [ ]

hi @cocolabssas ,

There is an error at the country level and there is already a pre-configure address in the geolocation fields : 

http://imgur.com/Ru4PvLSl.png

We can not select any country, the list is empty.

**Comment by cocolabssas** [comment]
Your problem seems to be caused by a countries misconfiguration:
Look at this lines and check that available countries are correctly setted : https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Resources/config/parameters.yml#L110
