### ISSUE TITLE
Selection of a category in the index

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#212]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x ]
| Feature request? | [ ]
| Support request? | [ ]

hi @cocolabssas ,

When you click on the category list button on the home page, there is no longer the list of categories that has been displayed since the update

test page : https://dev.weddingyourself.fr

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

Your problem is caused by this missing style :

```
.form-category .area {
    overflow: visible;
}
```

But more globally it seems related to a css file you removed or missed to call : all-override.css.
