### ISSUE TITLE
Mixed content : https is missing for images

### ISSUE THREAD

**Issue by Damiano1376** [Cocolabs-SAS/cocorico#214]
Hello,

I have a problem with https : 
Mixed Content: The page at 'https://www.mydomain.com/fr/' was loaded over HTTPS, but requested an insecure image 'http://www.mydomain.com/media/cache/listing_large/uploads/listings/images/default-listing.png'. This content should also be served over HTTPS.

I have already set https in parameters.yml, what should I do to fix this?

| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [yes]

**Comment by doydoy44** [comment]
I had the same problem and and in my case I solved it with the Reverse Proxy:
https://symfony.com/doc/2.8/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly

**Comment by cocolabssas** [comment]
Hi Damiano1376,

If you set cocorico.assets_base_urls parameter with 'https://www.mydomain.com/fr/' value and router.request_context.scheme to https it should work.
As @doydoy44  say your problem seems more a server misconfiguration than an application one.
This post seems to confirm that also : https://github.com/liip/LiipImagineBundle/issues/727

**Comment by Damiano1376** [comment]
I think you're right, there is a problem with my nginx-proxy. I use docker for cocorico and nginx , does anyone knows how to manage correctly https configuration in this two containers?

**Comment by Damiano1376** [comment]
Hello cocorico team,
I think i am on  the way, but i still need help.

I  think my error come from LiipImagineBundle because everything is in https excepted images in cache.
I  thound this post : 
https://github.com/liip/LiipImagineBundle/issues/1050

Considering the second solution, il should add a line in security.yml 

`security:
    access_control:
        - { path: ^/your/custom/cache/path, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/media/cache/resolve, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }`
What are the right paths for  cocorico?

**Comment by cocolabssas** [comment]
Hello @Damiano1376 ,

Great news :)
It should be `^/media/cache/`
Look into the web/media folder and the urls of the images you have in your browser.

**Comment by nmuntyanov** [comment]
@Damiano1376 
This is a solution https://github.com/liip/LiipImagineBundle/pull/1059 
But I don't know when guys will accept it
