### ISSUE TITLE
Cocorico Installation Issue

### ISSUE THREAD

**Issue by faraimupfuti** [Cocolabs-SAS/cocorico#215]
I am having difficulty in installing Cocorico locally on my computer using Wamp. I created a database on phpmyadmin and even adjusted the parameters database connection settings, and still it wont go through.

Where am i going wrong ?

**Comment by cocolabssas** [comment]
Hello,

Could you give more informations like (errors displayed, ...)

**Comment by faraimupfuti** [comment]
> Hello,
> 
> Could you give more informations like (errors displayed, ...)



 Hie. The error that is popping on the browser is : 


**Not Found
The requested URL /cocorico/config.php was not found on this server.

Apache/2.4.27 (Win64) Server at localhost Port 80**

Additional information:
1. i had installed composer
2. double checked the parameters file [ app/config/parameters.yml.dist ] to check to see if the database connections are correct...and its correct
3. Do i need to RENAME **parameters.yml.dist** TO **parameters.yml**  ????


Where do you think i might have made a mistake ??

**Comment by cocolabssas** [comment]
Hello,

You don't need to copy manually parameters.yml.dist.
I suggest you to follow all the installation details of the following documentations:

- https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-server-windows.md
- https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md

You can find these links in the table of contents here:
https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/index.md

Hope it helps

**Comment by EmmaTheGr8est** [comment]
hey @cocolabssas  please i tried using the docker version after running the commands and opening my browser i just see a scattered webpage

**Comment by EmmaTheGr8est** [comment]
@cocolabssas please i need your help asap thanks
