### ISSUE TITLE
Section "high rank" doesnt scroll on mobileversion

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#217]
| Q                | A
| ---------------- | -----
| Bug report?      | [x ]
| Feature request? | [ ]
| Support request? | [ ]

Hello,

On the mobile version of the site it is not possible to scroll horizontally the "high rank" section with the finger...
I have to click on the dots which is not user friendly...

Thanks

**Comment by cocolabssas** [comment]
Hello  @fakelefteye ,

Thanks for this feedback. We added it to the todo list.
