### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by giovannix** [Cocolabs-SAS/cocorico#22]
Hello.

Accessing http://cocorico.dev, I see the list of files present at /var/www/cocorico.dev/Symfony/web.

Accessing http://cocorico.dev/config.php, I see the message "This script is only accessible from localhost".

What is wrong?

Thanks,

Giovanni.

**Comment by cocolabssas** [comment]
Hello,

I think you miss again a part of the documentation : https://github.com/Cocolabs-SAS/cocorico#configure-project

**Comment by giovannix** [comment]
I had already copied the .htaccess.dist to .htaccess according to the documentation.

**Comment by giovannix** [comment]
Is it possible be a problem related to VirtualHost configuration?

**Comment by cocolabssas** [comment]
Does your VirtualHost configuration accept .htaccess and doesn't override the cocorico one?

**Comment by cocolabssas** [comment]
Could you check your DirectoryIndex directive. It should be `app_dev.php`.
Concerning the config.php change the 127.0.0.1 at line 18 by your server IP.

**Comment by giovannix** [comment]
Thank you! Now I have one cocorico instance working!
