### ISSUE TITLE
Issue with FaceBook login and user type being null

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#224]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x]
| Feature request? | [ ]
| Support request? | [ ]

Hello,

When a user registers with facebook button the type of user ( company or individual) cannot be entered.

So when the newly registered user wants to publish an add he is being stopped by a message saying "this value can't be null" and of course cannot edit it.

So the quick workaround could be to allow a Null value for this field, or to add a field with the facebook login button...

thank you

**Comment by fakelefteye** [comment]
![image](https://user-images.githubusercontent.com/5584130/47603579-32a63f80-d9ee-11e8-9cb2-b59fbe6fc63b.png)

**Comment by fakelefteye** [comment]
To solve what i did was to update the table user in sql  when status is null for the previous users set it to 1 and then it worked even for newly created user with Facebook.

**Comment by cocolabssas** [comment]
Hi @fakelefteye,

Indeed the problems only occurred for existing users. For new users there is no issue.

By the way i send you a little patch to fix facebook issues due to the recent Facebook policy and API  change.
We would be glad that you do a Pull request of this patch [facebook-api-change-fix.zip](https://github.com/Cocolabs-SAS/cocorico/files/2535883/facebook-api-change-fix.zip)

After applying this path you will need to execute : 
`php app/console doctrine:schema:update --force`

Thanks!

**Comment by fakelefteye** [comment]
hmm sorry I don't know how to apply a patch I will google it though and neitheir do a pull request , I've changed my files so if I do a pull request will it modify your version?

**Comment by fakelefteye** [comment]
Hello, I would like to make this pull, just a question shall I put my forked cocorico as upstream or origin ?
I would like to be able to sychronize your updates easily but I always have troubles with git.
Also I have made checkboxes for newsletter sign up using sendy so if I pull you will have my sendy credentials in your repo isn't it?

**Comment by cocolabssas** [comment]
Hello,

You have to work on two separate repositories:
- your own with your custom functionalities which you sync with cocorico as upstream
About how to sync your fork look at here: https://help.github.com/articles/syncing-a-fork/ 

- and an another one used only to make PR on Cocorico  
This tutorial describe clearly how to make a PR on a github repository : https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

Hope it helps

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
