### ISSUE TITLE
Pricing method (option 3)

### ISSUE THREAD

**Issue by bpitka** [Cocolabs-SAS/cocorico#225]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ X]
| Support request? | [ ]

Hello,
I read in the documentation that the pricing method 3 in order to have a price for a determined duration was an extension.

How is it possible to activate it ?

Thank you for your help.

**Comment by cocolabssas** [comment]
Hello @bpitka,

I think you read the documentation of EE. This method 3 is not yet in the CE. You should maybe contact [Cocolabs](https://www.cocolabs.io) if you need more information about this feature.

Thanks!
