### ISSUE TITLE
Avoid translating some words

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#227]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x ]

Hello,

I asked on stackoverflow but I'd like not to translate certain brand for eg : "North Dice" 

So I found that I should o this : 
Syntax:

<mstrans:dictionary translation=”translation of phrase”>phrase</mstrans:dictionary>

Example: en-de:

Source input: The word <mstrans:dictionary translation="wordomatic">word or phrase</mstrans:dictionary> is a dictionary entry.

[](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/dynamic-dictionary)

But where ? I tried to put some files in their translation sysmtem without success

Is there a Json file in cocorico where to add this? I try to find it ...

Also Azure is in V3 now. V2 is deprecated.

Thank you

**Comment by fakelefteye** [comment]
I found this in order to do it : 
https://cognitive.uservoice.com/knowledgebase/articles/1166938-hub-building-a-custom-system-using-a-dictionary-o

it take several days to deploy so I'll let you know if it doesn't work

**Comment by cocolabssas** [comment]
Hi,

The MS Azure translation functionality in Cocorico is implemented here : \Cocorico\CoreBundle\Model\Manager\TranslateManager::getTranslation

If MS azure allow to not translate some words you should look there.
