### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by giovannix** [Cocolabs-SAS/cocorico#23]
Hello.

How to provide internationalization in cocorico? Should I create .xliff files for each language or this is can be made automatically using Microsoft Translator API?

Thanks,

Giovanni.

**Comment by cocolabssas** [comment]
Hello,

There are two type of translations:

1. Static texts: ex : the link "Connexion" in top nav.

Static texts translations are stored in xliff and can be translated manually or through a web interface available through the "Translation" link in admin:

For languages setting have a look at `Cocorico/CoreBundle/Resources/config/parameters.yml.`
You will see the languages "en" and "fr" activated by default in the parameters `cocorico.locales` and `cocorico.locales_string`. 
If you change them by adding for example the italian language , you can learn how to extract new languages translations by following  this part of the documentation: `Cocorico/CoreBundle/Resources/doc/index.rst` > `Extract translations` section.

For example to extract all translations in a new italian language execute:

`php app/console translation:extract it --config=cocorico `

All translations are stored in `app/Resources/translations`.

2. Dynamic texts : ex: listing title and description

Dynamic texts translations are stored in database and translated through Microsoft Translator API.

**Comment by giovannix** [comment]
Thanks for your reply.

How to set it when I have different countries using the same language? For example, pt for Portugal and Brazil.

Best regards,

Giovanni.

**Comment by ClemSche** [comment]
Bonjour,

Je suis en congés du 09/02/17 au 20/02/17 inclus. N’hésitez pas à contacter contacter Anthoni Noyon sur anthoni.noyon@cocolabs.io pour tout renseignement.

Hello,

I will be absent from 09/02/17 to 20/02/17. If you have any questions during my absence please contact Anthoni Noyon on anthoni.noyon@cocolabs.io. 

Clément Schereck
Cocolabs

**Comment by edilsonsp** [comment]
Hello friends, someone was able to translate to Portugues Brasil pt-BR.

I did the translation by "admin / __ translations /"

But I have some errors:

Maps does not appear when I choose the Portuguese language.

=================================================
\src\Cocorico\CoreBundle\Resources\config\parameters.yml

  #Languages
    #For knp translatable
    locale: en

    cocorico.locale: en
    cocorico.locales:
            - en
            - pt-br 
    cocorico.locales_string: en|pt-br
    #Currencies
    cocorico.currency: USD
    cocorico.currencies_for_lexik:
        - BRL
        - USD
        - GBP
        - CHF
        - CAD
        - JPY
        - RUB
        - AUD
    cocorico.currencies:
        BRL: R$
        USD: $
        GBP: £
        CHF: CHF
        CAD: $ CAD
        JPY: ¥
        RUB: руб
        AUD: $ AUD
    cocorico.currencies_string: BRL|USD|GBP|CHF|CAD|JPY|RUB|RUB|AUD
    cocorico.currencies_json: %kernel.root_dir%/../web/json/currencies.json
=================================================

**Comment by giovannix** [comment]
I have the same problem. I've tried pt and pt_BR, but all texts appear only in English, not in Portuguese.

**Comment by cocolabssas** [comment]
When you add a new locale you have to extract new translations keys by executing the following command: 
`php app/console translation:extract pt_BR --config=cocorico`.
Then you will be able to translate them either directly in xliff files located in app/Resources/translations or through https://yourdomain.com/admin/__translations/

**Comment by giovannix** [comment]
Hello.

I've executed the command to extract the pt translation. When I translate the text via http://domain/app_dev.php/admin/__tanslations, all changes are made in xliff files. In this case, everything is working well.

However, accessing http://domain/app_dev.php/pt, the site is displayed in English.

The translations made in categories through http://domain/app_dev.php/admin/listing-category are working well too, i.e, categories are correctly displayed in Portuguese. 

It seems the problem is related with the texts stored in xliff files.

**Comment by edilsonsp** [comment]
Hi Giovannix execute this command em (SSH)

sudo su
rm -rf /var/www/html/cocorico/app/cache/*

**Comment by giovannix** [comment]
Thanks, edisonsp.

I took a look in the app/console and saw the option cache:clear. The following command worked as well:

php app/console cache:clear --env=dev
