### ISSUE TITLE
Password database 

### ISSUE THREAD

**Issue by FredSWR** [Cocolabs-SAS/cocorico#230]
Hi, 

We configure talend to retrieve the Mariadb data but we don't know the password of the database.
This is blocking us in the setting of Talend because we need it.

Can you give us the password please ?

Thanks in advance.

Bye !

**Comment by cocolabssas** [comment]
Hi,

We do not choose your DB password, you choose it while installation of cocorico at the end of `php composer.phar install` command. At this step you will have to set your DB account informations.
These values will be then set in app/config/parameters.yml.dist:6.

Hope it hepls
