### ISSUE TITLE
Not supported with php 7.2

### ISSUE THREAD

**Issue by Pratiklocho** [Cocolabs-SAS/cocorico#234]
| Q                | A
| ---------------- | -----
| Bug report?      | [ Y ]
| Feature request? | [ Y ]
| Support request? | [ N ]

there is some of thing in this project that not supported by PHP 7.2 and give warning  some is listed below 

> count(): Parameter must be an array or an object that implements Countable

> Warning: get_class() expects parameter 1 to be object, null given

for last error i found solution 
wrap all the get_class($variable); with 
`
if(is_object($variable)){
    get_class($variable);
} 
`

but first one i didn't get any solution

**Comment by giorgio654** [comment]
Hello @Pratiklocho,
Cocorico isn't compatible with this PHP version yet.
You can downgrade temporary to avoid issue.

**Comment by Pratiklocho** [comment]
Hello @giorgio654 
you have any idea when it's supported php 7.2

**Comment by cocolabssas** [comment]
Hello @Pratiklocho 

It should be in the second quarter 2019.

**Comment by Pratiklocho** [comment]
OK thanks @cocolabssas
