### ISSUE TITLE
Minimum amount

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#240]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

What is the variable to edit to set the minimum amount of an ad?

http://imgur.com/rBy2EL0l.png

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

You are not asking for the minimum amount of a listing (ad) but for a booking.
Here are the parameter : 
`cocorico.booking_price_min: 500`
You will find it here : `src/Cocorico/CoreBundle/Resources/config/parameters.yml:147`

**Comment by gonzasylv** [comment]
Thanks.

**Comment by gonzasylv** [comment]
thanks @cocolabssas ,

it is currently possible not to set a minimum price?

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

For now it is not possible.

**Comment by gonzasylv** [comment]
Ok thanks :)
