### ISSUE TITLE
price converter

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#241]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

there is an option in the config to disable the converter?

http://imgur.com/pjV17cLl.png

**Comment by cocolabssas** [comment]
Hi,

Yes you only need to comment or remove  this corresponding  twig part `src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/new.html.twig:133`

**Comment by gonzasylv** [comment]
Thanks.
