### ISSUE TITLE
Contact infos

### ISSUE THREAD

**Issue by ElwardFletcher** [Cocolabs-SAS/cocorico#242]
| Q                | A
| ---------------- | -----
| Bug report?      | [  ]
| Feature request? | [  ]
| Support request? | [X ]

Hi everyone,

Is there anyway I can take out the upper bar with email and phone contact, as well as Contact infos at the bottom bar? For now I'd like contact to be exclusively via form.

Been looking in the code, but only found out where to change those infos and leaving the space black or with "null" doesn't take out the icons.

Thanks so much

**Comment by cocolabssas** [comment]
Hi @ElwardFletcher,

It is very simple, you just need to remove the corresponding parts in header and footer twig template : 

-  `src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_header.html.twig:17`
- `src/Cocorico/CoreBundle/Resources/views/Frontend/Common/_footer.html.twig:22`

**Comment by ElwardFletcher** [comment]
Perfect, thank you so much for your help
