### ISSUE TITLE
Forced to certify listing 

### ISSUE THREAD

**Issue by JonathanVandal** [Cocolabs-SAS/cocorico#246]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi,

I want to know how to automatically certify a listing or remove this constraint.
For the moment when I publish a listing and if I want to consult it, I got an error 404. 
So I have to go to the admin dashboard then certify the listing. And after it works.

So how can I do ? I watched the configuration and I see new_is_published is true.

```
cocorico_listing:
    new_is_published: true
```
I tried to set this property to false but there are no changes.

I see in Cocorico\ListingBundle\Repository\ListingRepository.php : 

```
    public function getFindOneBySlugQuery($slug, $locale, $joined = true) {
        $slugParts = explode('-', $slug);
        $listingId = end($slugParts);

        $queryBuilder = $this->createQueryBuilder('l')
            ->addSelect("t")
            ->leftJoin('l.translations', 't')
            ->where('l.id = :listingId')
            ->andWhere('t.locale = :locale')
            ->setParameter('listingId', $listingId)
            ->setParameter('locale', $locale)
            ->andWhere('l.certified = :certified')
            ->setParameter('certified', true);
        if ($joined) {
            $queryBuilder
                ->addSelect("u, i")
                ->leftJoin('l.user', 'u')
                ->leftJoin('u.images', 'i');
        }

        return $queryBuilder;
    }
```

So I removed this condition : 

```
            ->andWhere('l.certified = :certified')
            ->setParameter('certified', true);
```

It is ok ? Or there is a config for that ?

**Comment by cocolabssas** [comment]
Hi @JonathanVandal 

You found the correct solution :)
This file src/Cocorico/ListingBundle/Repository/ListingRepository.php  containing this specific condition 
```
->andWhere('l.certified = :certified')
->setParameter('certified', true);
```
is an example on how to override the Listing repository. 
And the override consists to only find certified listing. 
So indeed you can completely ignore it by removing the corresponding condition.

About the configuration :

```
cocorico_listing:
    new_is_published: true
```

this make a listing automatically published by default after listing deposit.
If false the listing have to be published by the administrator in the administration of the platform after deposit.  

PS:
To have some info on configurations of a bundle you can do for example :

`php bin/console config:dump-reference cocorico_listing`

which return 

```
# Default configuration for extension with alias: "cocorico_listing"
cocorico_listing:

    # This value defines whether a new listing is published by default
    new_is_published:     ~

    # This value sets the minimum price of a listing
    price_min:            ~

    # This value sets the maximum price of a listing
    price_max:            ~

    # This value defines whether the offerer can duplicate a listing
    duplication:       
```   ~

Hope it helps

**Comment by JonathanVandal** [comment]
Thank you to confirm and for the other tips
