### ISSUE TITLE
connection with facebook

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#249]
| Q                | A
| ---------------- | -----
| Bug report?      | [ X ]
| Feature request? | [ ]
| Support request? | [  ]

hi @cocolabssas ,

Since today, I have an error when I want to identify with facebook, do you have the same error? or does it come from home?

http://imgur.com/D2FFqnYl.png

**Comment by gonzasylv** [comment]
Finally it works all alone..

**Comment by cocolabssas** [comment]
:+1:
