### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by giovannix** [Cocolabs-SAS/cocorico#25]
Hello.

How to configure Cocorico/CoreBundle/Resources/config/parameters.yml when I have different countries using the same language? For example, pt for Portugal and Brazil.

Best regards,

Giovanni.

**Comment by cocolabssas** [comment]
The following setting should work:

In `src/Cocorico/CoreBundle/Resources/config/parameters.yml`:

cocorico.locales:
            - pt
            - pt_BR

cocorico.locales_string: pt|pt_BR

**Comment by giovannix** [comment]
Thanks.

**Comment by xpeering** [comment]
Hi Giovannix!
Do you know if installing code source of cocorico project on my server can  I have access to ADMIN dashboard?
Thanks!

**Comment by giovannix** [comment]
Hi xpeering.

You can have access to admin dashboard through http://yourdomain/admin/dashboard (without language prefix).

**Comment by cocolabssas** [comment]
I close the issue as it seems to be resolved.
