### ISSUE TITLE
Docker container built from the cocorico-docker git does not launch properly

### ISSUE THREAD

**Issue by ht512512** [Cocolabs-SAS/cocorico#250]
Hello,
Docker container built from the cocorico-docker git does not seem to launch properly. Please help, Thank you.

Platform = Ubuntu 18.04

Cloned the git repo

Did "Docker build" to build the container successfully

Did "Docker run" as describe in the the Readme.md here (uses mysql and mongodb in the container). Failed. It tried the Cocorico script 5 times with error exit; after which it gave up. The logtail showed the error of mysql "Connection refused"

I changed the parameter to point to mysql on another server I have and rebuilt the container. Of course, created cocorico db and user on the mysql server.

Ran the new container. This time mysql connection was established without any error and container seemed to have launched without any errors.

Tried to access the app at http://localhost/en and got an exception because of a bad query. I have included the exception below. BTW, looking at the mysql server, all the tables were created properly.

Any help about how to proceed in making my local container work will be very valuable. I rather use docker than do a host installation. Thank you.

Hemant

======== Exception =================
An exception occurred while executing 'SELECT DISTINCT id_1 FROM (SELECT '' AS sclr_0, l0_.id AS id_1, l0_.price AS price_2, l0_.certified AS certified_3, l0_.average_rating AS average_rating_4, l0_.createdAt AS createdAt_5, l1_.title AS title_6, l1_.description AS description_7, l1_.slug AS slug_8, l1_.locale AS locale_9, l1_.id AS id_10, l2_.id AS id_11, l3_.id AS id_12, l3_.lft AS lft_13, l3_.lvl AS lvl_14, l3_.rgt AS rgt_15, l3_.root AS root_16, l4_.name AS name_17, l4_.locale AS locale_18, l4_.id AS id_19, l5_.id AS id_20, l5_.name AS name_21, u6_.id AS id_22, u6_.first_name AS first_name_23, u7_.id AS id_24, u7_.name AS name_25, l8_.id AS id_26, l8_.country AS country_27, l8_.city AS city_28, l8_.route AS route_29, g9_.id AS id_30, g9_.lat AS lat_31, g9_.lng AS lng_32, l4_.locale AS locale_33, u7_.position AS position_34, l1_.locale AS locale_35, l0_.status AS status_36, l0_.createdAt AS createdAt_37 FROM listing l0_ LEFT JOIN listing_translation l1_ ON l0_.id = l1_.translatable_id LEFT JOIN listing_listing_category l2_ ON l0_.id = l2_.listing_id LEFT JOIN listing_category l3_ ON l2_.listing_category_id = l3_.id LEFT JOIN listing_category_translation l4_ ON l3_.id = l4_.translatable_id AND (l4_.locale = ?) LEFT JOIN listing_image l5_ ON l0_.id = l5_.listing_id LEFT JOIN user u6_ ON l0_.user_id = u6_.id LEFT JOIN user_image u7_ ON u6_.id = u7_.user_id AND (u7_.position = 1) LEFT JOIN listing_location l8_ ON l0_.location_id = l8_.id LEFT JOIN geo_coordinate g9_ ON l8_.coordinate_id = g9_.id WHERE l1_.locale = ? AND l0_.status = ? ORDER BY l5_.position asc, u7_.position asc) dctrn_result ORDER BY createdAt_5 DESC LIMIT 6' with params ["en", "en", 2]:

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.createdAt_5' which is not in SELECT list; this is incompatible with DISTINCT

**Comment by ht512512** [comment]
> Hello @ht512512
> 
> It seems to be related to this issue #124.

Thank you for the pointer. After dropping "ONLY_FULL_GROUP_BY" from sql-mode, I was able to bring up the App home page, however, clicking on login link gave me the following exception. Am I missing something? Any additional configuration required before using the container? Thanks.

    in src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php at line 50  -
            public function vote(TokenInterface $token, $booking, array $attributes)
            {
                // check if class of this object is supported by this voter
                if (!$this->supportsClass(get_class($booking))) {
                    return VoterInterface::ACCESS_ABSTAIN;
                }
    at ErrorHandler ->handleError ('2', 'get_class() expects parameter 1 to be object, null given', '/cocorico/src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php', '50', array('token' => object(AnonymousToken), 'booking' => null, 'attributes' => array('IS_AUTHENTICATED_FULLY')))
    at get_class (null)
    in src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php at line 50  +
    at ReviewVoter ->vote (object(AnonymousToken), null, array('IS_AUTHENTICATED_FULLY'))
    in app/cache/dev/classes.php at line 2870  +
    at AccessDecisionManager ->decideUnanimous (object(AnonymousToken), array('IS_AUTHENTICATED_FULLY'), null)
    in app/cache/dev/classes.php at line 2797  +
    at AccessDecisionManager ->decide (object(AnonymousToken), array('IS_AUTHENTICATED_FULLY'), null)
    in app/cache/dev/classes.php at line 2925  +
    at AuthorizationChecker ->isGranted (array('IS_AUTHENTICATED_FULLY'))
    in src/Cocorico/UserBundle/Controller/Frontend/SecurityController.php at line 39  +
    at SecurityController ->loginAction ()
    at call_user_func_array (array(object(SecurityController), 'loginAction'), array())
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 139  +
    at HttpKernel ->handleRaw (object(Request), '1')
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 62  +
    at HttpKernel ->handle (object(Request), '1', true)
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69  +
    at ContainerAwareHttpKernel ->handle (object(Request), '1', true)
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185  +
    at Kernel ->handle (object(Request))
    in web/app_dev.php at line 30  +
    at require ('/cocorico/web/app_dev.php')
    in vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php at line 40  +

**Comment by cocolabssas** [comment]
Hello @ht512512 

This error make me think that you are using php 7.2 but as you can see in the installation documentation  Cocorico require php 7.1.

php 7.2 compatibility is in our road map and will be done at the latest in the second quarter 2019.

**Comment by ht512512** [comment]
@cocolabssas 
Thank you. The Dockerfile definition by default pulled down php 7.2. After changing it to php 7.1 it worked fine.

**Comment by spdaly** [comment]
@cocolabssas How can I get the Docker image to use 7.1?

**Comment by gsanchez27** [comment]
@ht512512 how to change the dockerfile to use php 7.1?
