### ISSUE TITLE
"The translation file (...)  is not writable."

### ISSUE THREAD

**Issue by ElwardFletcher** [Cocolabs-SAS/cocorico#256]
| Q                | A
| ---------------- | -----
| Bug report?      | [  ]
| Feature request? | [  ]
| Support request? | [ X]

Hi @cocolabssas 
I have a small question regarding translations. I have new languages installed, yet when accessing via admin/__translations/, I'm not able to translate them and I have the following message:
"The translation file (...)  is not writable."

Curious that the original ones (EN and FR) I'm able to translate without any problem.

Thanks for your help

**Comment by cocolabssas** [comment]
Hi @ElwardFletcher 

Could you check if the translations files for your new languages exists in the app/Resources/translations folder. 
If no you have to extract them with the command  `php app/console translation:extract [xx] --config=cocorico` and then clear your cache.
If the files exists check theirs permissions.
You can read the corresponding  documentation [here](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/translations.md).

**Comment by cocolabssas** [comment]
Hi @ElwardFletcher 

If you are on linux : `ls -alh`
