### ISSUE TITLE
I cant add / publish a listing please help

### ISSUE THREAD

**Issue by birkirivarb** [Cocolabs-SAS/cocorico#257]
I cant add / publish a listing. when i press the publish your listing button on https://cocorico.dev/en/listing/new

Nothing happens its just stuck in loading.

What is causing this problem?

btw im on windows using xampp the website works 100% except this

**Comment by cocolabssas** [comment]
Hello @birkirivarb,

Could you look at your Javascript console and see if there any errors.

**Comment by birkirivarb** [comment]
new:2367 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
XMLHttpRequest.open @ new:2367
send @ jquery.min.js:4
ajax @ jquery.min.js:4
getTranslations @ new:2156
(anonymous) @ new:2140
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
2jquery.min.js:4 POST https://rentanduse.test/is/language/translate 500 (Internal Server Error)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
getTranslations @ new:2156
(anonymous) @ new:2140
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
new:2367 Refused to get unsafe header "X-Debug-Token"
(anonymous) @ new:2367
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
m.(anonymous function) @ jquery.min.js:4
getJSON @ jquery.min.js:4
(anonymous) @ new:1198
each @ jquery.min.js:2
translateGeoLocations @ new:1194
(anonymous) @ new:1088
(anonymous) @ geocoder.js:4
(anonymous) @ geocoder.js:2
SP @ geocoder.js:2
d @ geocoder.js:2
c @ common.js:52
(anonymous) @ VM832 GeocodeService.Search:1
new:2367 Refused to get unsafe header "X-Debug-Token-Link"
(anonymous) @ new:2367
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
m.(anonymous function) @ jquery.min.js:4
getJSON @ jquery.min.js:4
(anonymous) @ new:1198
each @ jquery.min.js:2
translateGeoLocations @ new:1194
(anonymous) @ new:1088
(anonymous) @ geocoder.js:4
(anonymous) @ geocoder.js:2
SP @ geocoder.js:2
d @ geocoder.js:2
c @ common.js:52
(anonymous) @ VM832 GeocodeService.Search:1

**Comment by birkirivarb** [comment]
this is the error i get its basicly 4 errors. 1 yellow decapriated error and 3 x debug errors

the x debug errors show up when i load the page. the yellow decapriated error pops up when i try to upload and its a javascript code. but im not the best in java so i dont know what is causing this

**Comment by igorcherry** [comment]
Hello
I have the same problem on CentOS hosted on Google Cloud. When I press Publihs ...  It looks like proccessing publishing, but it's never finish and no new Listings appears in Admin Console - Listings
![image](https://user-images.githubusercontent.com/35894283/50086616-eb724900-01fd-11e9-934e-72249766ca69.png)

**Comment by cocolabssas** [comment]
Hello,

Indeed there is a problem since Google has changed his price and conditions. 
We need two things to making work:
- Fix the issue on our side. (Will be done in some hours).
- You will need to add your bank details in your Google account. You will have 200$ free monthly usage which should be enough to support the needs of most users.

- The google service installation guide : https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/services-creation.md#create-your-google-api-account

- The Google pricing details : https://cloud.google.com/maps-platform/pricing/?hl=en

**Comment by cocolabssas** [comment]
Hello,

As promised this issue is now fixed: fdda3876699633caa70b95cb2a3ddbc9298d4611

Enjoy!
