### ISSUE TITLE
ADMIN Access

### ISSUE THREAD

**Issue by xpeering** [Cocolabs-SAS/cocorico#26]
Hi!
I´m new to cocorico marketplace and I like to know the ADMIN-Dashboard installed at demo:
http://demo.cocorico.io/en/

I´m trying to access without success...

some attemps:
http://demo.cocorico.io/admin/dashboard
Message: "Page not found"

http://demo.cocorico.io/en/admin/dashboard
Message: "Page not found"

Like informed here at "Browsing the Demo Application":
http://cocorico.dev/admin/dashboard
super-admin@cocorico.rocks
super-admin

Message: "Can not access this site"

Somebody can send me:
admin-dashboard url;
user name;
password

to cocorico demo access?
Thanks in advance!

**Comment by giovannix** [comment]
Hi xpeering.

I think that cocorico demo admin dashboard is not available.

**Comment by cocolabssas** [comment]
Hi,

Indeed the admin of demo.cocorico.io is not publicly accessible. It is of course available if you install cocorico.

**Comment by xpeering** [comment]
Ok Understood
Thanks!
