### ISSUE TITLE
install Cocorico with MySQL ?

### ISSUE THREAD

**Issue by baryaz** [Cocolabs-SAS/cocorico#264]
Bonjour 

comment je peux installer Cocorico avec un base MySQL ?

J'arrive pas à l'instaler avec mongoDB j'ai ces erreurs :

  Problem 1
    - Installation request for alcaeus/mongo-php-adapter 1.1.3 -> satisfiable by alcaeus/mongo-php-a
dapter[1.1.3].
    - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
  Problem 2
    - Installation request for mongodb/mongodb 1.2.0 -> satisfiable by mongodb/mongodb[1.2.0].
    - mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb is missing from your system.

et quand je tente d'installer mongo adapter j'ai cessi comme erreur ::

VirtualAlloc() failed: [0x00000008] Espace insuffisant pour traiter cette commande.

VirtualFree() failed: [0x000001e7] Tentative d'accès à une adresse non valide.

VirtualAlloc() failed: [0x00000008] Espace insuffisant pour traiter cette commande.

VirtualFree() failed: [0x000001e7] Tentative d'accès à une adresse non valide.

Fatal error: Out of memory (allocated 1465909248) (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220

Cordialement.

**Comment by cocolabssas** [comment]
Hello,

It seems that you missed to install the **mongodb** (not the mongo) php extension as describe here : https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-server-linux.md#install-php-mongodb-driver
