### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by baryaz** [Cocolabs-SAS/cocorico#268]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [* ]

i have this error 

**Erreur 500 Internal Server Error**

in the home page and other page like comment and paiment

and http://cocorico.local/app_dev.php

CRITICAL - Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "Warning: mkdir(): Permission denied in /var/www/cocorico.local/Symfony/src/Cocorico/CoreBundle/Resources/config/. (which is being imported from "/var/www/cocorico.local/Symfony/src/Cocorico/CoreBundle/Resources/config/routing.yml")." at /var/www/cocorico.local/Symfony/app/cache/dev/classes.php line 14665

**Comment by cocolabssas** [comment]
Hello,

Check the permissions of your document root folder and make sure that you have specified the same  directory owner  than the web server one.

First make sure of which user is your web user.
In apache it can be www-data. You can change it if you want.

For the permissions, do this (replace www-data if needed):

```
chown -R www-data:www-data /var/www/cocorico.local/
find /var/www/cocorico.local/Symfony -type d -exec chmod 755 "{}" \;
find /var/www/cocorico.local/Symfony-type f -exec chmod 644 "{}" \;
```

**Comment by baryaz** [comment]
thank you for you response i did that and i get another exception and a critical error:
 **Warning: get_class() expects parameter 1 to be object, null given**
_500 Internal Server Error - ContextErrorException_ 

**Logs**

25. CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: get_class() expects parameter 1 to be object, null given" at /var/www/hajj.advisor/Symfony/src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php line 50

**Comment by cocolabssas** [comment]
You seem to use  php 7.2 instead 7.1. Downgrade PHP to 7.1 and the problem should be resolved.
