### ISSUE TITLE
Cocorico Symfony 4

### ISSUE THREAD

**Issue by baryaz** [Cocolabs-SAS/cocorico#269]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

how do I upgrad cocorico to be builded in Symfony 4 core not Symfony 2 ?

thanks.

**Comment by cocolabssas** [comment]
Hello,

You can't. For now you will be able to upgrade to Symfony 3.4 in the second quarter 2019. We plan to upgrade to Symfony 4 in the last Quarter of 2019 when the Symfony 4 LTS will be released.
