### ISSUE TITLE
CRITICAL - Uncaught PHP Exception ... at ... ReviewVoter.php line 50

### ISSUE THREAD

**Issue by baryaz** [Cocolabs-SAS/cocorico#270]
any solution for this error pleaz ?
thanks in advance.
it appears when i try to login /app_dev.php/en/login
 Warning: get_class() expects parameter 1 to be object, null given
500 Internal Server Error - ContextErrorException 
...
...
Logs:
 CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: get_class() expects parameter 1 to be object, null given" at /var/www/cocorico.local/Symfony/src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php line 50

**Comment by business-hall** [comment]
See https://github.com/Cocolabs-SAS/cocorico/issues/151#issuecomment-450525828
See https://github.com/Cocolabs-SAS/cocorico/issues/234#issuecomment-442056206
