### ISSUE TITLE
Need help (paid) to setup Cocorico platform

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#273]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

Dear Cocorico fans

Can somebody help me (I will pay for this job) for a proper setup (no re-design, no modification for now, just Setup) of this platform. Later re-design and installation of payment bundle (Cards and PayPal) will be needed. I think it’s right platform for my idea, but currently it’s more for Php/Simfony gury and not for simple user (like me), who wants just to press Setup and have it done. 
So what is done for now: on Google Hosting installed CentOs/php/Simfony/MongoDB/Apache, Cocorico files and JMSTranslation Bundle (for Russian language).
What is not working (need to be fixed): 
1)	New listing is not posted (but my Google account has all Map APIs, Credit of 260$ and credit card connected)
2)	No possibility to Login with Facebook
3)	I can manage Translation files through JMS Admin panel, but when I switch to Russian language on my site, nothing happened, not Russian titles, etc (but some Russian names of ListingTitle/CategoriesNames/etc which were done in Cocorico Admin panel shown fine. 
4)	Not found Default images like default-user.png and defauk-listing.png 
5)	Need explanation how to setup phone|eMail address confirmation via SMS, eMail    

So the Final Result of Work should be like this https://cocodocto.demo.cocorico.io/en/

Hope to see your proposals Igor.Chernyshev77@gmail.com

**Comment by cocolabssas** [comment]
Hello @igorcherry 

About your issues:

1. If it is not already done. You need to set your domain name in Google console Browser API key and 
set your Google API keys in parameters.yml:
    cocorico_geo.google_place_api_key: ~
    cocorico_geo.google_place_server_api_key: ~

Then clear your cache:
`php app/console cache:clear`

2: You need to configure your Facebook Login app and set the corresponding parameters:

```
cocorico.facebook.app_id: ~
cocorico.facebook.secret: ~
```

3. Clear your cache:
`php app/console cache:clear`

4. You should have them. But you can get them here :
https://github.com/Cocolabs-SAS/cocorico/blob/16276396a7fb26177626c5a121a77c7022452bc3/web/uploads/listings/images/default-listing.png

5. Email validation from email is done by setting  this parameter `cocorico.registration_confirmation` to true in src/Cocorico/CoreBundle/Resources/config/parameters.yml:57.
Phone validation from SMS and other SMS features are available for now on the EE.

Cocodocto is made with the EE. You can contact [cocolabs](https://www.cocolabs.io/fr/contact-devis-creation-marketplace/) to have more informations on it.

Hope it helps!
