### ISSUE TITLE
COCORICO DEMO 3

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#276]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

There is possibility to have the sources to have the same rendering as your demo 3?

https://cocochef.demo.cocorico.io/fr/

**Comment by cocolabssas** [comment]
Hello @gonzasylv,

Cocochef is made with EE. You can contact [cocolabs](https://www.cocolabs.io/fr/contact-devis-creation-marketplace/) to have more informations on it.

If you prefer to develop yourself, you can also customize CE to be like a Cocochef platform.
