### ISSUE TITLE
Docker installation not working

### ISSUE THREAD

**Issue by EmmaTheGr8est** [Cocolabs-SAS/cocorico#277]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

@cocolabssas please i really need your help so i've been trying to install the docker version for cocorico 
but its not rendering properly, please any help

**Comment by cocolabssas** [comment]
Hello @EmmaTheGr8est 

Could you describe more precisely your problem?
