### ISSUE TITLE
Is mongodb used in this project ? 

### ISSUE THREAD

**Issue by kursusHC** [Cocolabs-SAS/cocorico#28]
Hi, 

And thank you for your very nice project. 

I've been through the installation and noticed the mongo database wasn't used at all (though I've not started using the site yet). Is there a reason to make it mandatory ?

**Comment by cocolabssas** [comment]
Hi,

Thanks for the compliment :)
The mongo db is required and used for listings availabilities and price by date management. You can  go to the offerer Dashboard > Calendar or "Prices & conditions" menu to discover it.

**Comment by gsanchez27** [comment]
hello is it still required to install mongodb even though i am planning to use mysql of wamp?

**Comment by gsanchez27** [comment]
Hello

**curl.cainfo = "pathto/cacert.pem"** also can you explain this part what CA certificate is this pertaininbg to?
