### ISSUE TITLE
Somebody tested Cocorico with PHP 7.0?

### ISSUE THREAD

**Issue by xpeering** [Cocolabs-SAS/cocorico#29]
Hello!
Somebody tested / installed Cocorico using PHP 7.0?
(Configure PHP - Tested versions: PHP: 5.4 for Cocorico 0.1.x, 5.6 for Cocorico 0.2.x)
Thanks!

**Comment by xpeering** [comment]
# **About Installing Cocorico version 0.3.2 on Ubuntu server 16.04.2 LTS with default PHP 7**

Trying to install it, I receive the follow error message:

PHP Fatal error:  Cannot use Symfony\Component\Validator\Constraints\True as True because 'True' is a special class name in /var/www/html/marketing/Symfony/src/Cocorico/CoreBundle/Form/Type/Frontend/ListingNewType.php on line 31

then, the only way to install Cocorico 0.3.2 was doing an PHP downgrade to 5.6 tested version.
for more information about downgrade, please check the link below:
http://askubuntu.com/questions/756181/installing-php-5-6-on-xenial-16-04

**Comment by cocolabssas** [comment]
Hi,

Cocorico has not been tested on PHP 7 for now. We will do it when we will upgrade Symfony to the 3.4  version.

**Comment by xpeering** [comment]
Do you know or have some idea when you will upgrade symfony to 3.4 version and install cocorico with PHP 7?
Thanks!
