### ISSUE TITLE
More detailed Install

### ISSUE THREAD

**Issue by PW2512** [Cocolabs-SAS/cocorico#30]
Hi, 
I'm having great issues trying to get this installed and working on a new Linode linux server based on Debian 8. I would ideally like to use CentOS 7 as I'm more familiar with that, however I believe it's not possible. 

Would anyone mind writing a step-by-step guide for me to enable me to get this online and working as I have tried to follow the guide printed, but I've not been successful. 

Thanks

**Comment by cocolabssas** [comment]
Hi,

Firstable if you follow attentively the README install section and you know how to install a LAMP environment, you should manage to install it on a Debian distribution.

Secondly Cocorico works on any Linux  (and even on Windows) distributions correctly configured with :

- a HTTP server (tested on Apache, Nginx),  
- a SGBDR (tested with mysql)
- PHP 5 (tested on PHP 5.4, 5.6)
- MongoDB

So you should also manage to install it on CentOS.

**Comment by fakelefteye** [comment]
hello

>>a HTTP server (tested on Apache, Nginx),  

Is it tested with apache and nginx working together or can I install it only on nginx?

thanks
