### ISSUE TITLE
ListingOption price to 0

### ISSUE THREAD

**Issue by jeromedebeauvoir** [Cocolabs-SAS/cocorico#31]
Hello,

I'd like to enable 0 price ListingOptions. How do you suggest to do that ? 

Thank you 

Amaury

**Comment by kroshp** [comment]
Hello,

This functionality is not in this repository and has no support available. I suggest you to implement it yourself.

**Comment by cocolabssas** [comment]
Hello,

This functionality is not in this repository and has no support available. I suggest you to implement it yourself.
