### ISSUE TITLE
Help to fix Virtual Server parameter

### ISSUE THREAD

**Issue by xboatcom** [Cocolabs-SAS/cocorico#32]
I am trying to run this app in root domain folder:
www.xboat.com.br

But it just can be opened without CSS in the base url:
www.xboat.com.br/web/

How can I change the right parameter to fix this?

Thanks!

**Comment by cocolabssas** [comment]
Your DocumentRoot seems wrong. Check if it is correctly configured as described here:
https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Resources/doc/virtual-hosts.rst.
It should be under the web directory.
