### ISSUE TITLE
fields.html.twig

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#327]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x ]
| Feature request? | [ ]
| Support request? | [ ]

hi @cocolabssas,

when i update fields.html.twig, i have a long error list, did you make a mistake while updating?

Screen : 
http://imgur.com/Ek9Sa7Kl.png

http://imgur.com/3r1rQy4l.png

.. the list is long

my fields.html.twig : https://pastebin.com/Lv8W2Jqq

**Comment by cocolabssas** [comment]
Hi @gonzasylv 

Look at the beginning of your file line 1. You have added extra code `
{% for field in child_form %}`  while updating fields.html.twig.

**Comment by gonzasylv** [comment]
Oh, I did not even see! thanks you @cocolabssas :)
