### ISSUE TITLE
Local http://cocorico.dev/ is showing Symfony welcome page only

### ISSUE THREAD

**Issue by soniacisneros** [Cocolabs-SAS/cocorico#33]
Hello, 

How could I get a working local copy of cocorico? When I type http://cocorico.dev/ all I see is the Symfony welcome page that says "Your application is now ready. You can start working on it at: C:\wamp64\www\cocorico.dev\"

What went wrong? I followed the steps shown in the installation information in github. Thank you. 

This is my configuration, in case it helps. 

(1) My cocorico folder
![image](https://cloud.githubusercontent.com/assets/21006287/25152097/dbf7fcfc-247f-11e7-8e4c-557fe05c0c00.png)

(2) My virtual host information
![image](https://cloud.githubusercontent.com/assets/21006287/25152128/f852ed80-247f-11e7-9638-2cab8134ace3.png)

(3) The page I see at http://cocorico.dev/
![image](https://cloud.githubusercontent.com/assets/21006287/25152187/220a4cc2-2480-11e7-8665-1af8dffd394f.png)

**Comment by BenjaminPE** [comment]
Bonjour,

Je serais en congés jusqu'au 21/04/2017 inclus. Votre mail sera traité par Jeremy Bensidoun.

Cordialement,

Benjamin Perrault

**Comment by kroshp** [comment]
Hi,

I think you miss some steps while reading installation instructions. I suggest you to install it by carefully reading each step of the installation guide.

PS: You vhosts seems to not be saved.

**Comment by cocolabssas** [comment]
Hi,

I think you miss some steps while reading installation instructions. I suggest you to install it by carefully reading each step of the installation guide.

PS: You vhosts seems to not be saved.

**Comment by soniacisneros** [comment]
Thank you for the reply. I am using WAMP and there is a section on ti that says "Virtual hosts", where my vhost "cocorico.dev" appears. I followed the steps and did it three times exactly thinking that I might have missed something. Is there a way in which the installation setup could be more explicit? I think it is missing some details that might be extremely helpful to users like me trying to install it.

**Comment by cocolabssas** [comment]
Many peoples managed to install cocorico by reading the install documentation. I suppose that your problem is specific to your environment. This issue will help to be more explicit on how to resolve your specific problem.
Could you give more details:
- Result of `php composer.phar show -i` executed in C:\wamp64\www\cocorico.dev 
- Content of C:\wamp64\www\cocorico.dev directory
- Content of your web/.htaccess
- Erase your app/log/dev.log, then go to http://cocorico.dev then send your dev.log.

**Comment by cocolabssas** [comment]
I close this issue as it seems to depend more on a misunderstanding than an issue.

**Comment by dailyhypervisor** [comment]
I agree with @soniacisneros the install should certainly be more prescriptive.  I have made 3 attempts to get this working to date and have been unsuccessful so far.  I get a developer who is familiar with Symfony certainly would be able to figure it out, but someone who is not would be challenged to get this to run.
