### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by sixthgalaxy** [Cocolabs-SAS/cocorico#34]
I am trying to install Cocorico in Debian 8. When I ran **php app/check.php** to check for system configuration, I got the following errors:

PHP Warning:  require_once(/var/www/cocorico.dev/Symfony/app/Symfony                                                                                 Requirements.php): failed to open stream: No such file or directory                                                                                  in /var/www/cocorico.dev/Symfony/app/check.php on line 3
PHP Fatal error:  require_once(): Failed opening required '/var/www/                                                                                 cocorico.dev/Symfony/app/SymfonyRequirements.php' (include_path='.:/                                                                                 usr/share/php:/usr/share/pear') in /var/www/cocorico.dev/Symfony/app                                                                                 /check.php on line 3

**Comment by soniacisneros** [comment]
Chek in /var/www/cocorico.dev/Symfony/app/ if you have the file called "Symfony Requirements.php". If you are utilising the Cocorico copy from github, ti does not have it. What I did was to copy "Symfony Requirements.php" file from another Symfony project. This File is only to enable checking of your environment to be able to run Symfony projects. Hope this helps.

**Comment by cocolabssas** [comment]
Bonjour,

Mon adresse mail principale a changé, dorénavant veuillez me contacter sur anthoni.noyon[at]cocolabs.io.

Anthoni Noyon

------------------

Hi,

My main e-mail address has changed, from now on please contact me on anthoni.noyon[at]cocolabs.io.

Anthoni Noyon

**Comment by sixthgalaxy** [comment]
@soniacisneros-Thank you for your reply. I will try out your solution and let you know. Have you tried to use Cocorico dockers installation?

**Comment by sixthgalaxy** [comment]
@soniacisneros-    I have created Symfony Requirements.php file and that seems to have fixed the PHP error, but now I am getting the following message when try to access the app via URL. Any help with this will be greatly appreciated.

**No route found for "GET /en/config.php"**

**Comment by cocolabssas** [comment]
Hi,
I didn't know how you install cocorico but the file 'Symfony Requirements.php' should automatically be installed if you follow the installation documentation and should not have space in its name.
I suggest you to simply and attentively follow the README install section and add more details of your problems when you have some.

**Comment by soniacisneros** [comment]
@sixthgalaxy  I know right?? I faced the same and tried several times. Since the "config.php" is just to check if the system is ok to run the project I believe that if SymfonyRequirements.php says everything is ok then you are good to go. I would like to know your opinion because I do not know if it just me or the installation "documentation" is very summarised that I suspect I missed some details that are not explicitly explained and that is why we got this kind of problems. Please let me know if you achieve to get your cocorico working. Thanks for the help!

**Comment by sixthgalaxy** [comment]
I have found the following error in the log:

Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "**No route found for "GET /web/config.php**"" at /var/www/cocorico.dev/Symfony/app/cache/dev/classes.php line 2100 Context: { "exception": "Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException)" }

**Comment by sixthgalaxy** [comment]
@cocolabssas 

I have found the following error in the log:

Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/config.php"" at /var/www/cocorico.dev/Symfony/app/cache/dev/classes.php line 2100 Context: { "exception": "Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException)" }

**Comment by cocolabssas** [comment]
@sixthgalaxy 
Without further details it can be difficult to be sure of what is causing of your problem.
But from you log i deduct that you are accessing a wrong url : [yourdomain]/web/config.php.
Try [yourdomain]/config.php instead (See https://github.com/Cocolabs-SAS/cocorico#checking-your-system-configuration).

**Comment by cocolabssas** [comment]
I close this issue as it seems to depend more on a misunderstanding than an issue.
