### ISSUE TITLE
question about mongodb

### ISSUE THREAD

**Issue by gomonkey** [Cocolabs-SAS/cocorico#35]
Hello I will try to install today your project on my server and i have some doubt after did it some failure local test
I tested on php 7.0, i will use php 5.5 or 5.6
I saw that Mongo is deprecated, now i don't know if I have to install Mongodb or Mongo.
What can you suggest to me? will be a problem if I will install mongodb?
Thanks
Gabriele.

**Comment by gomonkey** [comment]
in the end I decided to use mongo

**Comment by cocolabssas** [comment]
Hi, 
for now it has been tested with php mongo extension.  But it should also work with mongodb extension. Documentation will be updated as soon as it will be tested with mongodb extension.
