### ISSUE TITLE
Customize Listing Page

### ISSUE THREAD

**Issue by vesonal** [Cocolabs-SAS/cocorico#350]
I want to customize Listing page, basically want to add some text box fields with 'add more' option, 
Say if any cook want to add listing then want to add utensils using in cooking, I want a way to allow him to add multiple utensils. So how can we customize the listing section ??

**Comment by nico01f** [comment]
+1

**Comment by cocolabssas** [comment]
A solution without implementation could be the creation of utensils in characteristics in admin and then let  the offerer choose them in his listing edition page. The drawback is that offerer will not fill the name of his utensils but should choose them from existing lists. The advantage is that you control and standardized all utensils names (and you do not need to implement it).
