### ISSUE TITLE
Unable to find template "@JMSTranslation/translate/index.html.twig"

### ISSUE THREAD

**Issue by wolojonathan** [Cocolabs-SAS/cocorico#359]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hello,

After a succesfull installation and deployment of the dev environment, I'm having trouble with the translations web interface.

It's throwing the error Unable to find template "@JMSTranslation/translate/index.html.twig"

I saw in other threads that this error already occured, and that you even found a workaround on schmittjoh's git repository.

However, I've tried to setup the framework as written, to update from the latest version on schmittjoh's repo - without success.

Do you have any idea how I could solve that issue ?
If you need any kind of specifications for my environment, please let me know.

P.S. : If this is an issue you would like to discuss in direct chat, I am French. :)

Thanks in advance !

**Comment by cocolabssas** [comment]
Hello,

Indeed we have identified this issue. A fix will be available in few days. 
In the meanwhile could you try this fix:

```
cd vendor/jms/translation-bundle/JMS/TranslationBundle/Resources/views
ln -s Translate translate
```

**Comment by wolojonathan** [comment]
Hi guys,

Thanks, that's a solved one ! ;-)
