### ISSUE TITLE
Can’t find cocorico_geo.google_place_SERVER_api_key

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#361]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Hello

New listing is not posted
![image](https://user-images.githubusercontent.com/35894283/52807144-012fad80-308b-11e9-822e-dc3d0ef05032.png)
but in my Google account all Map APIs enabled and current credit of 255 euro and credit card connected
![image](https://user-images.githubusercontent.com/35894283/52807542-06d9c300-308c-11e9-9150-e84ed307686c.png)

So I think that I need to set Google Place SERVER API, but I didn’t see it in google console. Can you help me to find it (or maybe it has a new name)

**Comment by cocolabssas** [comment]
Hello,

Your Google APIs enabled are correct.
The cause of the issue can be the following:
- Your API keys cocorico settings are wrong : 
  - Look at the app/config/parameters.yml and check that  the Google API keys are correct and corresponds to the Google browser / server key key :
`
cocorico_geo.google_place_api_key: [Google browser key]
cocorico_geo.google_place_server_api_key: [Google server key]
`
  - Check also if you restricted API access in the Google console that your domain and your server IP correspond. 

To have more informations on the cause  of the issue :
- Check your browser console  to see if there are any errors?
- Check your Symfony logs 
- Enabled the debug mode of the Cocorico Geocoder here : `src/Cocorico/GeoBundle/Geocoder/Provider/GoogleMaps.php:45`
and check in your browser network console the response of the `/en/geocoding/[lat]/[lng]fr/reverse_geocoding?token=xxx url`. You will see informations of what is happening for the reverse geocoding operation.

Hope it helps

**Comment by igorcherry** [comment]
Thank you very much, the issue is solved, and seems that similar like in #118
