### ISSUE TITLE
Error during Add New Category in Admin panel

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#362]
| Q                | A
| ---------------- | -----
| Bug report?      | [ X]
| Feature request? | [ ]
| Support request? | [ ]

Hello
When I try to Add new Category (and Characteristic) in Admin panel, I have error message
![image](https://user-images.githubusercontent.com/35894283/52807938-1a395e00-308d-11e9-884a-0440bf879735.png)
Other creations/Add (Characteristic Group and Type) works fine

**Comment by wolojonathan** [comment]
Hi,

I managed to solve this issue by changing 1 line in /src/Cocorico/CoreBundle/Entity/

In the function __toString(), I've added .'' after $this->getName(), to force the value to a String even though the current Category has no Name.

**Comment by igorcherry** [comment]
Solved,  thanks to wolojonathan

**Comment by cocolabssas** [comment]
Hello,

The issue is fixed by this recent commit : cc74ab1124b318d7eabc143f1df1e5c720172d8f.
