### ISSUE TITLE
default listing

### ISSUE THREAD

**Issue by gsanchez27** [Cocolabs-SAS/cocorico#368]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | []
| Support request? | [Q]

Hello, Just install cocorico temdplate I am getting some error on displaying the image on default listing. Please see the image below

![sc](https://user-images.githubusercontent.com/5301578/53773505-b5538400-3f25-11e9-97c1-9fe6d2b952e3.png)

I check the gd2 extension on php.ini on my wamp and it is enabled. 

i have this config on my paramters.yml file "cocorico.image_driver: imagick"

Thank you in advance :)

**Comment by actionbills** [comment]
i wish i could help i can’t even get my local host to show the website and it states in the terminal cocorico is alive. if you can help please contact me at saintone8@hotmail.com

**Comment by cocolabssas** [comment]
Hello @gsanchez27

You should set `cocorico.image_driver` parameter to `gd` if you do not have imagick installed:

`cocorico.image_driver: gd`

**Comment by gsanchez27** [comment]
Hello @cocolabssas thank you for your response I was able now to make it work :)
