### ISSUE TITLE
No Invoice and no possibility to made Rating

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#369]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X ]

Hello Cocorico.  Can you help or advise.  After Booking as Accepted and Paid and Time of Booking passed, Asker can See invoice in Payments block as Payments Done , but Offrer don’t see anything. Also this no possibility to Rate and Write Comments (Asker and Offrer don't see this buttom). Is it Error, or I didn’t turned on something in config.
![image](https://user-images.githubusercontent.com/35894283/53794037-6c083200-3f2f-11e9-8f0b-37a2e74b94ab.png)

![image](https://user-images.githubusercontent.com/35894283/53794057-75919a00-3f2f-11e9-845e-11a2b5b44070.png)

**Comment by cocolabssas** [comment]
Hello @igorcherry

In the installation guide section [cron](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/crons.md) you will see all the cron you need to enabled.

For your issue the Bookings validation cron `php app/console cocorico:bookings:validate --env=dev` should fix it.
 
You can of course execute the command manually.

**Comment by igorcherry** [comment]
Thank you a lot, it was really topic with Crons
