### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by gomonkey** [Cocolabs-SAS/cocorico#37]
Hello, I followed this issue [#23](https://github.com/Cocolabs-SAS/cocorico/issues/23).
I extract all translations by this perfect code for me
`php app/console translation:extract it --config=cocorico`
I added 'it' in the parameters file in `Cocorico/CoreBundle/Resources/config/parameters.yml`
I opened and updated almost every thing in the translation page in administration ( __translations )

but still not working, I can change language in Italian but still is in english.
I forgot something ?
Thanks

**Comment by cocolabssas** [comment]
Hello,

Have you clear your cache? 
`php app/console cache:clear --env=dev`

Also in your parameters.yml you should have something like this:

    locale: en
    cocorico.locale: en
    cocorico.locales:
            - en
            - it
    cocorico.locales_string: en|it`

**Comment by cocolabssas** [comment]
I close the issue as it is more related to support thanto an issue.
Don't hesitate to create an issue if you find one.
Thanks.
