### ISSUE TITLE
terminal says coco is alive but i can’t find it help!

### ISSUE THREAD

**Issue by actionbills** [Cocolabs-SAS/cocorico#371]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

**Comment by Natfrmlncr** [comment]
As a new user trying to work with unfamiliar tech stacks, I feel your pain... but could you please detail what you have tried, and environment details? I'll assume you've installed this on your local machine... So have you tried to access localhost/ on your browser?

**Comment by actionbills** [comment]
I’m going to write a detail description as much as possible of what I
understand for you and where I think I went wrong. It may be the ports or
conflicting server or Ip.  I think what I’m missing is since virtualbox
 was installed by the docker toolbox I still haven’t went inside virtual
box and added a windows operating system and set it up there. When I opened
up virtual box it asked me to update it which I updated via the link then
it gave me a few errors which I will figure out. I think I may need a
windows iso image which I have somewhere. Maybe that’s the issue. Again
thanks for being understanding knowing that I don’t understand the
technologies. I figured it all out in one night.  So maybe I need to do it
all over again and go slower.  Oh and yes I installed this on a local
machine with windows 7.

Terry

**Comment by actionbills** [comment]
ok so back to the drawing board. i reinstalled docker toolbox with virtualbox. my question is i have been searching for an upgrade command to update virtualbox in the docker command line but cant find it. do i need to upgrade manually from the website on host computer or with docker command? 
2nd once virtualbox is upgraded do i install my windows iso and open a virtual instance before installing cocorico?

**Comment by actionbills** [comment]
oh and this is all on a local desktop machine

**Comment by cocolabssas** [comment]
Hello @actionbills 

I suggest you to not use docker on windows. As you can see [here](https://github.com/docker/for-win/issues/1936) or  [here](https://github.com/docker/for-win/issues/1674)  there are some issues with this config.
The best would be to install Cocorico on linux.

**Comment by cocolabssas** [comment]
We close this issue as it is a duplication of issue #373
