### ISSUE TITLE
Start the container issues cocorico

### ISSUE THREAD

**Issue by actionbills** [Cocolabs-SAS/cocorico#373]
when i try to run the container in the docker terminal to install cocorico it gives me this error

harris5@harris5-PC MINGW64 /c/Program Files/Docker Toolbox

$ docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p 27017:27
017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/d
ata/db -e HOST_UID=$UID cocolabs/cocorico

C:\Program Files\Docker Toolbox\docker.exe: invalid reference format: repository
 name must be lowercase.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

**Comment by actionbills** [comment]
when i try to run the container in the docker terminal to install cocorico it gives me this error

harris5@harris5-PC MINGW64 /c/Program Files/Docker Toolbox

$ docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p 27017:27
017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/d
ata/db -e HOST_UID=$UID cocolabs/cocorico

C:\Program Files\Docker Toolbox\docker.exe: invalid reference format: repository
 name must be lowercase.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by cocolabssas** [comment]
Hello @actionbills 

As already answered in your previous and same issue :

> I suggest you to not use docker on windows. As you can see [here](https://github.com/docker/for-win/issues/1936) or  [here](https://github.com/docker/for-win/issues/1674)  there are some issues with this config.
> The best would be to install Cocorico on linux with or without docker but you can also install it on windows without docker for dev env.

**Comment by actionbills** [comment]
ok I received your email after I installed cocorico docker installation. I
seemed to follow all steps and started the container by changing a bit of
the code

docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p
27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v
`pwd`/tmp/mongo:/data/db -e HOST_UID=$UID cocolabs/cocorico

and it installed correctly. it states Cocorico is alive. Afterwards it
there at the alive and I had to close it and start the docker terminal over
to get the command prompt line back. I went to local host in my web browser
from my desktop computer and typed localhost again and it did not work me.
So I think I may have a port mapping problme? Or maybe I should open up
ports on my computer? if you have any suggestions let me know. otherwise i
will take your advice and compile it with linux. Thank you

**Comment by cocolabssas** [comment]
Hello @actionbills,

It seems specific to windows / docker configuration and we do not support it. The best would be to install Cocorico docker image on a linux distribution.
FYI: All issues related to docker need to be posted to the [Cocorico docker  repository](https://github.com/Cocolabs-SAS/cocorico-docker) 

Thanks!
