### ISSUE TITLE
default credentials do not work!

### ISSUE THREAD

**Issue by rkhyd** [Cocolabs-SAS/cocorico#374]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [* ]

The default credentials provided in the documentation do not work. how do i reset or recover them?

**Comment by cocolabssas** [comment]
Hello @rkhyd 

Could you precise what you mean by the default crendentials?
You will find [here](https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/DataFixtures/ORM/UserFixtures.php) the default accounts you can used in Cocorico.
If it does not work ensure that you follow the [installations instructions](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/index.md) and more precisely the [database initialization](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md#initialize-the-sql-and-nosql-database).

Hope it helps!

**Comment by rkhyd** [comment]
hello @cocolabssas ,
The issue was i was getting an error when importing the databse.. I have sorted it out now.. thank you for pointing me in the right direction. 
This was the error on database import.
`PHP Warning:  require(/var/www/vhosts/kidswell.ca/httpdocs/app/cache/prod/doctrine/orm/Proxies/__CG__CocoricoCoreBundleEntityListingCharacteristicType.php): failed to open stream: No such file or directory in /var/www/vhosts/kidswell.ca/httpdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 223
PHP Warning:  require(/var/www/vhosts/kidswell.ca/httpdocs/app/cache/prod/doctrine/orm/Proxies/__CG__CocoricoCoreBundleEntityListingCharacteristicType.php): failed to open stream: No such file or directory in /var/www/vhosts/kidswell.ca/httpdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 223
PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/kidswell.ca/httpdocs/app/cache/prod/doctrine/orm/Proxies/__CG__CocoricoCoreBundleEntityListingCharacteristicType.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/kidswell.ca/httpdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 223

In AbstractProxyFactory.php line 223:

  Compile Error: require(): Failed opening required '/var/www/vhosts/kidswell.ca/httpdocs/app/cache/prod/doctrine/orm/Proxies/__CG__CocoricoCoreBundleEntityListingCharacteristicType.php' (include_
  path='.:/opt/plesk/php/7.1/share/pear')
doctrine:fixtures:load [--append] [--em EM] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>`
i fixed the issue with the command `app/console cache:warmup --env=prod`
Then i imported the database again and the credentials are working now.. thank you..
