### ISSUE TITLE
Can't see see other's profile

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#376]
| Q                | A
| ---------------- | -----
| Bug report?      | [X ]
| Feature request? | [ ]
| Support request? | [ ]

**Comment by cocolabssas** [comment]
Hello @igorcherry 

Please provide more information about your issue.

**Comment by igorcherry** [comment]
Hi, this is more info

When I am **not login in** and try see other's offerer profile by this link https://mysite/en/user/237937667/show, but site redirect me to login page
When I am **login in** and try see other's offerer profile by this link https://mysite/en/user/237937667/show, site show me **my own profile** page https://mysite/en/user/2097279397/show

**Comment by cocolabssas** [comment]
Hi,

Did you made some code modifications, because we can't reproduce your issue?

**Comment by igorcherry** [comment]
Hello. I am not programmer, so for srure didn't change the code
