### ISSUE TITLE
Not able to run the composer..

### ISSUE THREAD

**Issue by ibrahimbm** [Cocolabs-SAS/cocorico#379]
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for alcaeus/mongo-php-adapter 1.1.3 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
  Problem 2
    - Installation request for mongodb/mongodb 1.2.0 -> satisfiable by mongodb/mongodb[1.2.0].
    - mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb is missing from your system.

**Comment by tiretdusix** [comment]
Hello.

Composer is telling you that your system is lacking MongoDB and/or MongoDB extension for PHP.

In order to make full usage of Cocorico's booking system, you will need MongoDB installed, as well as the php mongodb extension.

>the requested PHP extension mongodb is missing from your system.

`alcaeus/mongo-php-adapter` installation is disallowed by composer until then.

Best regards.

**Comment by ibrahimbm** [comment]
I have already installed the MongoDB on mac and also on the PHP


MongoDB support | enabled
-- | --
MongoDB extension version | 1.2.9
MongoDB extension stability | stable
libbson bundled version | 1.5.5
libmongoc bundled version | 1.5.5
libmongoc SSL | enabled
libmongoc SSL library | OpenSSL
libmongoc crypto | enabled
libmongoc crypto library | libcrypto
libmongoc crypto system profile | disabled
libmongoc SASL | enabled




I would be needing your help to set up this on my local server

**Comment by cocolabssas** [comment]
Hi @ibrahimbm 

Could you send us what `php -i | grep Mongo` is returning.

**Comment by ibrahimbm** [comment]
MongoDB support => enabled
MongoDB extension version => 1.2.9
MongoDB extension stability => stable

**Comment by cocolabssas** [comment]
Could you update your mongodb PHP ext to a version greater than 1.3?

**Comment by ibrahimbm** [comment]
now i have succesfully installed the composer and app installed perfectly.

Some issue still.. not able to see the admin dashboard: 
http://local.cocorico.com/admin/dashboard (i set this virtual host as this)
not found error.

**Comment by ibrahimbm** [comment]
SQL database initialisation: i am getting the below error..

 ./bin/init-db php --env=dev
Could not open input file: app/console
Could not open input file: app/console
Could not open input file: app/console
Could not open input file: app/console

**Comment by cocolabssas** [comment]
Hi @ibrahimbm 

The init-db script is fixed in this commit https://github.com/Cocolabs-SAS/cocorico/commit/33e767819d280d8e2bc85d8c6ca09b122943da36.
I suggest you to update to the last version of Cocorico.

**Comment by ibrahimbm** [comment]
Thank you .. its udpated. but still error with the mongodb 

:  
Server at localhost:27017 reports wire version 0, but this version of libmongoc requires at least 3 (MongoDB 3.0)
root@vagrant-ubuntu-trusty-64:/var/www/html/proptech# php -i | grep Mongo
MongoDB support => enabled
MongoDB extension version => 1.5.3
MongoDB extension stability => stable

**Comment by cocolabssas** [comment]
Could you send us the version of mongodb you use and check this answers:
- https://stackoverflow.com/questions/50709696/compatibility-between-mongodb-server-and-mongo-c-driver
- https://stackoverflow.com/questions/52669717/mongodb-exception-server-reports-wire-version-0-but-version-of-libmongoc-requi
