### ISSUE TITLE
Super-Admin can't change his profile details and can disable himself

### ISSUE THREAD

**Issue by gbenzglobal** [Cocolabs-SAS/cocorico#38]
Hi There,

Thanks for the cocorico. It is great. Recently, I installed it on centos 7) your latest version). 

I found 

01. Super admin can't change his profile details ?
02. Super admin can disable himself?

How can I reset this. Thank you

**Comment by cocolabssas** [comment]
Hi,

For the two points you can set your "disabled" fields option value to "false" if the user has the role   "ROLE_SUPER_ADMIN" in Cocorico/UserBundle/Admin/UserAdmin.php:

      `...
       ->add(
               'firstName',
                null,
                array(
                    'required' => true,
                    'disabled' => [Add your condition here]
                )
            )`

**Comment by cocolabssas** [comment]
I close the issue as it is more related to support thanto an  issue. 
Don't hesitate to create an issue if you find one.
Thanks.

**Comment by gbenzglobal** [comment]
Thank you
