### ISSUE TITLE
Registration confirmation Error

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#380]
| Q                | A
| ---------------- | -----
| Bug report?      | [ X]
| Feature request? | [ ]
| Support request? | [ ]

Hello, 
in the file **parameters** when I switched on cocorico.registration_confirmation: **TRUE** and I tried to Register as a new user, I got next error
![image](https://user-images.githubusercontent.com/35894283/54638475-64966c00-4a8b-11e9-9bb1-58e7dcea0870.png)

**Comment by cocolabssas** [comment]
Hi @igorcherry 

We can not reproduce your issue. Did you made some changes in Cocorico like upgrading packages or disabling some Cocorico bundle like UserBundle?
