### ISSUE TITLE
Error when Time unit is day

### ISSUE THREAD

**Issue by Damiano1376** [Cocolabs-SAS/cocorico#381]
Hello,

I have just installed the latest version. Everything is fine, but when i change the time unit to 1440, i have an 500 error when i try a research : 

Child "time_range" does not exist.
Exception Logs 1 Stack Trace

In vendor/symfony/symfony/src/Symfony/Component/Form/Form.php (line 923)
throw new OutOfBoundsException(sprintf('Child "%s" does not exist.', $name));

Form->get('time_range')
in src/Cocorico/CoreBundle/Form/Type/Frontend/ListingSearchResultType.php (line 219)
$timeRange = $form->get('time_range')->getData();

No problem with time unit 60.

| Q                | A
| ---------------- | -----
| Bug report?      | [ x]
| Feature request? | [ ]
| Support request? | [ ]

**Comment by cocolabssas** [comment]
Hi @Damiano1376,

Indeed we identified this issue. It will be fixed today.

**Comment by cocolabssas** [comment]
Fix here 7fdb243a08b6a883e601132ead62f30d26c4d862.
