### ISSUE TITLE
Characteristics

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#383]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Dear Cocorico team
Is it possible in CE version  
1.	setup Characteristics as a Check Boxes (now it’s only list  Yes/No/Maybe or 1/2/3/4)
2.	Group Characteristics like in CocoDev (only one main Characteristics in Search line and then you drill down into Characteristics Groups)
3.	I don’t need to select amount of days, Which parameter I should switch off ?
4.	CSS is very nice in CocoDev (easy to read and navigate), can I got it instead of self modification CSS files?

Thanks in advance
![image](https://user-images.githubusercontent.com/35894283/54830037-013d5180-4cb8-11e9-8065-722672322a14.png)

**Comment by cocolabssas** [comment]
Hello @igorcherry 

For your 3 first questions you need to implement it. 
Not sure to understand the last question. Do you mean you want to use Cocodev CSS instead of the CE  ones?

**Comment by igorcherry** [comment]
Hello,
for first 3 question I understand. Will do. 
4 question - Yes, if it possible to get Cocodev CSS and put it instead of my CE default CSS
5 question - now in file parameters, I can take my fee from Offrerer/Asker as % from Price, how can I switch to fix price (e.g. always 10$ from Asker and 20$ from Offrerer? 
![image](https://user-images.githubusercontent.com/35894283/55069298-ff8ed780-5083-11e9-863f-465a29d0b77d.png)
