### ISSUE TITLE
Listing price precision

### ISSUE THREAD

**Issue by Damiano1376** [Cocolabs-SAS/cocorico#384]
Hello cocorico team,

in previous versions i could set prices with decimals. But in the last update, when i set cocorico.listing_price_precision: true , prices are still without decimal.

Is it a bug ?

| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

**Comment by cocolabssas** [comment]
Hello @Damiano1376,

Could you set this parameter to 2 and precise where your prices are displayed without decimal.
You need to know that in some places, price are displayed without decimal independently of this parameter (in result page for example). If you need to display decimal for this kind of price you need to go to the corresponding twig template and change the last parameter of `format_price` twig filter.

Ex for result page:
In `src/Cocorico/CoreBundle/Resources/views/Frontend/ListingResult/_result_listings.html.twig:9`
change 
`{% set price = (listing.price / 100) | format_price(app.request.locale, 0) %}`
by 
`{% set price = (listing.price / 100) | format_price(app.request.locale, 2) %}  `

**Comment by Damiano1376** [comment]
Ok thanks,
 
I want to add decimals in the home page, _high_ramk.html.twig
It's ok with
{% set price = (listing.price / 100) | format_price(app.request.locale, 2) %}

Thank you !
