### ISSUE TITLE
Does Cocorico have event bookings?

### ISSUE THREAD

**Issue by arvana** [Cocolabs-SAS/cocorico#386]
| Q                | A
| ---------------- | -----
| Bug report?      | [ no ]
| Feature request? | [ yes ]
| Support request? | [ yes ]

Does Cocorico have event bookings?  I am looking for a platform that allows offerors to sell services that include one-on-one time, and also many-on-one events.

The events could be in a physical venue or a webcast with a set time.  So that service should allow for multiple buyers of the same timeslot / event.  Also there needs to be a way to track the buyers to allow access, some kind of ticketing system.

I'm asking because I didn't see this functionality listed anywhere, and otherwise it looks like Cocorico would be a great fit for me.  So maybe it's already there, or if not, is it something that would be of interest to develop?

**Comment by cocolabssas** [comment]
Hello @arvana 

CE does not have multiple buyers of the same timeslot. To have it, a stock management feature should be added to Cocorico allowing to have more than one buyers and no more than X on the same timeslot.
Indeed it would be interesting to develop it. We've already planned to add this notion of stock but without precise date of delivery for now.

**Comment by arvana** [comment]
OK, thanks very much for responding.  I'm going to check out the codebase and see if I can make it work for my application -- you have a lot of great features!

**Comment by cocolabssas** [comment]
Thanks !
