### ISSUE TITLE
Cocorico Functions Capability

### ISSUE THREAD

**Issue by automotechnologies** [Cocolabs-SAS/cocorico#387]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi everyone using Cocorico, I'm trying to build my platform to see the scalability of Cocorico as my platform moving forward but would like to check some concerns you guys may have experience with.

1 - Can we manually activate "Offerer" status as admin? So users who create an account are all "Askers" unless admin enable the account to also be "Offerer" before they can create listings? I know the work around is to enable pre-moderation of listings, but it would be better if we can manually enable accounts to be Offerer.

2 - Instant booking & Booking Request - By default the system seems to be booking request where the offerer must accept the booking for it to be confirmed. Are we able to have both instant and request types? So certain accounts can be instant and certain will be booking request or only one type, either instant or request? If so how do I change it to instant?

3 - Last, why is my Cocorico dashboard empty compared to other screenshots I've seen?

![28977089-04bcb632-7917-11e7-89d2-91a5dcefb49b](https://user-images.githubusercontent.com/48977584/55861083-dac85300-5b9f-11e9-9a76-d12962b917be.jpg)

![image](https://user-images.githubusercontent.com/48977584/55861106-e7e54200-5b9f-11e9-8fe7-7c44ec0b4640.png)

Thanks,
Otomo

**Comment by cocolabssas** [comment]
Hi @automotechnologies 

1 - This feature does not exist. The work needed to do it should not be too complex neither too long.  If you have Symfony skills you should be able to do it yourself.

2- This feature is indeed useful but does not exist and is more complex to implement. I will not be surprised that it is added to Cocorico one day.

3- For now this feature is only available in the Enterprise edition. 

Hope it helps!

**Comment by automotechnologies** [comment]
Hi CocoLabs, thank you for the clarification.

Any idea how to change between instant booking and booking request? Might be better for me to start with instant booking and figure out how to implement both options.

Thanks!

**Comment by cocolabssas** [comment]
Hi @automotechnologies 

The instant booking functionality does not exists for now. As it is a relative complex feature we need some time to analyse and have an idea on how to change the booking request to instant booking. 
We will do it when we will add this feature not planned for now.

**Comment by automotechnologies** [comment]
Hi @cocolabssas 

Based on the cocorico feature set on the site -

**Booking Flow**
Cocorico allows you to customize your booking flow as required. You can set validation rules, allow _instant booking_ and define delays after which requests expire.

So currently it can only support booking requests and not instant booking? Even if I'm just going to use 1 type.

**Comment by automotechnologies** [comment]
Oh one more important question is, right now all listings are unique right? So if a booking is made for day X, it will be unavailable, is there a way we can set a "quantity" for a listings so they can accept multiple bookings for the same day, or at least a simpler unlimited, and manually toggle to unavailable once it's fully booked.

**Comment by automotechnologies** [comment]
Hi, any updates on whether can we change it to instant booking?

Thanks Cocorico!

**Comment by automotechnologies** [comment]
Hi team or anyone able to help with those questions?

Thanks!
