### ISSUE TITLE
Cocorico is working very slowly

### ISSUE THREAD

**Issue by imanalopher** [Cocolabs-SAS/cocorico#389]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

Hi @cocolabssas, I have problem with cocorico, Cocorico is working very slowly
My php version (php7.1)

Loading 30seconds every steps, image is here:
https://i.imgur.com/RYtMkMZ.png

**Comment by cocolabssas** [comment]
Hi @imanalopher,

It seems that in your profiler  "geocoding" twig files are taking around 30 seconds.
Did you fill your Google Map API account correctly by filling your bank account for example.
If you not fill your bank account Google will not let you use his APIs.
FYI: It should be free until you reach a high number of requests. See [google maps pricing](https://cloud.google.com/maps-platform/pricing/sheet/)  for more information.

Hope it helps

**Comment by imanalopher** [comment]
I have resolve my problem, Problem was with `Symfony/Intl` bundle and I updated to version `4.2`. Weird php7.1 has conflict with the bundle.

**Comment by cocolabssas** [comment]
Indeed there is an issue with ICU version  64.1 (https://github.com/symfony/symfony/issues/31087).
