### ISSUE TITLE
virtual host dev

### ISSUE THREAD

**Issue by comprateur** [Cocolabs-SAS/cocorico#39]
Hi, is it normal in the virtual host dev example to have
 DocumentRoot /var/www/cocorico.dev/Symfony/web
    <Directory /var/www/cocorico/web>

I don"t have any cocorico folder only  /var/www/cocorico.dev/Symfony/web

thanks

**Comment by cocolabssas** [comment]
Hi,

Indeed you have to read :

```
DocumentRoot /var/www/cocorico.dev/Symfony/web
<Directory /var/www/cocorico.dev/Symfony/web>
```

The typo is fixed: https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Resources/doc/virtual-hosts.rst. 

Thanks!
