### ISSUE TITLE
Delete Google+ but Add Google Account Login/Registration

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#390]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [X]
| Support request? | [ ]

Hello Cocorico team

I have a proposal, due to “Google+ is no longer available for consumer (personal) and brand accounts” it’s no need for Google Share (not it;s three bottons Fb, Twitter, **Google+**). But a lot of people (as minimum all who have Android phones) has Google Account and can be very helpful to add Registration/Login not only with Facebook Account but also with Google Account 
![image](https://user-images.githubusercontent.com/35894283/56358475-f7d3d600-61de-11e9-8bb9-1414071d7275.png)

Thanks in advance

**Comment by cocolabssas** [comment]
Hi @igorcherry,

Thanks for this pertinent suggestion :)

**Comment by cocolabssas** [comment]
Not planned for now
