### ISSUE TITLE
Access denied for user exception

### ISSUE THREAD

**Issue by Rituparna007** [Cocolabs-SAS/cocorico#391]
At the time of installation when I am putting this command 
.\bin\init-mongodb.bat --env=dev
I am getting the following error
![1](https://user-images.githubusercontent.com/41118562/56500520-ce8daf80-6528-11e9-8986-654440fc149e.png)
Please suggest from where this issue arising. I am following this link totally:
https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md

**Comment by cocolabssas** [comment]
Hi  @Rituparna007 

You should execute these SQL statements : https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-server-windows.md#mysql.
by  replacing {DB}, {DBUSER}, {DBUSERPWD} with the corresponding values you have in your parameters.yml:

Ex for:
```
database_name:     mydb 
database_user:     myuser 
database_password: mypassword
```

Your SQL should be :
```
CREATE DATABASE IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, REFERENCES ON mydb.* TO myuser@localhost IDENTIFIED BY 'mypassword'
```

**Comment by cocolabssas** [comment]
Feel free to reopen it if problem persists
