### ISSUE TITLE
Installed cocorico but cannot access admin/dashboard

### ISSUE THREAD

**Issue by Rituparna007** [Cocolabs-SAS/cocorico#392]
I have installed cocorico. But cannot access admin/dashboard. Can you please help me how to access that?

**Comment by cocolabssas** [comment]
Hi @Rituparna007 

Could give more informations:
- URL of admin you try to access
- Errors 
- Any other informations helping us to help you

**Comment by moscolb** [comment]
^ Hi @cocolabssas I have the exact same problem. The following URL works in my browser: cocorico.local takes me to the root directory. However, cocorico.local/admin/dashboard takes me to a blank page that reads "The requested URL was not found on this server."

This leaves me with a bunch of downloaded and installed files with no way to access the application. Any help would be greatly appreciated!

**Comment by liyanonline** [comment]
I have the same problem.

**Comment by ateeq24** [comment]
I am having the same problem

**Comment by ateeq24** [comment]
I was able to access the admin panel through [](http://localhost/cocorico.local/web/app.php/admin)
