### ISSUE TITLE
Installing SSL with wamp is not working

### ISSUE THREAD

**Issue by Rituparna007** [Cocolabs-SAS/cocorico#393]
Following the Server Installation doc when I am trying to do these steps these are not working:

Install SSL with WAMP

    Install Win32 OpenSSL here http://slproweb.com/products/Win32OpenSSL.html
    Copy/paste libeay32.dll, ssleay32.dll into php bin folder (ex: C:\wamp64\bin\php\phpx.x)

1)My system having 64 bits operating system,so should I use SSL for win 32?
2)On that SSl link I am unable to download MSI/EXE
3) When I am trying to do this

Generate self signed certificate
cd C:\wamp\bin\apache\Apache2.4.4\conf

I have got an error "could not open input file open ssl" when that file is existing there.

Please help

**Comment by cocolabssas** [comment]
Hi @Rituparna007?

As installing a self signed certificate on Windows is not so easy i recommend you to not use https and use http instead on your dev env.
On production it is strongly recommended to use a linux based system.

**Comment by cocolabssas** [comment]
Feel free to repoen it if needed
