### ISSUE TITLE
Generate Private Key not working

### ISSUE THREAD

**Issue by Rituparna007** [Cocolabs-SAS/cocorico#395]
Hello

I have installed Open SSL under C:/Program Files and then also done copy/paste both the files libeay32.dll, ssleay32.dll. But after that when I am trying to do this 
#Generate private key
openssl genrsa -aes256 -out key\private.key 2048

Its showing could not open open ssl. Please help.

**Comment by cocolabssas** [comment]
Hello @Rituparna007,

Thanks to continue to discuss into the  issue you've  already created here https://github.com/Cocolabs-SAS/cocorico/issues/393
