### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cocorico_dev.listing' doesn't exist

### ISSUE THREAD

**Issue by Rituparna007** [Cocolabs-SAS/cocorico#396]
After installing when I am hitting this link http://coco.local/en/ this following error is coming

-----------------------------------------------------------------------------------------------
An exception occurred while executing 'SELECT DISTINCT id_1 FROM (SELECT '' AS sclr_0, l0_.id AS id_1, l0_.price AS price_2, l0_.certified AS certified_3, l0_.average_rating AS average_rating_4, l0_.comment_count AS comment_count_5, l0_.createdAt AS createdAt_6, l1_.title AS title_7, l1_.description AS description_8, l1_.slug AS slug_9, l1_.locale AS locale_10, l1_.id AS id_11, l2_.id AS id_12, l3_.id AS id_13, l3_.lft AS lft_14, l3_.lvl AS lvl_15, l3_.rgt AS rgt_16, l3_.root AS root_17, l4_.name AS name_18, l4_.locale AS locale_19, l4_.id AS id_20, l5_.id AS id_21, l5_.name AS name_22, u6_.id AS id_23, u6_.first_name AS first_name_24, u7_.id AS id_25, u7_.name AS name_26, l8_.id AS id_27, l8_.country AS country_28, l8_.city AS city_29, l8_.route AS route_30, g9_.id AS id_31, g9_.lat AS lat_32, g9_.lng AS lng_33, l4_.locale AS locale_34, u7_.position AS position_35, l1_.locale AS locale_36, l0_.status AS status_37, l0_.createdAt AS createdAt_38 FROM listing l0_ LEFT JOIN listing_translation l1_ ON l0_.id = l1_.translatable_id LEFT JOIN listing_listing_category l2_ ON l0_.id = l2_.listing_id LEFT JOIN listing_category l3_ ON l2_.listing_category_id = l3_.id LEFT JOIN listing_category_translation l4_ ON l3_.id = l4_.translatable_id AND (l4_.locale = ?) LEFT JOIN listing_image l5_ ON l0_.id = l5_.listing_id LEFT JOIN `user` u6_ ON l0_.user_id = u6_.id LEFT JOIN user_image u7_ ON u6_.id = u7_.user_id AND (u7_.position = 1) LEFT JOIN listing_location l8_ ON l0_.location_id = l8_.id LEFT JOIN geo_coordinate g9_ ON l8_.coordinate_id = g9_.id WHERE l1_.locale = ? AND l0_.status = ? ORDER BY l5_.position asc, u7_.position asc) dctrn_result ORDER BY createdAt_6 DESC LIMIT 6' with params ["en", "en", 2]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cocorico_dev.listing' doesn't exist

Please help me

**Comment by cocolabssas** [comment]
Hello @Rituparna007,

You seem to forgot to execute somme commands : https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md#sql-database-initialisation

**Comment by Rituparna007** [comment]
Thank you .Its working now. But another issue having when login into admin panel with the given user credential in installation document then its showing "Invalid Credential". Please help

**Comment by cocolabssas** [comment]
Could you confirm that the credentials you used are  : super-admin@cocorico.rocks / super-admin

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
