### ISSUE TITLE
problem cocorico installation

### ISSUE THREAD

**Issue by pacific-webdesign** [Cocolabs-SAS/cocorico#398]
Hi, 
when i want install cocorico, i have this problem : [screenshot image](https://i.postimg.cc/Qt0Z6p2w/Screenshot-2019-4-24-Symfony-Configuration-Checker.png).
Do you say why ?

thank you in advance.
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

**Comment by cocolabssas** [comment]
Hi,

It seems that your config.php file is not interpreted by PHP. Could you ensure that your have PHP enabled?

**Comment by cocolabssas** [comment]
We close it as it seems there is no more activity on it. Feel free to reopen it if needed.
