### ISSUE TITLE
payment, front end and cocorico news

### ISSUE THREAD

**Issue by bdiagana** [Cocolabs-SAS/cocorico#399]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [x ]
| Support request? | [x ]

Hello,
1/ How can i set a methods payment like credit card with mangopay for example ?
2/ How can i customize front end in cocorico ?
3/ How change cocorico news ?
Thank you

**Comment by cocolabssas** [comment]
Hello,

> 1/ How can i set a methods payment like credit card with mangopay for example ?

You need to implement it. 

> 2/ How can i customize front end in cocorico ?

- CSS are in web/css folder : 
all.css
all-override.css
fullcalendar-override.css

- JS are in web/js folder:
common.js
date-time.js
jquery.main.js
jquery.main-override.js

- Twig templates are in Bundles "view" folder  and main layout is in app/views folder.

> 3/ How change cocorico news ?

You need to modify the  parameter `cocorico.home_rss_fee`d in file `src/Cocorico/CoreBundle/Resources/config/parameters.yml:14`

**Comment by bdiagana** [comment]
Great, thanks for your reply
