### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by numerogeek** [Cocolabs-SAS/cocorico#4]
Hey, 

As the requirements are pretty specific to this project, that would be nice to put  #it on docker.

**Comment by kroshp** [comment]
Good idea,

But this not a priority for now.
If you feel it, we would enjoy to see it on docker. 
We remain available if you need more informations.

Thanks

**Comment by npotier** [comment]
Hello @numerogeek @kroshp, we have created the ```Dockerfile``` and ```docker-compose.yml``` files in order to run Cocorico with Docker. You can see them here : [https://github.com/acseo/docker-cocorico](https://github.com/acseo/docker-cocorico)

Feel free to let us know what you think about it.

**Comment by cocolabssas** [comment]
@npotier Thanks a lot for this contribution. We will check this quickly and keep you informed.

**Comment by xpeering** [comment]
Hello @npotier !
I want to test your Cocorico with Docker installation, but I have one doubt:
Some modification / advice before to start with?
Thanks!

**Comment by adyassine** [comment]
I created this repository to run cocorico on Doker https://github.com/adyassine/cocorico-docker

**Comment by xpeering** [comment]
Thanks @adyassine ! I´ll ask to my dev partner to check this out!

**Comment by dailyhypervisor** [comment]
Does anyone have any scripts to install this package?  If not does anyone have any advice on where to start?  Linux distro , version, etc?  I would assume that someone is doing automated build testing on this and is so their must be some scripts that are being used to configure all the dependencies.  Anything would be greatly appreciated as following the installation documents is a bit tedious at this point.  Although I'm technical I'm not a developer and I would struggle to see how an average person would be able to consume this.

**Comment by La-Meche** [comment]
Hi @dailyhypervisor, have you tried Docker?

**Comment by dailyhypervisor** [comment]
@La-Meche no but I'm going to give it a go today.  I've seen two different solution one on docker hub and the other in a git repo.  Any recommendations on which one would be better.  It looks like the one on docker hub has php in a separate container, but the one one git does not.

**Comment by fakelefteye** [comment]
Hello, thank you I tried ACSEO docker but I'm new to Docker I don't understand how it really work can someone tell me the step by step to install and build this docker image ? 

when I do docker composer up I have this error : and there is nothing at line 42 of apache2.conf only comments...

cocorico-web         | DocumentRoot must be a directory
cocorico-web         | AH00526: Syntax error on line 42 of /etc/apache2/apache2.conf:


Thank you

**Comment by npotier** [comment]
Hi @fakelefteye, the [apache2.conf](https://github.com/acseo/docker-cocorico/blob/master/apache2.conf#L42) file at line 42 is not blank, it indicates the `DocumentRoot` folder, wich is `/var/www/html` 

In the Docker container, `/var/www/html` is a **volume** declared in the [docker-compose.yml](https://github.com/acseo/docker-cocorico/blob/master/docker-compose.yml), line 36. On your host machine, it's the **cocorico** folder.

On your host machine, are you sure to have this folder ? You can fetch it by cloning the repo : 

```bash
git clone https://github.com/Cocolabs-SAS/cocorico.git
```

Hope this helps.

**Comment by fakelefteye** [comment]
Thank you for your answer ; lets start from the start so that i dont get lost please ;)
I have launched a brand new blamk ubuntu 14 on aws .
What do I need first? shall I install lamp and then git cocorico
or do I just need to install docker and everything will be set up from docker ?

From your answer I think I need to first install apache lamp then clone cocorico then install docker-compose and do docker compose? 

Sorry I'm a newbie... I figured out the apache2.conf in your repo because I was going to /etc/apache2/apache2.conf inside a docker image like I said I'm completely lost...

Thank you

**Comment by fakelefteye** [comment]
Also I don't understand the cd /path/to/cocorico is that a random directory that I create or does it needs to be in the /var/www/html directory?
Thank you

**Comment by fakelefteye** [comment]
The error for DocumentRoot got resolved, I removed the /web then added it again and seems liek this error doesnt show.

now i keep having
cocorico-db-mongo exited with code 100
cocorico-web exited with code 1

**Comment by npotier** [comment]
@fakelefteye You have two cases : 
1) you want to use docker for test / dev purpose. I advise you to carrefully read 
 the README.md file in https://github.com/acseo/docker-cocorico. It provides a Dockerfile and step by step instructions to have a running cocorico instance.

2) you want to use cocorico on a server, for example your amazon instance. I advise you to read the official installation procedure located in this repo : https://github.com/Cocolabs-SAS/cocorico#installation

**Comment by mmshivukumar** [comment]
hi all can anyone help me out to install this project in local host.
 im new to symfony please

**Comment by npotier** [comment]
Hi @mmshivukumar this repository is about how to install **Cocorico** in an **Docker** environment.

I advise you to read the installlation process on the original repo here if you want to give a try to cocorico without Docker : https://github.com/Cocolabs-SAS/cocorico

**Comment by cocolabssas** [comment]
Hi everybody,

To simplify Cocorico installation we just published a new Docker installation for Cocorico PHP 7.1 compatible :  https://github.com/Cocolabs-SAS/cocorico-docker.
 
Enjoy!
