### ISSUE TITLE
cannot start config.php

### ISSUE THREAD

**Issue by comprateur** [Cocolabs-SAS/cocorico#40]
Hello, 
I've installed cocorico on a debian server (no gui) but I cannot start the config.php. 

The error is:
This script is only accessible from localhost.

-rwxr-xr-x 1 ludovic ludovic  8090 mai   14 08:15 config.php

Merci

**Comment by cocolabssas** [comment]
Hello,

This is the Symfony default behavior: For security reasons you can access to this file only from localhost.
If you look at the code of the file you will find at the beginning  

```
if (!in_array(@$_SERVER['REMOTE_ADDR'], array(
    '127.0.0.1',
    '::1',
))) {
    header('HTTP/1.0 403 Forbidden');
    exit('This script is only accessible from localhost.');
}
```
You can add the IP Address from which you want to access to this file. For security reasons don't deploy this file to production.

**Comment by cocolabssas** [comment]
I close the issue as it is more related to support than to an issue.
Don't hesitate to create an issue if you find one.
Thanks.
