### ISSUE TITLE
Deploy prod - Rsync not found

### ISSUE THREAD

**Issue by enuelmorales-snoop** [Cocolabs-SAS/cocorico#400]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi! It happens to me that when deploying production with the command deploy that is in the doc it returns "rsync not found" I am using the image of Docker cocorico, I enter by sh to the container and run the deploy ... Anything idea?

The code is:

docker exec -i -t cocorico php bin/console project:deploy prodPHP Warning:  Version warning: Imagick was compiled against Image Magick version 1799 but version 1800 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Fake deploying on prod server with rsync --dry-run -azC --force --delete --progress -h --checksum --exclude-from="/cocorico/app/config/rsync_exclude.txt" -e "ssh -p 22" ./ fakeuser@fake.cocorico.prod:/fake/path command

START deploy
--------------------------------------------
ERR > sh: rsync: not found

END deploy
--------------------------------------------

This was a simulation, --go was not specified. Post deploy operation not run.
Run the command with --go for really copy the files to prod server

**Comment by cocolabssas** [comment]
HI @enuelmorales-snoop,

Indeed Cocorico Docker image does not allow rsync for now. We will inform you as soon as it will be available (maybe in June).

**Comment by cocolabssas** [comment]
Feel free to reopen it if needed
