### ISSUE TITLE
GUI - Setting up Cocorico 

### ISSUE THREAD

**Issue by guymco** [Cocolabs-SAS/cocorico#401]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Hello everyone,

1. Is it possible to set-up **Cocorico** without command lines? is there a Graphic User Interface to run the install (like wordpress manual install). 
2. Is there a video tutorial somewhere on the web that show the setting up of **Cocorico**? I could not find any on youtube...
3. Does the **cocorico-docker** have more installation issues than the **regular Cocorico** install?
4. Are there any **Cocorico** expert reasonably priced who can help me set-up the platform on my **VPS** server?

Thanks in advance,
- GM

**Comment by cocolabssas** [comment]
Hi @guymco,

> 1. Is it possible to set-up Cocorico without command lines? is there a Graphic User Interface to run the install (like wordpress manual install).

Good question but Cocorico does not have a web install process. We plan to add it but without having a precise date for now.

> 2. Is there a video tutorial somewhere on the web that show the setting up of Cocorico? I could not find any on youtube...

Again good question, but the answer is the same than the previous one. We plan to do it but without precise date for now. In the meanwhile if you use Cocorico Docker image or you follow the installation guide for Linux and you have minimum skill on Linux  / Docker you should be able to install it.  

> 3. Does the cocorico-docker have more installation issues than the regular Cocorico install?

There is no installation issues with Cocorico install if you follow the installation guide and if you have enough linux system management skill. But Cocorico Docker will help you to install more easily your LAMP env and your Cocorico app.

>  4. Are there any Cocorico expert reasonably priced who can help me set-up the platform on my VPS server?

It should be the case. To help you we are going to create a post centralizing this kind of demand.

Hope it helps!

**Comment by cocolabssas** [comment]
We close it as it seems there is no more activity on it. Feel free to reopen it if needed.
