### ISSUE TITLE
Multiple Item in One Booking

### ISSUE THREAD

**Issue by pacutezky** [Cocolabs-SAS/cocorico#404]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [YES ]
| Support request? | [ YES]

**Comment by pacutezky** [comment]
Can Cocorico bet setup to book an Event venue with additional items like catering menu?
Is it currently supported or a custom development is needed?

**Comment by cocolabssas** [comment]
Hi @pacutezky 

For now it needs a custom development.

**Comment by cocolabssas** [comment]
We close it as it seems there is no more activity on it. Feel free to reopen it if needed.
