### ISSUE TITLE
cocorico logs being written by root?

### ISSUE THREAD

**Issue by rkhyd** [Cocolabs-SAS/cocorico#407]
| Q                | A
| ---------------- | -----
| Bug report?      | [y]
| Feature request? | [ ]
| Support request? | [ ]

I installed cocorico yesterday and today it gave this error. The log file is owned by root! Shouldn't be owned by the apache user when its created?

![image](https://user-images.githubusercontent.com/15903310/58930123-d2436180-8777-11e9-8ec3-3a841dc5e54d.png)

**Comment by cocolabssas** [comment]
Hi @rkhyd,

Cocorico does not decide the user you choose to install it neither the user you choose to run it.
Your problem seems to be that root was the user used to install Cocorico.
Your project files and folders should indeed owned by an another user like apache one.

**Comment by cocolabssas** [comment]
We close it as it seems there is no more activity on it. Feel free to reopen it if needed.
