### ISSUE TITLE
Where in the google do I create a Browser API Key and Server API Key? 

### ISSUE THREAD

**Issue by Rex-am-I** [Cocolabs-SAS/cocorico#408]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x]

Where in the google do I create a Browser API Key and Server API Key?

**Comment by rkhyd** [comment]
hello Rex,
Please follow this guide to generate the keys.
https://www.iwdagency.com/help/dealer-store-locator/creation-of-server-api-keybrowser-api-key

**Comment by Rex-am-I** [comment]
Thanks so much for that prompt and useful advice!
