### ISSUE TITLE
tax management

### ISSUE THREAD

**Issue by aenyg** [Cocolabs-SAS/cocorico#409]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

Hello
I just started using the platform and I am trying to configure the taxes to support the Canadian market.
I mean there are different taxes - GST PST HST - and I did see only one level of configuration.
I am wondering if I missed anything to set them up.

could you please help me to understand if it can be set up by configuration or if this needs to be developed?

thank you
Y.

**Comment by cocolabssas** [comment]
Hi @aenyg,

Cocorico managed only one taxe rate for now you can configure  here src/Cocorico/CoreBundle/Resources/config/parameters.yml:54. 

This feature related to multiple tax rates need to be implemented.

**Comment by cocolabssas** [comment]
We close it as it seems there is no more activity on it. Feel free to reopen it if needed.
