### ISSUE TITLE
web page opening but without format

### ISSUE THREAD

**Issue by comprateur** [Cocolabs-SAS/cocorico#41]
After following the steps, I have successfully open the main page but I have no format (see printscreen)
<img width="1280" alt="screen shot 2017-05-17 at 04 17 19" src="https://cloud.githubusercontent.com/assets/19526536/26136113/4e690a24-3aba-11e7-9a8d-5474488a92e4.png">

thanks,

**Comment by comprateur** [comment]
Solved it was necessary to have a certificate for https.

**Comment by cocolabssas** [comment]
Thanks for your participation!

**Comment by fakelefteye** [comment]
For newbies like me I also had the problem in parameter.yml you have to change https://cocorico.dev to yourwebsite.com
