### ISSUE TITLE
Stuck on bin\start-mongodb.bat "C:\Program Files\MongoDB\data"

### ISSUE THREAD

**Issue by Rex-am-I** [Cocolabs-SAS/cocorico#410]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x ]

I am installing on Windows. I have installed Mongo, but I am getting stuck on this line:
bin\start-mongodb.bat "C:\Program Files\MongoDB\data"
"Windows cannot find mongod.exe...."
1. I navigated to the bin folder in my app folder where the start-mongodb.bat file is
2. changed "C:\Program Files\MongoDB\data" to "C:\Program Files\MongoDB\data", but I still got the same message.
2. changed "C:\Program Files\MongoDB\data" to "C:\Program Files\MongoDB\Server\4.0\data", but I still got the same message.

What am I doing wrong?

**Comment by Rituparna007** [comment]
I have installed it also and got mongod.exe under C:\Program Files\MongoDB\Server\4.0\bin. Will you please use this once and check whats happening? In data folder under 4.0 there is no mongod.exe.

**Comment by Rex-am-I** [comment]
It's under the bin folder, but I still got that error. Baffled. I subsequently installed MongoDB Compass, started that and, in the bin folder double clicked on the mogod.exe file. The question is, is this correct?
