### ISSUE TITLE
Attempted to call function "locale_get_region" from namespace "Cocorico\CoreBundle\Utils".

### ISSUE THREAD

**Issue by Rituparna007** [Cocolabs-SAS/cocorico#412]
Hello

I am getting this error. My front end home page is coming fine but when I am clicking on Publish Listing button getting this error.

Please help.

**Comment by cocolabssas** [comment]
Hi @Rituparna007 

Ad described in the install documentation you need to install and enable php-intl  extension.

**Comment by cocolabssas** [comment]
We close it as it seems there is no more activity on it. Feel free to reopen it if needed.
