### ISSUE TITLE
MySQL and MongoDB confusion for newbie

### ISSUE THREAD

**Issue by Rex-am-I** [Cocolabs-SAS/cocorico#413]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x]
Early on in the install process I created a mysql databse when I was prompted to do so. Which db's do I enter in the parameters.yaml.dist file? See part of this file below:

parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     cocorico_dev [IS THIS THE MYSQL DB NAME?]
    database_user:     cocorico_dev
    database_password: cocorico_dev

    #MongoDB
    mongodb_server: mongodb://localhost:27017
    mongodb_database_name: cocorico_dev [IS THIS THE MONGDB NAME?]

**Comment by Rex-am-I** [comment]
I settled on making the top part MySQL and the other MongoDB. We'll see...

**Comment by Rituparna007** [comment]
parameters:
database_host: 127.0.0.1
database_port: ~
database_name: cocorico_dev [Yes it is the MYSQL database name]
database_user: cocorico_dev
database_password: cocorico_dev

and

#MongoDB
mongodb_server: mongodb://localhost:27017
mongodb_database_name: cocorico_dev [Yes it is the MONGODB database name]
