### ISSUE TITLE
Access to cocorico.local/config.php is forbidden

### ISSUE THREAD

**Issue by Rex-am-I** [Cocolabs-SAS/cocorico#414]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x]

When I try to run http://cocorico.local/config.php , I get a "Access forbidden!" message. And running http://cocorico.local/ only gets me to the XAMPP landing page. Where did I go wrong?

This is the modification that I made to the http.conf file:
VirtualHost 127.0.0.1:80>
      ServerName cocorico.local
      ServerAlias cocorico.local

      #For multiple images uploads
      LimitRequestBody 240000000

      DocumentRoot /var/www/cocorico.local/Symfony/web
      <Directory /var/www/cocorico.local/Symfony/web>
          #For performance and security reasons we should not use htaccess in prod
          AllowOverride Indexes FileInfo AuthConfig
          Order Allow,Deny
          Allow from all
      </Directory>

I also made a change to the hosts file > 127.0.0.1      cocorico.local

**Comment by cocolabssas** [comment]
Hi @Rex-am-I 

Maybe you missed to rename, as described in the installation documentation, the web/.htaccess.dist to web/.htaccess.
But your error related to config.php make think that your IP is maybe not 127.0.0.1. You can check this here web/config.php:18.

**Comment by Rex-am-I** [comment]
I didn't miss the .htaccess renaming step. For good measure, I went and did it again.

And the IP in the web/config.php file is 127.0.0.1

I really need help on this one!

**Comment by cocolabssas** [comment]
Could you comment in config.php  the lines:
```

header('HTTP/1.0 403 Forbidden');
exit('This script is only accessible from localhost.');
```
And dump $_SERVER['REMOTE_ADDR'] .

**Comment by cocolabssas** [comment]
Feel free to reopen it needed
