### ISSUE TITLE
run cron

### ISSUE THREAD

**Issue by snoopgithub** [Cocolabs-SAS/cocorico#418]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ X]
| Support request? | [X ]

**Comment by cocolabssas** [comment]
Hi @snoopgithub 

Could you be more precise?

Thanks!

**Comment by snoopgithub** [comment]
Hello. We need to integrate a cocorico instance with an external billingo solution. The external billing solution is aaccesible by an API. We need to call this API with the reservations not billed yet in order to get billed. So, we are thinking about using something like a CRON which runs once a day. Is Cocorico prerpare for working with CRONs????

Thanks in advance
Greettings!

**Comment by cocolabssas** [comment]
Hello @snoopgithub,

You can of course use crons with Cocorico. You can find here https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/crons.md Cocorico commands executed by cron.

**Comment by cocolabssas** [comment]
Feel
