### ISSUE TITLE
Cocorico with SYMFONY 3.4 and PHP 7

### ISSUE THREAD

**Issue by xpeering** [Cocolabs-SAS/cocorico#42]
Somebody know or have some date idea when we can install Cocorico using SYMFONY 3.4 and PHP 7?
Thanks!

**Comment by fakelefteye** [comment]
Hello,
I don't understand how to install Cocorico as a CMS it seems that the instructions are for developers not simple users...
shall i just upload the files via filezilla? i did the whole installation process and it is not working...
Thank you

**Comment by fakelefteye** [comment]
I figured out how to install but my site cannot load css or images because cocorico.dev is not available...

**Comment by SOFRACS** [comment]
Hi @xpeering! Cocolabs are working on carrying Cocorico to PHP7 in the coming weeks in anticipation of the next Symfony LTS, expect a big update soon!

**Comment by cocolabssas** [comment]
Hi @fakelefteye 

i removed your comment because it didn't have any relation with the subject of its issue.
Please either create a new issue or participate to an existing one. 

Thanks,

**Comment by xpeering** [comment]
Thanks @SOFRACS! 
We'll be waiting for this big update.
