### ISSUE TITLE
Coco Docto, Wanted to Have recurrent booking

### ISSUE THREAD

**Issue by ArchTaqi** [Cocolabs-SAS/cocorico#420]
| Q                | A
| ---------------- | -----
| Feature request? | [X]

For Doctors, somtimes we need to make a recurrent booking/appoinment. 

1. Make daily appoinment from Time AA:AA to Time BB:BB i.e Daily appoinment from **27-06-2019 10:00 AM - 11:00 AM to 05-07-2019 10:00 AM - 11:00 AM** on **workdays**.

2. Weekly Appoinment from from **27-06-2019 10:00 AM - 11:00 AM to 05-07-2019 10:00 AM - 11:00 AM - Tue, Wed** only.

3. Bi-Weekly Appoinment from from **27-06-2019 10:00 AM - 11:00 AM to 05-07-2019 10:00 AM - 11:00 AM Tue, Wed** only.

**Comment by cocolabssas** [comment]
Hello @muhammadtaqi 

You can on Cocorico make recurrent bookings but for all days between start and end day.
Indeed it would be interesting to choose the days to which this recurrence applies.

Suggestion label has been added.
