### ISSUE TITLE
How can I install Cocorico in my linux web hosting through Cpanel? HELPME

### ISSUE THREAD

**Issue by isacoctopusg** [Cocolabs-SAS/cocorico#422]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

I have a Linux Web Hosting contracted, I want to know the steps to install Cocorico directly on my website from Cpanel.

**Comment by clementduveau** [comment]
Hi,

I am not an expert in cPanel but Cocorico need MongoDB which is not supported by cPanel. It is unlikely that Cocorico will be buildable on cPanel.

Regards
