### ISSUE TITLE
Problem with photos of Listings

### ISSUE THREAD

**Issue by bu11shift** [Cocolabs-SAS/cocorico#424]
| Q                | A
| ---------------- | -----
| Bug report?      | [x]
| Feature request? | [ ]
| Support request? | [x]

![изображение](https://user-images.githubusercontent.com/26028882/61962502-4f4dc300-afd2-11e9-9046-a5f6924d84ba.png)

I have a problem. Offerer Acc  Listings -> Edit -> Photos
PHP 7.2.20
Attempted to call an undefined method named "macro_imagesCollectionItem" of class "__TwigTemplate_66d964d16470f651ab0c76c6886d6085c89cf8d645279be31e156f08bd8a500c".

             

Do you know what could be the problem?     
Thank you.

**Comment by cocolabssas** [comment]
Hi @bu11shift 

This error does not exists in Cocorico. Could you compare this file src/Cocorico/CoreBundle/Resources/views/Form/fields_collection.html.twig with yours. 
It seems that this macro `{% macro imagesCollectionItem(child_form, allow_delete) %}` has disappeared from your code.

**Comment by imanalopher** [comment]
@bu11shift Try change PHP version to `php 7.1` , You are using `php 7.2`
