### ISSUE TITLE
Fee (from % to Fix amount)

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#427]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X ]

Hello experts, I am lookinf fr advice
Now in file parameters, I can take my fee from Offrerer/Asker as % from Listing Price, 
How can I switch to FIX fee (e.g. always 10$ from Asker and 20$ from Offrerer?
![image](https://user-images.githubusercontent.com/35894283/63020875-89a6d380-be9f-11e9-9eb0-57baf2c1167f.png)

**Comment by cocolabssas** [comment]
Hello,

This feature should be available in Q4 2019.
