### ISSUE TITLE
Unable to find file LiipImagineBundle

### ISSUE THREAD

**Issue by christoroy** [Cocolabs-SAS/cocorico#428]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

Hello,

I have a problem with the installation.
I followed this [link](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md) to install.
Finally, when I run the Base Url I getting this [error](https://prnt.sc/ovjtuw).
what should I do to fix this?
Thanks in Advance.

**Comment by MunirajM** [comment]
Hi, 

I am also having the same issue as below when trying to install the app on Ubuntu server. 

`Unable to find file "@LiipImagineBundle/Resources/config/routing.xml" in @LiipImagineBundle/Resources/config/routing.xml (which is being imported from "/var/www/html/Symfony/src/Cocorico/CoreBundle/Resources/config/routing.yml"). Make sure the "LiipImagineBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@LiipImagineBundle/Resources/config/routing.xml" is not empty.`

I am trying to install Cocorico with the below server specs,

PHP 7.1(with required extensions and drivers)
MongoDb 4.2.0
MySQL 5.7
Apache 2
2 GB RAM(2GB Swap Memory)

Any idea to fix this error?

**Comment by gabilanbrc** [comment]
I googled a little and assummed that needed to install liip/imagine-bundle, this is what I got

php.exe composer.phar require liip/imagine-bundle
Using version ^2.1 for liip/imagine-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Removal request for liip/imagine-bundle == 2.9999999.9999999.9999999-dev
    - Can only install one of: imagine/imagine[v0.7.1, 1.2.2].
    - Can only install one of: imagine/imagine[v0.7.1, 1.2.2].
    - Can only install one of: imagine/imagine[v0.7.1, 1.2.2].
    - liip/imagine-bundle 2.1.0 requires imagine/imagine ^0.7.1,<0.8 -> satisfiable by imagine/imagine[v0.7.1].
    - Installation request for liip/imagine-bundle ^2.1 -> satisfiable by liip/imagine-bundle[2.1.0, 2.x-dev].
    - Installation request for imagine/imagine (locked at 1.2.2) -> satisfiable by imagine/imagine[1.2.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by MunirajM** [comment]
Hi @gabilanbrc 

liip/imagine-bundle will be installed on our initial composer command and I dont think we need to install it again.

After some research, I found that the installed Imagine bundle on my server have routing.yaml and not the routing.xml(https://prnt.sc/p11hgu). You can also see the details from the below links,

https://symfony.com/doc/1.0/bundles/LiipImagineBundle/installation.html
https://symfony.com/doc/2.0/bundles/LiipImagineBundle/installation.html

You can try replacing `@LiipImagineBundle/Resources/config/routing.xml` with `@LiipImagineBundle/Resources/config/routing.yaml` on the file Symfony/src/Cocorico/CoreBundle/Resources/config/routing.yml to fix this issue.

**Comment by gabilanbrc** [comment]
Thanks @MunirajM , that seemed to work!


> Hi @gabilanbrc
> 
> liip/imagine-bundle will be installed on our initial composer command and I dont think we need to install it again.
> 
> After some research, I found that the installed Imagine bundle on my server have routing.yaml and not the routing.xml(https://prnt.sc/p11hgu). You can also see the details from the below links,
> 
> https://symfony.com/doc/1.0/bundles/LiipImagineBundle/installation.html
> https://symfony.com/doc/2.0/bundles/LiipImagineBundle/installation.html
> 
> You can try replacing `@LiipImagineBundle/Resources/config/routing.xml` with `@LiipImagineBundle/Resources/config/routing.yaml` on the file Symfony/src/Cocorico/CoreBundle/Resources/config/routing.yml to fix this issue.

**Comment by cocolabssas** [comment]
The issue seems coming from a composer update. This command should resolve the issue : 
`php composer.phar require liip/imagine-bundle:"^1.9"`
