### ISSUE TITLE
Facebook button 

### ISSUE THREAD

**Issue by bdiagana** [Cocolabs-SAS/cocorico#429]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x]
| Feature request? | [ ]
| Support request? | [ ]

![image](https://user-images.githubusercontent.com/34586367/63597108-febf8a80-c5bc-11e9-91ad-ee7dace78d5e.png)

I have this error when i click to the facebook button.

Thank you

**Comment by cocolabssas** [comment]
Hi @bdiagana,

The Facebook API has changed recently and is no more compatible with Cocorico.
For now we suggest you to hide the FB login button. 

Thanks
