### ISSUE TITLE
10GB in cache

### ISSUE THREAD

**Issue by gomonkey** [Cocolabs-SAS/cocorico#43]
I had over 10 GB cached, and no one exepted me visited the website.
 I think is a really big big problem

**Comment by cocolabssas** [comment]
If you are in production, indeed there is a problem from your side:
We know that for  cocorico websites in production, with many additional functionalities and visited by many people cache size are around 30MB. 
If you are in non production it is more normal although we never reached this size in non production environments.
If this big size create some problems you can investigate a little more what is growing in your cache folder and check this link to disable for example some debugging functionalities:
https://stackoverflow.com/questions/14938355/cache-folder-grown-very-very-fast
