### ISSUE TITLE
unable to login administrator account

### ISSUE THREAD

**Issue by christoroy** [Cocolabs-SAS/cocorico#430]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

After installing Cocorico I am facing the [issue](https://github.com/Cocolabs-SAS/cocorico/issues/428) the issue still persists.

And I am not able to log in admin [error](https://prnt.sc/oxihka)

I used the below credentials
super-admin@cocorico.rocks
super-admin

Let me know if anyone faced these issue.
Thanks in Advance.

**Comment by cocolabssas** [comment]
Did you load fixtures: See doc/installation-application.md:69 and

**Comment by imanalopher** [comment]
#Linux
`chmod 744 bin/init-db`
`./bin/init-db php --env=dev`

#Windows
`.\bin\init-db.bat --env=dev`
