### ISSUE TITLE
Attempted to load class "DeployBundle" from namespace "Hpatoio\DeployBundle"

### ISSUE THREAD

**Issue by damiencostocking** [Cocolabs-SAS/cocorico#431]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]
Bonjour,
J'arrive à déployer correctement cocorico avec une variable d'environnement égale à prod mais mais lorsque je renseigne dev, je rencontre le message suivant :

PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DeployBundle" from namespace "Hpatoio\DeployBundle".
2019-08-27T08:39:43+02:00 Did you forget a "use" statement for another namespace? in /data/bas/site/app/AppKernel.php:69

Comment puis-je régler ce problème ?

**Comment by cocolabssas** [comment]
Hi Damien,

DeployBundle works in dev and staging env not in prod env.
