### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by vins2k** [Cocolabs-SAS/cocorico#432]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [Mobile.App]
| Support request? | [ ]

How difficult is it to build a mobile app sharing the same marketplace site using Cocorico?
Thanks

**Comment by cocolabssas** [comment]
Hi @vins2k,

For that you will need to implement the whole API of cocorico. And this is not an easy task. We planned to implement the Cocorico API this year.
