### ISSUE TITLE
Issue - PHP Fatal error:  Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by gantispam** [Cocolabs-SAS/cocorico#433]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Reproduce :
* Do a fresh installation with php 7.1 or 7.2
* Show "Listing On" : http://mon-test.fr/en/listing/listing-one-265805713/show

Error : 
```
[Mon Sep 02 17:03:09.819239 2019] [php7:error] [pid 13798] [client 192.168.1.24:11263] PHP Fatal error:  Nesting level too deep - recursive dependency? in /var/www/my-app/var/cache/prod/twig/85/854c4c4047087a724899bb36242f506827b0758f54335e01a51ad11089c11521.php on line 347, referer: http://mon-test.fr/en/
```

Tried to disable Twig's cache and new error is : 
```
[Mon Sep 02 17:10:15.577505 2019] [php7:error] [pid 13797] [client 192.168.1.24:11698] PHP Fatal error:  Nesting level too deep - recursive dependency? in /var/www/my-app/vendor/twig/twig/lib/Twig/Environment.php(378) : eval()'d code on line 347
```

**Comment by cocolabssas** [comment]
Hi @gantispam 

Could you send the complete log of this error.

**Comment by imanalopher** [comment]
Hi @gantispam 
Could You run & show us:

`php -v`, `tail -f var/logs/{latest}.log`
