### ISSUE TITLE
Variable "form_helper" does not exist.

### ISSUE THREAD

**Issue by gabilanbrc** [Cocolabs-SAS/cocorico#437]
| Q                | A
| ---------------- | -----
| Bug report?      | ]
| Feature request? | [ ]
| Support request? | [[X ]
After installation (Windows 10, XAMPP), when editing any listing or category i get an error: Variable "form_helper" does not exist.
Attached you will see the screenshot

![image](https://user-images.githubusercontent.com/1634776/65376282-63c9d700-dc74-11e9-8d6f-38eeac62f1e1.png)

**Comment by cocolabssas** [comment]
It seems that you have updated your composer dependencies. What is your version of Sonata?
