### ISSUE TITLE
installed cocorico, login link doesn't work

### ISSUE THREAD

**Issue by moscolb** [Cocolabs-SAS/cocorico#439]
| Q | 
So I followed the windows installation step by step. i ended up downloading and installing cocorico directly in symfony. i set up a virtual host via WAMP (different folder from symfony).

but when i try to login to the administrator dashboard to actually access and use the platform using the links provided at the end of the tutorial (www.cocorico.dev or www.cocorico.local) none work. They all lead me to the same "This site can't be reached" message. Is Cocorico down or was I supposed to install Cocorico INSIDE the virtualhost? im new at this. thanks!

**Comment by rkhyd** [comment]
you will need to check your hosts file to see if the domains you have chosen to install are pointing to 127.0.0.1. 
Also, did you copy the virtualhosts file to the wamp's configuration file? Please paste the contents here if possible..

**Comment by moscolb** [comment]
@rkhyd 
the domain i chose- cocorico.local - is in my hosts file pointing towards 127.0.0.1 In internet explorer, cocorico.local points towards the symfony directory folder in which everything is installed. In google chrome, i have to write "cocorico.local.localhost" but then it still takes me to the same site - the symfony root folder where all the documents live. You can open all the documents but none are rendering. 

This is my vhosts file for wamp:
--------------------------------
<VirtualHost *:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot "${INSTALL_DIR}/www"
  <Directory "${INSTALL_DIR}/www/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>

<VirtualHost 127.0.0.1:80>
    ServerName cocorico.local
    ServerAlias cocorico.local
    DocumentRoot "C:/wamp64/www/cocorico_dev"
</VirtualHost>

-----------------------

The cocorico github repository was downloaded and installed in the folder mentioned document root above, in a subfolder named "symfony." So that the files live in the following path:
C: > wamp64 > www > cocorico_dev > symfony

and when I try cocorico.local in my browser, that takes me to the symfony directory where all the files live but cocorico.local/admin/dashboard (internet explorer) and cocorico.local.localhost/admin/dashboard (chrome) both pull up a page that says:

"Not Found
The requested URL /admin/dashboard was not found on this server."

**Comment by moscolb** [comment]
@rkhyd i should also mention that none of the files seem to work in a browser... even though they all work (i can open and read them and edit them) in my computer with a text editor. 

for example, the script config.php with the path:

cocorico.local/config.php

returns "The requested URL /config.php was not found on this server." even though the file exists in that root directory

**Comment by cocolabssas** [comment]
Hi @moscolb,

Did you do this : https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md#configure-project
