### ISSUE TITLE
Currency setting

### ISSUE THREAD

**Issue by deviprasad97** [Cocolabs-SAS/cocorico#44]
#Help Needed. I was able to install the site successfully but I am unable to change default currency
Second I want to have only one currency which file should I edit

**Comment by cocolabssas** [comment]
Hi @deviprasad97,

- To change the default currency, you have to change the parameter `cocorico.currency: EUR` in Cocorico/CoreBundle/Resources/config/parameters.yml

- To change the available currencies you have to change in the same file the parameters 'cocorico.currencies_for_lexik', 'cocorico.currencies', ' cocorico.currencies_string' by setting only the currency you want to keep.

**Comment by deviprasad97** [comment]
Thank you so much.
