### ISSUE TITLE
Missing key in "TranslatorManager.php:55" when publishing a new listing

### ISSUE THREAD

**Issue by nmateo** [Cocolabs-SAS/cocorico#441]
| Q                | A
| ---------------- | -----
| Bug report?      | []
| Feature request? | [ ]
| Support request? | [X ]
Another Cocorico bug that encounter our marketplace with the bought version of cocorico, not the demo.. "missing key" error right after anybody clicks on "publish your listing" to validate and publish a new listing..

![image](https://user-images.githubusercontent.com/9270970/66302052-87d61b00-e8f8-11e9-87a8-26a0da6ce2cb.png)

**Comment by cocolabssas** [comment]
Hello @nmateo,

It is not a bug. Your error said that you have an invalid translation key and more precisely that your translation key is empty.  Loot at the "Installation documentation > [create services accounts](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/services-creation.md#create-your-microsoft-translator-account )" to know how to get your translator key. Then fill in the corresponding parameter  `cocorico_translation.translator.key` in your app/config/parameters.yml.

Hope it helps!
