### ISSUE TITLE
Loading failed for the script........

### ISSUE THREAD

**Issue by specks-zz** [Cocolabs-SAS/cocorico#445]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Hello.

I've installed cocorico in a virtual machine (VMware in my own server) with Ubuntu 18, i followed all the steps but when access the main page, i've get the following messages.

Loading failed for the <script> with source “https://cocorico.dev/js/compiled/all.js”. en:702:1
Loading failed for the <script> with source “https://cocorico.dev/js/vendor/gmap-infobox.js”. en:723:1
Loading failed for the <script> with source “https://cocorico.dev/js/vendor/gmap-marker-clusterer.js”. en:726:1
Loading failed for the <script> with source “https://cocorico.dev/js/vendor/gmap-marker-with-label.js”. en:729:1
ReferenceError: handleUnauthorisedAjaxAccess is not defined
en:711:13
TypeError: window.cookieconsent is undefined
en:78:13
Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

![image](https://user-images.githubusercontent.com/1479414/67907927-44f61480-fb3f-11e9-9bce-85f8b5427414.png)

Maybe my virtual-host is wrong or maybe i need something else:

![image](https://user-images.githubusercontent.com/1479414/67908088-bd5cd580-fb3f-11e9-96ed-aadc035da671.png)

![image](https://user-images.githubusercontent.com/1479414/67908110-ce0d4b80-fb3f-11e9-9444-c71471d079d0.png)

I see that the scripts is being called from https://cocorico.dev but I don't know where to put that configuration. Do I need another virtual host?

If you need more information please tell me.

Regards.

**Comment by cocolabssas** [comment]
Hi @specks-zz,

Indeed you missed to set parameters while your installation. Look at this line : app/config/parameters.yml.dist:28 and put https://cocorico.local.

**Comment by specks-zz** [comment]
Thank's @cocolabssas, that's it.    My problem is solved.   Regards.
