### ISSUE TITLE
view the certified ad badge

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#447]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

what is the condition to display "certified ad", I would like to display it also in the ad page.

http://imgur.com/tdhNiqhl.png

Thanks :)

**Comment by cocolabssas** [comment]
Hi @gonzasylv,

You need to add this markup `src/Cocorico/CoreBundle/Resources/views/Frontend/Home/_high_rank.html.twig:50`  in the listing ad page

**Comment by gonzasylv** [comment]
its works, thank you ;)
