### ISSUE TITLE
Css not loaded and redirect always to https://cocorico.dev

### ISSUE THREAD

**Issue by rafaelvalerini** [Cocolabs-SAS/cocorico#448]
| Q                | A
| ---------------- | -----
| Bug report?      | [N ]
| Feature request? | [ N]
| Support request? | [Y ]

I am trying to execute the cocoric project.

I did all the procedures, but css doesn't load, when I call http://cocorico.local always redirected to domain https://cocorico.dev, and CSS not load.. but in the documentation is always used cocorico.local.

Following are my files:

Virtual Host cocorico.local.conf
```
<VirtualHost *:80>
        ServerName cocorico.local
        DocumentRoot /var/www/cocorico.local/Symfony/web

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```
The file .htaccess, I copied by .htaccess.dist

Can you help me with this problem?

Thanks

**Comment by gsanchez27** [comment]
what is the value set in this field "cocorico.assets_base_urls" on your parameters.yml? Try to set the value to https://cocorico.local

**Comment by rafaelvalerini** [comment]
Thanks!
