### ISSUE TITLE
Payplay Payment Gateway

### ISSUE THREAD

**Issue by deviprasad97** [Cocolabs-SAS/cocorico#45]
How can I integrate PayPal. Which Bundle should I use and how should I Integrate that with Cocorico. 
If I use MongoPay how can I integrate that, what files do I need to make changes to

**Comment by eshelf** [comment]
Hi @deviprasad97,

I see that you were trying to integrate Cocorico with JMS Payment Bundle, also with PayPal. 

Did you succeed? Wich solution did you use? I can't find any bundle compatible with Cocorico. Composer always find an incompatible bundle.

I hope you had success on this! If so, please help me on that.

Thanks in advance,

Gerson
