### ISSUE TITLE
new currency error save & time_zone error on booking

### ISSUE THREAD

**Issue by pablovilla4** [Cocolabs-SAS/cocorico#452]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x ]

Hello how are you? I'm having two problems, one with the currency exchange and the other with the time_zone, the
First problem was that I created a new currency adapter although it worked and it shows me the prices in ARS (Argentine pesos) when the reservation is saved it saves me a totally different value, and the second problem is with the reservation too, both users (the which reservation and the one that publishes) are in the same time_zone (America / Argentina / Mendoza) but at the time of confirming the reservation it shows me 3 more hours on the start date, there is some recommendation of how the correct step by step would be to make run this ??

The 3 hours difference corresponds to the difference between UTC and America / Argentina / Mendoza

I hope you understand the problem greetings!

**Comment by cocolabssas** [comment]
Hi and Happy new year @pablovilla4 !

Concerning your first problem you need to change the default currency in which prices will be stored : `src/Cocorico/CoreBundle/Resources/config/parameters.yml:26`

Concerning the second one you need to define the users default time zone  `cocorico.time_zone`  parameter here : `src/Cocorico/CoreBundle/Resources/config/parameters.yml:67` 

You also need to set the default PHP timezone to  UTC as described in the doc :  `doc/installation.md:67`

Hope it helps!

**Comment by pablovilla4** [comment]
Thanks I could make everything work
