### ISSUE TITLE
I need to create a Q&A page on my wesbite

### ISSUE THREAD

**Issue by Aisseissa** [Cocolabs-SAS/cocorico#454]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

- Hey everyone,
I'm new in this forum and i have a problem about the creation on my question and answer page. I don't know where I can add this page on my website. There is solution ? (I work on PHP)
-->

**Comment by cocolabssas** [comment]
Hi @Aisseissa 

Go to this admin page : https://cocorico-os.local/admin/page/list and login with the admin account specified here ; https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md#browsing-the-demo-application
