### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by pablovilla4** [Cocolabs-SAS/cocorico#457]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x]

Hello how are you? I have an error when deploying in production I followed these indications

https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/deployment.md

I don't have any error but on the server when entering it shows me a 404 error

I tried to copy the app.php file that was not copied with the rsync and also the .htaccess.prod.dist (I rename it to .htaccess) but I get a 500 error, is there a little more detailed guide on how to make the deployment in production ??

**Comment by cocolabssas** [comment]
Hi @pablovilla4,

could you look at your http server (eg: /var/log/apache2/) and application logs (var/logs) and send the corresponding 500 error messages.

**Comment by EconsultingWCU** [comment]
> Q	A
> Bug report?	[ ]
> Feature request?	[ ]
> Support request?	[x]
> Hello how are you? I have an error when deploying in production I followed these indications
> 
> https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/deployment.md
> 
> I don't have any error but on the server when entering it shows me a 404 error
> 
> I tried to copy the app.php file that was not copied with the rsync and also the .htaccess.prod.dist (I rename it to .htaccess) but I get a 500 error, is there a little more detailed guide on how to make the deployment in production ??

Did you get it working? I am facing a similar problem. I have an internal developer exp. with drupal but he does not manage to launch the basic setup of Cocorico based on the publicly available instructions.

**Comment by SchulzWill** [comment]
What error are you having, @EconsultingWCU ?

**Comment by pablovilla4** [comment]
Hello finally I deployed it manually copying the files like this in Symfony
https://symfony.com/doc/3.4/deployment.html

Thanks and regards!!!
