### ISSUE TITLE
listing price range calendar

### ISSUE THREAD

**Issue by gsanchez27** [Cocolabs-SAS/cocorico#458]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

Hello 

I am looking in the database table where is the price range of listing is stored, please see the picture below.
![Shot 009](https://user-images.githubusercontent.com/5301578/74940972-3bb1f000-542d-11ea-9cd6-3ca09b325846.png)

Also, how do I delete the price range created in the listing?

Thanks and regards
Gary

**Comment by cocolabssas** [comment]
Hi @gsanchez27 ,

The prices and availabilities are stored in mongodb.
As a developer you can use a  mongodb client (robo3t, ...) to delete them. As a user you can reinitialize them from UI as follow in your case:
- select day ranges : 25 - 29
- select time ranges 00:00 -> 23:45
- price : 22.

- select day ranges : 25 - 29
- select time ranges 23:45 -> 00:00
- price : 22.

FYI: We know that this feature need  to be improved.

Hope it helps!

**Comment by gsanchez27** [comment]
@cocolabssas, Thank you for your prompt response

![Shot 011](https://user-images.githubusercontent.com/5301578/74993841-44cfab00-5487-11ea-9c09-7010dc93bc3b.png)

So, even I didn't specify the mongodb server and database name it still uses mongoDB database for some of it functionality, is it correct?

I prefer to use MySQL,

is the mongoDB database file is located in this folder on the project?

![Shot 012](https://user-images.githubusercontent.com/5301578/74993961-aa239c00-5487-11ea-8085-0e6eda95fcfa.png)

Thanks again!

**Comment by gsanchez27** [comment]
Hello @cocolabssas 

Based from the screenshot of above comments "tmp/mongo" folder, can you help me what is the file I need to load in robo3t? also there is a mysql folder can you help me to understand what are this files and usage of them?

Thanks
Gary

**Comment by SchulzWill** [comment]
Hello @gsanchez27,
You will need to execute mongo as a service and then connect into it using your robo3t with a localhost connection.
You may follow this link to get it running: https://kb.objectrocket.com/mongo-db/how-to-setup-a-mongodb-database-in-robo-3t-344
