### ISSUE TITLE
Disable translation?

### ISSUE THREAD

**Issue by SajjaadSherif** [Cocolabs-SAS/cocorico#459]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x]

Hello

I would like to know if it is possible to disable translation and have cocorico operate only in English? 

Thanks and regards,
Sajjaad

**Comment by cocolabssas** [comment]
Hi @SajjaadSherif,

Yes you can do it by removing `fr` locale in `cocorico.locales` parameter here : 
src/Cocorico/CoreBundle/Resources/config/parameters.yml:21

```
cocorico.locales:
            - en
            - fr
```

**Comment by SchulzWill** [comment]
Hello @SajjaadSherif ,  the change above works :)
