### ISSUE TITLE
Facebook button

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#46]
Hello,
My facebook login works only on a mobile phone
What do I need to have to facebook button work on the Desktop PC?
I think I followed the instructions and created my facebook keys put them in parameters.yml

But when I click on the desktop on the facebook button nothing happens....

Thank you for your help

**Comment by cocolabssas** [comment]
Hello,

You can look at your browser notifications icons to see if the FB popin has not been blocked.
Furthermore  you can also look at the browser console to see if there are some JS messages telling that your FB app has not been correctly configured.

**Comment by fakelefteye** [comment]
Hello,

Thank you very much ; it was really silly I looked everywhere else but it wa actually I needed to put https://mysite.com/fr/oauth/fb-login and I had only https://www.mysite.com/fr/oauth/fb-login on the developer.facebook.com whitelist settings.

Hope this help someone in my situation

thank
