### ISSUE TITLE
Assets not loaded.

### ISSUE THREAD

**Issue by SchulzWill** [Cocolabs-SAS/cocorico#461]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [Y]

Hello there, 
I am using cocorico on Mac through MAMP. 
Until now, my configurations point to 127.0.0.1:8888 as the MAMP default host config.

Right now, I am unable to see any assets.

The following configuration is being used: 
` use_assetic_controller: false`
   ` cocorico.assets_base_urls: 'http://localhost:8888'`
  `  router.request_context.host: 'localhost'`
   ` router.request_context.scheme: http`
  `  router.request_context.base_url: '' `

Even using the configuration posted above, my assets keep sending me to cocorico.dev/

**Comment by SajjaadSherif** [comment]
If you are looking for a quick fix for testing then add cocorico.dev to your hosts file and associate it with your localhost IP (127.0.0.1). What have you set your environment to (--env=dev or --env=prod)? Have you added those configurations to both parameters.yml and parameters.yml.dist within the /Symfony/app/config folder?

**Comment by SchulzWill** [comment]
Hello there!
I have set my environment to dev and I have already changed on both parameters.yml files.
Even changing the hostname gives me errors.
I am using NGNIX with the following configuration:

location / {
			# try to serve file directly, fallback to app.php
			try_files $uri /app.php$is_args$args;
		}
		# DEV
		# This rule should only be placed on your development environment
		# In production, don't include this and don't deploy app_dev.php or config.php
		location ~ ^/(app_dev|config)\.php(/|$) {
			fastcgi_pass unix:/Applications/MAMP/Library/logs/fastcgi/nginxFastCGI.sock;
			fastcgi_split_path_info ^(.+\.php)(/.*)$;
			include fastcgi_params;
			# When you are using symlinks to link the document root to the
			# current version of your application, you should pass the real
			# application path instead of the path to the symlink to PHP
			# FPM.
			# Otherwise, PHP's OPcache may not properly detect changes to
			# your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
			# for more information).
			fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
			fastcgi_param DOCUMENT_ROOT $realpath_root;
		}

**Comment by SajjaadSherif** [comment]
when you update all.css in /Symfony/web/css it saves to all_all_1.css in /Symfony/web/css/compiled. If the changes you are making to the all.css file is not reflecting on your install; Make sure you dump static assets using "php bin/console assetic:dump --env=dev" while in the /Symfony folder, and clear cache & reload the web page in your browser.

**Comment by SchulzWill** [comment]
I did not change the css files yet, they were not visible.
I was able to solve it removing the entire folder and re-doing the installation process on my laptop.
