### ISSUE TITLE
How to change the default interface

### ISSUE THREAD

**Issue by SchulzWill** [Cocolabs-SAS/cocorico#462]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X ]

Hello there!
I am new with Symfony and twig, and for that reason, I would like to understand the best way to change the interface that came with the default installation and if there is any appliable theme to it.
Thank you :)

**Comment by cocolabssas** [comment]
Hi @SchulzWill,

You will need to modify:
- twig templates : src/Cocorico/XXXBundle/Resources/views
Most of them are in src/Cocorico/CoreBundle/Resources/views and the main layout is here app/Resources/views/base.html.twig

- css : web/css/*.css

- js : web/js/*.js
