### ISSUE TITLE
Parameters and configurations

### ISSUE THREAD

**Issue by SchulzWill** [Cocolabs-SAS/cocorico#463]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

I have changed the parameters inside these files:
app/config/parameters.yml.dist
src/Cocorico/CoreBundle/Resources/config/parameters.yml
app/config/parameters.yml

And I am not able to see some parameters taking effect on my site. 
The main parameters are:
cocorico.site_name
cocorico.phone
cocorico.address

**Comment by SajjaadSherif** [comment]
Have you tried to restart your server after making the changes?

**Comment by SchulzWill** [comment]
Yes.
I have tried removing the cache and even cleaning and reinstalling all the sources again.

**Comment by SchulzWill** [comment]
Well, the clear cache command is not working properly, so this was happening because of it.
When i deleted the /cache content, everything worked.

**Comment by SchulzWill** [comment]
Now, I still have the home.meta_title showing up in front of the app name...
`{{ 'home.meta_title'|trans({}, 'cocorico_meta') ~ " - " ~ cocorico_site_name }}`

**Comment by SajjaadSherif** [comment]
replacing
`{{ 'home.meta_title'|trans({}, 'cocorico_meta') ~ " - " ~ cocorico_site_name }}`
with 
`{{ cocorico_site_name }}`
should work.

**Comment by SchulzWill** [comment]
That did the trick!
