### ISSUE TITLE
CocoricoElasticsearchBundle

### ISSUE THREAD

**Issue by SajjaadSherif** [Cocolabs-SAS/cocorico#464]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x]

Hi,

Where can be CocoricoElasticsearchBundle be found?

`{% if bundleExist('CocoricoElasticsearchBundle') %}
           {% include '@CocoricoElasticsearch/_form_keywords.html.twig' %}
 {% endif %} `

Kind regards,
Sajjaad Sherif

**Comment by cocolabssas** [comment]
Hi @SajjaadSherif,

This bundle is not public for now.
