### ISSUE TITLE
Create additional admin(super-admins) users from admin dashboard

### ISSUE THREAD

**Issue by SajjaadSherif** [Cocolabs-SAS/cocorico#465]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x]

Hello

I would like to know if it possible to create additional admin users from the super-admin dashboard or do I have to create the user in the FOSuserbundle cli?

Thanks in advance
Sajjaad Sherif

**Comment by cocolabssas** [comment]
Hi @SajjaadSherif,

You can not create user from super-admin dashboard. What you can do is to register a new user then add `ROLE_SUPER_ADMIN` role in DB > table user > column roles.
