### ISSUE TITLE
MYSQL ERROR docker 

### ISSUE THREAD

**Issue by Lyam** [Cocolabs-SAS/cocorico#467]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x]

Hello, 
I have a erreur when im trying the run the docker : 
ConnectionException
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

weirdly the mysql doesnt stay up..

**Comment by SajjaadSherif** [comment]
Have you used the command:
`docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/data/db -e HOST_UID=$UID cocolabs/cocorico`
to start the container?

**Comment by Lyam** [comment]
Yes i did. but the mysql doesnt seem to be launch.

**Comment by SajjaadSherif** [comment]
What operating system are you using?

**Comment by Lyam** [comment]
Mac OS using the last version of docker and php 7@3 on the OS.

**Comment by SajjaadSherif** [comment]
Try running it in a linux (ubuntu 18.04 is the OS use it on) VM. The docker image was created to operate on Linux. (side note: I believe you will need to use php7.1 when installing the application (from master)).

**Comment by Lyam** [comment]
Great! it's working with no issue on a Ubuntu18.04 VM. Thank you!

**Comment by SajjaadSherif** [comment]
My pleasure. Please close the issue now that it has been resolved.

**Comment by cocolabssas** [comment]
Thanks for this help!
