### ISSUE TITLE
Instructions on running the app locally and customize it

### ISSUE THREAD

**Issue by gopala000** [Cocolabs-SAS/cocorico#468]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

I found cocorico as an awesome platform to deploy a coaching service. But, I don't see any "How To" guide to get started. Questions I have are:

1. Will this app run on Windows 10 box (my dev machine)?
2. What are the pre-requisite steps and software installation required?
3. How do I build and deploy locally? I saw some stackoverflow post to use docker deployment. Will the build create docker image? How do I deploy to Azure cloud?
4. How do I customize for my requirements? I'd like to customize like you have done for the demo app. 
5. Is the demo apps available in the github for reference?
6. I'm located in US. If I want to use Stripe/paypal  for payment processing, how do I go about doing it?
7. If I have to build an Android and iPhone app, how do I go about using the web app developed using cocorico?
8. If I want to validate identity of the buyer of service by checking against some driver's license db, are there hooks to do it?

Appreciate if you can provide guidance on this. Thanks

**Comment by SchulzWill** [comment]
Hello gopala... I'll try to help you:
1) If you have XAMP/WAMP running on your machine, it will work. You'll only have to set the right ports to the parameters.yml
2) You'll need php, mysql and mongodb to start it.
3)No docker image is created directly by this repo. You will need to clone the https://github.com/Cocolabs-SAS/cocorico-docker and perform some work to make it running.
4)You'll need PHP Symfony knowledge to do that.
5)Nope.
6) Good question for @cocolabssas 
7) Use a PWA to do that, you'll be able to run it fastly and smoothly without any major developments.
8) You'll need to code it on your own.
