### ISSUE TITLE
Does the open source version have Mangopay installed?

### ISSUE THREAD

**Issue by ojsimon** [Cocolabs-SAS/cocorico#47]
Hi, 

Does the open source version have Mangopay API installed?

Does anyone have the opensource version setup?

Thanks

**Comment by deviprasad97** [comment]
No the open source is missing MongoPay Bundle. And has no documentation on how to do that either

**Comment by ojsimon** [comment]
@deviprasad97 Is there no way to obtain the MangoPay Bundle?

**Comment by deviprasad97** [comment]
You will get MongoPay bundle check out this https://github.com/Mangopay/mangopay2-php-sdk
try searching MongoPay Bundle on Google. After you find one you have to perform the installation and configure your project to use that bundle

**Comment by ojsimon** [comment]
@deviprasad97 How difficult would this be? My PHP and coding skills are incredibly limited. Has anyone already done this?

**Comment by cocolabssas** [comment]
I suggest you to make this task by a confirmed Symfony / Mangopay developer.
