### ISSUE TITLE
(Support request) Does Cocorico support any payment platform by default? 

### ISSUE THREAD

**Issue by BartolucciCarlos88** [Cocolabs-SAS/cocorico#475]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ X]

Does Cocorico support any payment platform by default? Because according what I have read is that I would have to code always to accept any payment platform, no?

Thank you

**Comment by cocolabssas** [comment]
Hi,
Cocorico OS for now has no public  payment solution and must be implemented by your own.

**Comment by Samuel17686** [comment]
Hello, 
"Cocorico OS for now has no public payment solution", does it mean you will add it one day? Anytime soon?

**Comment by cocolabssas** [comment]
Hello,
It is not decided but if we do it it will not be done before few months.
