### ISSUE TITLE
Issue while installing composer 

### ISSUE THREAD

**Issue by OthmanSefraoui** [Cocolabs-SAS/cocorico#477]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ ]

Hello i'm trying to install the composer but i have this error.
An error occurred when executing the "'cache:clear --no-warmup'" command:
In DocParser.php line 995:
  Notice: Trying to access array offset on value of type null
Any suggestion ?

**Comment by SchulzWill** [comment]
Hello there!
You should change the content of this line to:
`while ($this->lexer->lookahead!==null && $this->lexer->lookahead['position'] === ($this->lexer->token['position'] + strlen($this->lexer->token['value']))`

The full explanation to do that may be found on https://github.com/doctrine/annotations/issues/273

**Comment by OthmanSefraoui** [comment]
Thanks a lot. but i get this error if i change the content of the line   [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_NAMESPACE_S    
    EPARATOR, got '(' at position 25 in class Cocorico\CoreBundle\Document\List    
    ingAvailabilityTime.

**Comment by rubberduckyint** [comment]
getting this error, facebook info is filled out.  Not sure what would cause it.  The FB set up instructions seem to be a little different then current FB UI but we id enter Valid OAuth Redirect URIs.  Any help would be great.  Thanks


#Facebook
    cocorico.facebook.app_id: '26xxxxxxxxxxxxxxxxxx'
    cocorico.facebook.secret: '25eded44xxxxxxxxxxxxxxxxxxxxe'

In VariableNode.php line 85:
                                                                               
  The path "hwi_oauth.resource_owners.facebook.client_id" cannot contain an e  
  mpty value, but got null.

**Comment by cocolabssas** [comment]
Hello,

It can be related to your PHP version. For now Cocorico has been tested and works with php 7.1 and 7.2.

**Comment by OthmanSefraoui** [comment]
Thanks i fixed it by changing PHP version.
