### ISSUE TITLE
Should "app/SymfonyRequirements.php" really be in `.gitignnore`?

### ISSUE THREAD

**Issue by stashingly2020** [Cocolabs-SAS/cocorico#478]
| Q                | A
| ---------------- | -----
| Bug report?      | [x]
| Feature request? | [ ]
| Support request? | [ ]

When I run `php bin/symfony_requirements` (following the directions on https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md), I see that it looks at `app/SymfonyRequirements.php` but this is not a file that I have access to because it's in `.gitignore`? Was ignoring it a mistake or did I miss something?

**Comment by cocolabssas** [comment]
Have you some issue to run `php bin/symfony_requirements`?
Because SymfonyRequirements.php is now in var folder and is also in gitgnored folder.
This file should not be versionned.
Do you have a var folder ?

**Comment by stashingly2020** [comment]
Hmm I did have some problem but now I don't. I see that that file is in `var` which I have.
