### ISSUE TITLE
How to easily change who-we-are to about-us

### ISSUE THREAD

**Issue by stashingly2020** [Cocolabs-SAS/cocorico#479]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x]

I spent a lot of time tracking down all instances of who-we-are only to figure out that it's not as easy as replacing all occurrences of that text (e.g. with `sed`), but I also had to go and issue an UPDATE command for table page_translation (`UPDATE page_translation SET slug="about-us" WHERE slug="who-we-are"`). I don't really understand why the database is involved but is there an automatic way to update the pages in the database?

**Comment by cocolabssas** [comment]
One way to do it will be to have a dynamic footer / menus system generator. But the functionality is not a priority for now.
