### ISSUE TITLE
Characteristic form doesn't work

### ISSUE THREAD

**Issue by marcis** [Cocolabs-SAS/cocorico#481]
| Q                | A
| ---------------- | -----
| Bug report?      | [ X]
| Feature request? | [ ]
| Support request? | [ ]

Can't add or edit Characteristics due to JS Error (see screenshot)

![image](https://user-images.githubusercontent.com/609029/80861330-47603500-8c6e-11ea-92cf-e907cb26cbdf.png)

Can't select type nor group

**Comment by cocolabssas** [comment]
It seems that you updated your  dependencies. Revert your composer.lock to its original version https://github.com/Cocolabs-SAS/cocorico/blob/master/composer.lock  and execute composer install.
