### ISSUE TITLE
composer install errors

### ISSUE THREAD

**Issue by Samuel17686** [Cocolabs-SAS/cocorico#482]
| Q                | A
| ---------------- | -----
| Bug report?      | [  ]
| Feature request? | [  ]
| Support request? | [ x]

Hello

I have these errors when I install the dependencies with composer.

Problem 1
    - Installation request for doctrine/mongodb 1.2.2 -> satisfiable by doctrine/mongodb[1.2.2].
    - doctrine/mongodb 1.2.2 requires ext-mongo ^1.2.12 -> the requested PHP extension mongo is missing from your system.
  Problem 2
    - doctrine/mongodb 1.2.2 requires ext-mongo ^1.2.12 -> the requested PHP extension mongo is missing from your system.
    - doctrine/mongodb-odm 1.0.5 requires doctrine/mongodb ~1.2 -> satisfiable by doctrine/mongodb[1.2.2].
    - Installation request for doctrine/mongodb-odm 1.0.5 -> satisfiable by doctrine/mongodb-odm[1.0.5].

I have mongo installed and php mongodb extension.

PHP version => 7.3.1
MongoDB extension version => 1.7.4

**Comment by SchulzWill** [comment]
Hello Samuel!
What is your OS?
You may see if the installed libs are being loaded by the php version you are running. Execute the command to identify where your php are being loaded.
`which php`

**Comment by Samuel17686** [comment]
Hello,

Thank you for your answer. I'm using macOS and it runs php using MAMP:
`/Applications/MAMP/bin/php/php7.3.1/bin/php`

**Comment by Samuel17686** [comment]
My bad, because I forked cocorico long time ago, I have downloaded cocorico V0.3.4, I just tried with the last version and everything work fine.
