### ISSUE TITLE
API Facebook

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#483]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas 

I think I have created my oauth etc, but I have an error that appears when I try to identify myself with facebook: http://imgur.com/wR8hbyMl.png / http://imgur.com/R3aQ7vfl.png

When I set the path to my curl.cainfo : curl.cainfo = "/etc/ssl/certs/ca-certificates.crt"

http://imgur.com/GYUfgQHl.png / http://imgur.com/Ski6TeTl.png

An idea ?

**Comment by gonzasylv** [comment]
I think the API must have changed, here is my correction:

```
  $Linkfb = $responseArray['link'] ?? '';
  $Verifiedfb = $responseArray['verified'] ?? '';
  $Genderfb = $responseArray['gender'] ?? '';
  $Localefb = $responseArray['locale'] ?? '';
  $Timezonefb = $responseArray['timezone'] ?? '';
  $MotherTonguefb = $responseArray['locale'] ?? '';
```

dans src/Cocorico/UserBundle/Model/UserManager.php

**Comment by cocolabssas** [comment]
Thanks for this feedback.
