### ISSUE TITLE
sh: can't open '/entrypoint.sh': Permission denied

### ISSUE THREAD

**Issue by rakibulinux** [Cocolabs-SAS/cocorico#489]
When I run this command "`docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/data/db -e HOST_UID=$UID cocolabs/cocorico`" it's show me **sh: can't open '/entrypoint.sh': Permission denied** Can you please help me to solve this problem.

**Comment by Kakise** [comment]
The problem is with the docker scripts, the scripts file permission are 644 so they are not executable by default.

This pull request fixes the problem for me (macOS & Ubuntu LTS)
> https://github.com/Cocolabs-SAS/cocorico-docker/pull/38
