### ISSUE TITLE
install platform video 

### ISSUE THREAD

**Issue by saad-elalfy** [Cocolabs-SAS/cocorico#490]
hello 
now my server ready to install platform but i don't know how can i open the platform to counties the install steps 
if there are video will be more than easier

**Comment by cocolabssas** [comment]
Hello @saad-elalfy ,

We don't have video for now. We will try to add some video guide asap. In the meantime you can look at the install doc : https://github.com/Cocolabs-SAS/cocorico/tree/master/doc
