### ISSUE TITLE
Error sql emoji

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#491]
| Q                | A
| ---------------- | -----
| Bug report?      | [ x ]
| Feature request? | [ ]
| Support request? | [ ]

hi @cocolabssas,

I just discovered an error when we put an emoji in a field like the description, we receive a sql error

Ex: hi 😘

http://imgur.com/TGBqRYjl.png

**Comment by cocolabssas** [comment]
Hi @gonzasylv,

It seems related to rdbms configuration and database app configuration.It seems that you should set all of them to utf8mb4.

It should help : https://symfony.com/doc/3.4/doctrine.html#a-simple-example-a-product

**Comment by gonzasylv** [comment]
its ok thanks
