### ISSUE TITLE
Is the github still maintained?

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#493]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hello,

Cocorico still maintains this github?

**Comment by cocolabssas** [comment]
Hello,

Yes of course. Many updates will coming soon.

**Comment by gonzasylv** [comment]
hi @cocolabssas ,

thank you for your answer, if you can look for my issues please, it would be nice, good luck to you :)

**Comment by cocolabssas** [comment]
Thanks!
We just answer to some of your issues ;)

**Comment by gonzasylv** [comment]
thanks @cocolabssas
