### ISSUE TITLE
disable address requirement for listing

### ISSUE THREAD

**Issue by gbelvedere** [Cocolabs-SAS/cocorico#495]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

Is it possible to allow some listing items to be "remote", meaning not having an address? 
thanks

**Comment by cocolabssas** [comment]
Hi @gbelvedere,

It is not an option for now.  But it is in our middle term Roadmap (Q4 2020 or Q1 2021).

**Comment by gbelvedere** [comment]
any tips for the development? I need it for a project and may be I can do a PR later if its ok with you

**Comment by androidtenerife** [comment]
Hi, @cocolabssas  i have problems  with the adresses validation. Not recognize the real address. The message is 
![image](https://user-images.githubusercontent.com/23082375/86126303-fcc83100-bad5-11ea-8c12-545e08aa6a02.png)

**Comment by gbelvedere** [comment]
check in the logs if its giving you some error, also you need the google api key to make it work

**Comment by cocolabssas** [comment]
Hi @gbelvedere,

Look at your browser JS console, you should have an explicit error message.
