### ISSUE TITLE
Payment methods

### ISSUE THREAD

**Issue by androidtenerife** [Cocolabs-SAS/cocorico#496]
| Q          ?
| Feature request? | [x ]

Have you implemented some one method of payment.?

**Comment by rubberduckyint** [comment]
We wrote a new module for payments via stripe.  Let me know if you're interested

**Comment by woakes070048** [comment]
@rubberduckyint I would be interested

**Comment by shared-bmade** [comment]
@rubberduckyint I would be interested as well. Could you please provide me with extra information about how to get access to the module and how to use it? Thanks in advance!

**Comment by rubberduckyint** [comment]
Hi
looking into what it will take to package that code.  Currently its part of
our highly customized version


*David Jina*
CEO and Founder,
Rubber Ducky Interactive
<https://mailtrack.io/trace/link/dda63a16c206ebd8a5a5f3b1bf6119e681c00b0c?url=http%3A%2F%2Frubberduckyinteractive.com%2F&userId=808130&signature=ce66a9ebf49c7ce5>
310-765-4301 | M 310-902-3069 <310-902-3069>
*321 W Grand Ave
<https://mailtrack.io/trace/link/3ffe40d6b1abdce9ba34b3a3cdbd0f3cf80e6f54?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=7ac9b826f5ce4c2b>*
*El Segundo CA 90245
<https://mailtrack.io/trace/link/57fd1771b109384c427da36b5f727dead692ee1e?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=eadd1b766b5c36aa>*
<https://mailtrack.io/trace/link/bf2203b62695868f7f1af6c8afdd8d3e3816b85f?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fdavid-jina-302b7a64%2F&userId=808130&signature=074cee1a3ad720c1>

**Comment by rubberduckyint** [comment]
Hi
looking into what it will take to package that code.  Currently its part of
our highly customized version



*David Jina*
CEO and Founder,
Rubber Ducky Interactive
<https://mailtrack.io/trace/link/16b213f5ec6fec581b256f7781ff5219f4ff3c27?url=http%3A%2F%2Frubberduckyinteractive.com%2F&userId=808130&signature=726d559e708b36e4>
310-765-4301 | M 310-902-3069 <310-902-3069>
*321 W Grand Ave
<https://mailtrack.io/trace/link/f1792265022cc888a1cf1fb2d8757101e3662c26?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=b4e7f2ec40951632>*
*El Segundo CA 90245
<https://mailtrack.io/trace/link/33f28d1f75c27e1703f15fa996826deb5f1208e6?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=79222ec6c1f169e8>*
<https://mailtrack.io/trace/link/cff8d3f8508687bf2779f257489a96e3737de6af?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fdavid-jina-302b7a64%2F&userId=808130&signature=7dd36a220d49c0ef>

**Comment by rubberduckyint** [comment]
Spoke with our dev team.  The code is pretty integrated and would take a
decent amount of time to extract into a package we can share.  There are
two of you who are interested maybe you can split the cost.   My out of
pocket cost just paying for labor to extract and create a package would be
around $500.

Email me direct

David@rubberduckyinteractive.com



*David Jina*
CEO and Founder,
Rubber Ducky Interactive
<https://mailtrack.io/trace/link/2f95344b345f7f292166af19a3a1496685be4262?url=http%3A%2F%2Frubberduckyinteractive.com%2F&userId=808130&signature=0392f65ca6476555>
310-765-4301 | M 310-902-3069 <310-902-3069>
*321 W Grand Ave
<https://mailtrack.io/trace/link/500beb12fb56e365ab4b648036963a62bc8a68e9?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=731bee9798d39050>*
*El Segundo CA 90245
<https://mailtrack.io/trace/link/7509680c103155113542fb9fb8d60f9783f353bf?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=e0080b5d988f8fa9>*
<https://mailtrack.io/trace/link/fd83e4713903c9b7773e4ad86601cf651c81ae97?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fdavid-jina-302b7a64%2F&userId=808130&signature=42de5e36889e8a13>

**Comment by rubberduckyint** [comment]
We can provide a stripe package but would need to cover the cost of making it a package from our modified version.   If you are interested dm me or contact us through rubberduckyinteractive.com

**Comment by woakes070048** [comment]
@shared-bmade I would be interested in paying half of it. Are You?

**Comment by woakes070048** [comment]
@rubberduckyint I also emailed you and never got a response.

**Comment by rubberduckyint** [comment]
sorry must have missed it or went to junk.  Please email me again with the
subject "cocorico stripe"  I will look for that today

*David Jina*
CEO and Founder,
Rubber Ducky Interactive
<https://mailtrack.io/trace/link/5685cb06f88dafba9ade5585c7cad888a83184eb?url=http%3A%2F%2Frubberduckyinteractive.com%2F&userId=808130&signature=cc6a5a12e76789d0>
310-765-4301 | M 310-902-3069 <310-902-3069>
*321 W Grand Ave
<https://mailtrack.io/trace/link/44b3cc0d7bcb81ae6dfb843661fa63821b4bf100?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=d2a8afffe5fa342d>*
*El Segundo CA 90245
<https://mailtrack.io/trace/link/44b3cc0d7bcb81ae6dfb843661fa63821b4bf100?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=d2a8afffe5fa342d>*
<https://mailtrack.io/trace/link/c82e0952b25c83c55f93db823a0f388251085490?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fdavid-jina-302b7a64%2F&userId=808130&signature=eca55cd12389dcfb>

**Comment by shared-bmade** [comment]
Hi @woakes070048, @rubberduckyint: we are still interested in this module and will decide shortly (hopefully somewhere this week or next week) if we definitely want to. I will get back to you guys about it!

**Comment by shared-bmade** [comment]
Hi @woakes070048 @rubberduckyint: Sorry for the long radio silence. It's been busy at our office and the project where we wanted to implement this Stripe plugin for Cocorico was put on hold for a bit. We're still very interested in this plugin. Is it still available for the price mentioned before? And @woakes070048 are you still interested as well? 

Also i would like to know which payment options this module provides? Our client would like to use iDeal (Dutch), Creditcard payments and "Buy now, pay later" which Stripe provides with Klara. Are those options possible with this module?

Thanks in advance and i'm awaiting your repsonse

**Comment by rubberduckyint** [comment]
The catch is its not really a packaged plugin/module.  We needed to use
stripe so we wrote the code to do so but since it was just for our project
its not really packaged as a plugin.  In order to provide it as plugin, we
would have to convert it to such.   Our code currently only adds stripe as
that is what our project required.   Its just a basic credit card check out
no pay later.  We can write anything you need though.   I posted that if
anyone wants we can package it at cost.  If you want additional
functionality we can write that too and I can get you a quote once I have
full specs.



*David Jina*
CEO and Founder,
Rubber Ducky Interactive
<https://mailtrack.io/trace/link/364fc875f43914ba4a96f35fca7f6c6bc311b2f8?url=http%3A%2F%2Frubberduckyinteractive.com%2F&userId=808130&signature=1725659f53a6a668>
310-765-4301 | M 310-902-3069 <310-902-3069>
*321 W Grand Ave
<https://mailtrack.io/trace/link/1bce7f95313eb45c899f8de3b91fa5588d8f889c?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=3591bd1680033b3a>*
*El Segundo CA 90245
<https://mailtrack.io/trace/link/00299e90ad0746a96d3515624fa5b2cc23db8582?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=ecad457063d13b7f>*
<https://mailtrack.io/trace/link/1de9052edcdc63ba6aaf6ab05045c725ee5e9e99?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fdavid-jina-302b7a64%2F&userId=808130&signature=f1f45ce56908afc6>

**Comment by shared-bmade** [comment]
Hi David,

Thanks for your reply and the explanation. Could you please provide us with a quote to convert it into a plugin which supports the following payment options within Stripe:

-	iDeal via Bank redirects: https://stripe.com/docs/payments/bank-redirects
-	Creditcard via card payments: https://stripe.com/docs/payments/cards/overview
-	Direct debit via SEPA Direct Debit: https://stripe.com/docs/payments/sepa-debit
-	Buy now, pay later: https://stripe.com/docs/payments/buy-now-pay-later

Those our the payment options we would like to have in our project.  I hope you can get back to me quickly about it. 
And what would be the time estimate to build the plugin in?
Thanks in advance!

Eyal Beker

**Comment by rubberduckyint** [comment]
Sure, let me get you an estimate.  Please email me at
david@rubberduckyinteractive.com. The emails from git seem to end up in my
updates folder and I don't always catch them.



*David Jina*
CEO and Founder,
Rubber Ducky Interactive
<https://mailtrack.io/trace/link/2516c02d3cc1033fba3d5262e64303bb9a794185?url=http%3A%2F%2Frubberduckyinteractive.com%2F&userId=808130&signature=19be9a042dc04d8b>
310-765-4301 | M 310-902-3069 <310-902-3069>
*321 W Grand Ave
<https://mailtrack.io/trace/link/87859d802e88f0706e157e901500701671475c14?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=a4290aef14c40cde>*
*El Segundo CA 90245
<https://mailtrack.io/trace/link/eb1ed9bdeca80bc68f1899df3b830a58926593e2?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2F321%2BW%2BGrand%2BAve%2C%2BEl%2BSegundo%2C%2BCA%2B90245%2Fdata%3D!4m2!3m1!1s0x80c2b16baaa95f23%3A0x4950195b3dc88e6c%3Fsa%3DX%26ved%3D2ahUKEwjwjd3e8sLqAhXJHzQIHR8xA5gQ8gEwAHoECAsQAQ&userId=808130&signature=811e83da58dbb142>*
<https://mailtrack.io/trace/link/7c91c92d84c3bb2cc1cdf63c8d10e53abacd1bca?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fdavid-jina-302b7a64%2F&userId=808130&signature=04b3dc8bf52b994e>
