### ISSUE TITLE
translate into another language

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#497]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

I added a language :

```
    cocorico.locales:
            - fr
            - ma
    cocorico.locales_string: fr|ma
```
http://imgur.com/puHwiWAl.png 

`php bin/console translation:extract ma --config=cocorico && php bin/console cache:clear --env=prod`

I do not see my articles on the home page in the Moroccan language while the fr they are clearly visible

I duplicate the content of my xliff in FR by changing to .ma.xliff, and I change its content FR to MA to keep the same slug etc

but when I want to access a page like "comment ça marche?" I get an error: comment-ca-marche page not found.

**Comment by cocolabssas** [comment]
Hi @gonzasylv,

The content you are talking about is related to database content. You need to translate your listings  and users to MA and do the same for your pages in admin.

**Comment by gonzasylv** [comment]
I did not understand, how to do precisely

**Comment by cocolabssas** [comment]
Go to your admin app : http://your-domain.com/admin menu Site > page

**Comment by gonzasylv** [comment]
Thanks :)
