### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by m-root** [Cocolabs-SAS/cocorico#5]
Hello

I did try to installing and configure the app but to my surprise it couldn't work. Is there a thing I missed to get this error? 

Kindly view the link below and advise. 

 http://sushil-cocorico.rhcloud.com

**Comment by cocolabssas** [comment]
Bonjour,

Je suis absent du 11 avril au 14 avril inclus. Je prendrai  connaissance de votre message à mon retour.

Nos bureaux restent ouverts pendant mon absence.

Anthoni NOYON
SOFRACS
01 43 79 86 30

**Comment by SOFRACS** [comment]
Bonjour,

Je suis absent du 11 avril au 14 avril inclus. Je prendrai  connaissance de votre message à mon retour.

Nos bureaux restent ouverts pendant mon absence.

Anthoni NOYON
SOFRACS
01 43 79 86 30

**Comment by cocolabssas** [comment]
Hello,

We see only a 503 error page as description of the problem. 
It's not enough to know the cause of the issue.
Could you give us more informations like application logs.

Thanks

**Comment by m-root** [comment]
I managed to get around it. 

Thanks
