### ISSUE TITLE
How to change Time unit to days

### ISSUE THREAD

**Issue by deviprasad97** [Cocolabs-SAS/cocorico#50]
How to make booking price according to day

**Comment by cocolabssas** [comment]
Hi @deviprasad97 ,

You just have to set in Cocorico/CoreBundle/Resources/config/parameters.yml this parameter:
`cocorico.time_unit: 1440`

**Comment by deviprasad97** [comment]
Thank you it worked

**Comment by pruffier** [comment]
Is it possible to set for the user the option of hour or day? Both options?
Thank you!
