### ISSUE TITLE
keyword search module is missing.  

### ISSUE THREAD

**Issue by rubberduckyint** [Cocolabs-SAS/cocorico#507]
| Q                | A
| ---------------- | -----
| Bug report?      | [ y]
| Feature request? | [ ]
| Support request? | [ ]

I have installed the open source version.  The keyword search input field is missing.  I tracked it down to CocoricoElasticsearchBundle is either missing or broken.  Can you help?

**Comment by cocolabssas** [comment]
This bundle is not public for now.
