### ISSUE TITLE
Open source availability of demos

### ISSUE THREAD

**Issue by atlijohanns** [Cocolabs-SAS/cocorico#509]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi Cocorico, and thanks for a brilliant open source platform.

I was scrolling through your demos under https://www.cocorico.io/en/demo/ and was wondering what is needed to get the same look and functionality as in https://cocodev.demo.cocorico.io/ and https://cocodocto.demo.cocorico.io/ (Keywords, more smooth UI, etc.)

Does that require coding of my own or is it/will be available as open source?

Thank you in advance.

**Comment by cocolabssas** [comment]
Hi, 
Cocorico demos are based on Enterprise Edition which is a more advanced edition than the Community one. 
We plan to update the CE to a recent version of the EE in  a near future.

**Comment by rubberduckyint** [comment]
this is very misleading.  Provide a demo of the community edition.  We invested a lot of time on this product believing that the demo was CE but it was EE.  It would also be useful to list what features are included in the EE vs CE version here on GIT.
