### ISSUE TITLE
Quick assistance i have already deployed version now need to copy  

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#51]
I have already deployed this on my server and working fine, now I need one more copy of my existing project.For making a copy do I need the follow all these steps? or simply copy paste and change the configuration file and follow the Symfony guideline for making a copy from there - [link](https://symfony.com/doc/current/deployment.html#common-post-deployment-tasks)

**Comment by cocolabssas** [comment]
Hello, 

if by copying you mean  deploying your project on other servers you can either follow these steps :
https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Resources/doc/deployment.rst.
Or indeed use one of the different solutions of project deployment listed here : [How to Deploy a Symfony Application](https://symfony.com/doc/current/deployment.html)

You will need also to customize your http host configuration, and making some modifications on your app/config/parameters.yml files for specific environment configuration. 

Thanks,
