### ISSUE TITLE
Documentation of bundles

### ISSUE THREAD

**Issue by atlijohanns** [Cocolabs-SAS/cocorico#510]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi support.

I was wondering if you provide any documentation on function and usage of bundles that can be enabled under src\Cocorico\CoreBundle\Resources\config\parameters.yml?

- ListingOptionBundle
- ListingAlertBundle
- ListingCategoryFieldBundle
- ListingDepositBundle
- MangoPayCardSavingBundle

**Comment by cocolabssas** [comment]
Hi,

These bundles are not public for now.
