### ISSUE TITLE
Apc error

### ISSUE THREAD

**Issue by liemteksun** [Cocolabs-SAS/cocorico#513]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [x ]

I got this error when trying to access cocorico
2020/09/22 09:37:12 [error] 8859#8859: *39 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "apc_fetch" from namespace "Doctrine\Common\Cache". in /var/www/html/cocorico/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php:41
Stack trace:
#0 /var/www/html/cocorico/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(221): Doctrine\Common\Cache\ApcCache->doFetch('DoctrineNamespa...')
#1 /var/www/html/cocorico/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(194): Doctrine\Common\Cache\CacheProvider->getNamespaceVersion()
#2 /var/www/html/cocorico/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(79): Doctrine\Common\Cache\CacheProvider->getNamespacedId('Cocorico\\UserBu...')
#3 /var/www/html/cocorico/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Cache\CacheProvider->fetch('Cocorico\\UserBu...')
#4 /var/www/html/cocorico/vendor/doctrine/orm/lib/Do" while reading response header from upstream, client: 

I know this is related to apc not being installed and it has been replaced by apcu on php7, but I can't disable or use apcu or arraycache

I've tried to disabled apc on /var/www/html/cocorico/app/config/config_prod.yml

imports:
    - { resource: config.yml }
    - { resource: "@CocoricoCoreBundle/Resources/config/config_dev.yml"}

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        query_cache_driver: apc
#        result_cache_driver: apc

What else can I do to fix this issue?

thanks

**Comment by liemteksun** [comment]
It seems that I need to run
php bin/console cache:clear --no-warmup --env=dev

That's solved now

Silly question: 
how do I change the website password once I logged in?

thanks

**Comment by cocolabssas** [comment]
Hello @liemteksun,

Doctrine cache are used for prod env. A change for replacing apc by apcu has just been done here: https://github.com/Cocolabs-SAS/cocorico/commit/76f9313da046db7255b3a9f12d9b1d3cbb164c37

To change password user go to MyDashboard > Profile > Contact Information : /en/dashboard/user/edit-contact
