### ISSUE TITLE
Automated cron emails not setting links to the page inside the email's body

### ISSUE THREAD

**Issue by mv3ntur4** [Cocolabs-SAS/cocorico#515]
| Q                | A
| ---------------- | -----
| Bug report?      | [x ]
| Feature request? | [ ]
| Support request? | [ ]

Hi @cocolabssas,

It seems that the automated emails received from cron don't set their links, ie. when i click the links that are in the body's email they don't have any destination setup so it does not do anything, for example: I can click to the listing's link but it does not go to the page because the href property is empty, that only happends with the automated emails sent by cron.

You can run manually the cron job for example: 
php $instalation_path/Symfony/bin/console cocorico:bookings:alertExpiring --env=prod

Maybe I should add some environment variables to it?

Thank you in advance for your support.

**Comment by atlijohanns** [comment]
Don't know if I am understanding correctly but here are two pointers from me:

1. You can edit text sent by selecting cocoric_mail on <yoursite>/admin/__translations (See https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/translations.md).

2. If the links are not sending you to the right URL you need to edit cocorico.assets_base_urls to match your URL in app/config/parameters.yml.

**Comment by mv3ntur4** [comment]
Yes I did the parameters.yml set up and it worked Atli!

Thank you very much, I am going to close the ticket and if you let me i 
will give your solution and a reference to you.

Greetings!

**Comment by mv3ntur4** [comment]
This was my working setup:
    cocorico.assets_base_urls: 'http://yourdomain.com'
    router.request_context.host: 'yourdomain.com'
    router.request_context.scheme: 'http'                            
    router.request_context.base_url: ''
Thank you @atlijohanns
