### ISSUE TITLE
Booking hour plus one when creating a booking

### ISSUE THREAD

**Issue by mv3ntur4** [Cocolabs-SAS/cocorico#516]
| Q                | A
| ---------------- | -----
| Bug report?      | []
| Feature request? | [ ]
| Support request? | [x]

Hi @cocolabssas,

I have an issue with the booking hours in their creation, when I choose the hour and submit it it shows 1 hour ahead, instead of the hour given previously, later when I consult the booking created it gives you the hour set plus 1 hour, (in fact the automated email sent shows the set hour + 1), I have sent a javascript alert before it gets submitted and the hour it shows it's ok but when it redirects shows the booking with 1 hour ahead (I suppouse it has to do with javascript, maybe web/js/compiled/all.js). 

Resume:
From:
http://domain.com/fr/listing/listing-1778098317/show
Set hour to 14:00 hrs
When click "book now" it redirects to:
http://domain.com/fr/booking/1778098317/2020-10-02-15:00/2020-10-02-16:00/new

As you can see it shows 14:00 + 1 hour (2020-10-02-15:00)

Thank you in advance for your support

**Comment by cocolabssas** [comment]
Hi @mv3ntur4,

You need to set `date.timezone = UTC` in your php.ini for cli and http.

**Comment by mv3ntur4** [comment]
Excellent @cocolabssas it worked! Thank you very much!
