### ISSUE TITLE
microsofttranslator.com is no longer available token needed

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#52]
Hello,

when i open a listing and i try to change the language button it redirects me from  

https://mysite.com/fr/annonce/test

to

https://mysite.com/en/listing/test
 and give me this error

Cocorico\CoreBundle\Entity\Listing object not found.
ERROR - Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Cocorico\CoreBundle\Entity\Listing object not found." at /var/www/rent-a-kite.com/Symfony/src/Cocorico/CoreBundle/Request/ListingParamConverter.php line 75 

also i was not able to correctly configure apache2.conf with the sample give on the website
And by the way do I have to modify sites-available conf or apache2.conf ?
when i copy the sample i change cocorico.dev to my site but apache doesnt reload because apparently there is some error in the file...

Thank you for your help

**Comment by fakelefteye** [comment]
Also related : the new listings displayed on the front page  in English (Mysite.com/en) are not displayed in french (mysite.com/fr)
Thanks

**Comment by fakelefteye** [comment]
Ok I found out that if i dont fill out the other languages tab it will send a error but it will be best to fill the other tabs with the same language if they are not filled by the user...

now my problem is when i click on translate button at the  bottom of the listing i get this error : at ErrorHandler ->handleError ('8', 'Trying to get property of non-object', '/var/www/mysite.com/Symfony/src/Cocorico/CoreBundle/Model/Manager/TranslateManager.php', '116', array('clientId' => '4cmyidb9d0ece0542', 'clientSecret' => '961a4mysecretkey50b8a4', 'curlHandler' => 'Resource id #544', 'request' => 'grant_type=client_credentials&scope=http%3A%2F%2Fapi.microsofttranslator.com&client_id=4c27d2c09myide0542&client_secret=961a4mysecretkeya4', 'response' => false, 'responseObject' => null)) 
in src/Cocorico/CoreBundle/Model/Manager/TranslateManager.php at line 116  

Can someone help me? thank you

**Comment by fakelefteye** [comment]
Am I mistaken or the link microsofttranslator.com is no longer valid ?
now its  https://api.cognitive.microsoft.com/sts/v1.0/issueToken
so I changed this in CoreBundle parameter.yml but it still doesnt work

I also did this according to microsoft with no luck 
// Pass key using header
curl --header 'Ocp-Apim-Subscription-Key: <your-key>' --data "" 'https://api.cognitive.microsoft.com/sts/v1.0/issueToken'
// Pass key using query string parameter
curl --data "" 'https://api.cognitive.microsoft.com/sts/v1.0/issueToken?Subscription-Key=<your-key>'

It seems that there is some setup to do in symfony to make it work I am correct?

Thanks

**Comment by fakelefteye** [comment]
since April the 30th they moved to Azure : 
https://translatorbusiness.uservoice.com/knowledgebase/articles/1078534-action-required-before-april-30-2017-microsoft-t#code

Anyone knows how to modify the code?

thank you

**Comment by fakelefteye** [comment]
https://github.com/MicrosoftTranslator/HTTP-Code-Samples/blob/master/PHP/PHPAzureToken.php
I found this but I dont know how to do it

**Comment by cocolabssas** [comment]
Hello,

Indeed the ms translator service has been replaced by the new ms azure translator service.
This new service implementation will be added in a while.
In the meanwhile you can adjust the existing ms translator service implementation by the new one. The changes should be minor.
Or you can also disabled it until we add its new version. 
 
Thanks

**Comment by fakelefteye** [comment]
Thank you for your reply do you know approximately when the new version will be released?

**Comment by kroshp** [comment]
Hi,

We have just realized it :
https://github.com/Cocolabs-SAS/cocorico/commit/39960f0677870cb8212ff3b8e47819837a2b88f2

Enjoy :)

**Comment by fakelefteye** [comment]
Thanks a lot!!
 is there a git command to automatically update ? (without deleting everything ) or do i copy the files manually?
thanls

**Comment by cocolabssas** [comment]
Hi,

You can apply the patch of the corresponding commit:

1. Download the patch: 
https://github.com/Cocolabs-SAS/cocorico/commit/39960f0677870cb8212ff3b8e47819837a2b88f2.patch

2. Check and apply the patch:
```
git apply --check 39960f0677870cb8212ff3b8e47819837a2b88f2.patch
git am --signoff <  39960f0677870cb8212ff3b8e47819837a2b88f2.patch
```

If you forked this repository you can also sync it with your own by following these instructions : https://help.github.com/articles/syncing-a-fork/

Hope it helps
