### ISSUE TITLE
geo google place

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#521]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

I ask my question even if I see that the answers are very rare, can we make sure that when a user does a search in the geolocation part, he is provided with only cities, not streets, etc. .

Example: I look for "p" that returns "Paris" and all the cities of the country which have "p".

I'm talking about this field: http://imgur.com/tCBmANfl.png

Thanks :)

**Comment by cocolabssas** [comment]
Hi @gonzasylv,

Sorry for not having time to respond as quickly as you would like. In order for you to get your answers as quickly as possible, I recommend that you spend some time to look at the code in more depth to try to figure it out for yourself.

In the meantime, here are a few tips that may help you :
The configuration you need to modify can be found here: 
`src/Cocorico/GeoBundle/Resources/views/Common/js/_geocoding_js.html.twig:100`

Try to change this :
```
               autoComplete = new google.maps.places.Autocomplete(
                    autoCompleteElt,
                    {types: ['geocode']}
                );
```

To :
```
               autoComplete = new google.maps.places.Autocomplete(
                    autoCompleteElt,
                    {types: ['(cities)']}
                );
```
If you need more I recommend you to understand by yourself how google place autocomplete place restriction works  by looking to its documentation : https://developers.google.com/places/web-service/autocomplete

Hope it helps!

**Comment by gonzasylv** [comment]
Thanks @cocolabssas
