### ISSUE TITLE
form gets erased when user log in

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#53]
Hello,

The form to publish a listing is made so that we can fill the form first and login after ;
If I fill the form and login after the form gets reloaded and erased which is frustrating for a user, how can we solve this? thank you

**Comment by cocolabssas** [comment]
Hello,

Surprising, for now in the community edition the login form and the listing deposit form are in the same page. And you have to login / or register while publishing listing not after.
And after testing the form fields are not erased after login.
Maybe the problem is due to https://github.com/Cocolabs-SAS/cocorico/issues/52.

Furthermore the login / register process is being enhanced and will be added to the community edition in a while.

Thanks!

**Comment by fakelefteye** [comment]
Hello 
Thank you for your reply, yes I saw that on cocorico demo that when you click on publish the listing you are redirected to the login form

On my site it looks like this : 

![image](https://user-images.githubusercontent.com/5584130/28308706-5963133e-6ba7-11e7-9327-e1f68f15349c.png)

**Comment by kroshp** [comment]
Bonjour,

Mon adresse mail principale a changé, dorénavant veuillez me contacter sur arnaud.benatsou[at]cocolabs.io.

Arnaud Benatsou

------------------

Hi,

My main e-mail address has changed, from now on please contact me on arnaud.benatsou[at]cocolabs.io.

Arnaud Benatsou

**Comment by cocolabssas** [comment]
Bonjour,

Mon adresse mail principale a changé, dorénavant veuillez me contacter sur arnaud.benatsou[at]cocolabs.io.

Arnaud Benatsou

------------------

Hi,

My main e-mail address has changed, from now on please contact me on arnaud.benatsou[at]cocolabs.io.

Arnaud Benatsou

**Comment by BenjaminPE** [comment]
Bonjour,

Mon adresse mail principale a changé, dorénavant veuillez me contacter sur benjamin.perrault[at]cocolabs.io.

Benjamin Perrault

------------------

Hi,

My main e-mail address has changed, from now on please contact me on benjamin.perrault[at]cocolabs.io.

Benjamin Perrault

**Comment by kroshp** [comment]
Hello fakelefteye,

To resume and answer to your questions : 
> The form to publish a listing is made so that we can fill the form first and login after ;
This behaviour doesn't exist neither in CE neither in EE.

**Comment by fakelefteye** [comment]
Thank you
 I must have done something wrong at some point but I don't know where ...

**Comment by fakelefteye** [comment]
Actually I saw that it happens only with Facebook login, it appends _=_ at the end of the URL 
, reload the page and erase everything... with the "normal login" it doesn't happen ; the listing is published correctly.

**Comment by cocolabssas** [comment]
Indeed this bug has been identified. Until it is fixed i suggest you to disable FB login in listing deposit page  and new booking page,

**Comment by fakelefteye** [comment]
thank you

**Comment by fakelefteye** [comment]
hello,
I have found on stackoverflow that there is a workaround to it but I don't know in which page I have to put this script... could you tell me where ?
Thank you 

if (window.location.hash == '#_=_'){
    history.replaceState 
        ? history.replaceState(null, null, window.location.href.split('#')[0])
        : window.location.hash = '';
}

****Full version with step by step instructions****

// Test for the ugliness.
if (window.location.hash == '#_=_'){

    // Check if the browser supports history.replaceState.
    if (history.replaceState) {

        // Keep the exact URL up to the hash.
        var cleanHref = window.location.href.split('#')[0];

        // Replace the URL in the address bar without messing with the back button.
        history.replaceState(null, null, cleanHref);

    } else {

        // Well, you're on an old browser, we can get rid of the _=_ but not the #.
        window.location.hash = '';

    }

}

**Comment by cocolabssas** [comment]
I don't think it will resolve the problem. Please refer to my previous answer.

Thanks,
