### ISSUE TITLE
no emails sent

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#54]
Hello,

When I use the form to contact the user in community edition the user doesn't receive an email notification ; I've tried to setup gmail smtp in parameters.yml .

Is it normal that the user doesn't receive an email notification in CE or is my setup wrong in parameters.yml? 
I'm in dev mode . or is there another file to modify?

Thank you 

Lise

**Comment by cocolabssas** [comment]
Hello Lise,

In dev mode the emails send from the platform are stored in app/spool/default folder. No need to change parameters.yml.
Furthermore we will add in a few days a new bundle to read these emails in their HTML version from the web profiler.

**Comment by fakelefteye** [comment]
Ok i just had to clear the php cache in prod mode

thnak you

**Comment by cocolabssas** [comment]
Hello Lise,

As expected here is our new bundle to read emails from the web debug toolbar https://github.com/Cocolabs-SAS/CocoricoSwiftReaderBundle. 

Enjoy :)
