### ISSUE TITLE
Title not translated

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#55]
Hello, 
there are multiple pages where the title is not translated (I jthink this is JMS translation right?)
for exqmple when i click on a listing it shows in the pages title : 
listing.show.meta_title and several other pages do the same...
how can I solve this ? I saw the same on demo.cocorico.io

thank you

**Comment by kroshp** [comment]
Hello,

Yes it is related to Symfony and JMSTranslation Bundle.
Look at app/Resources/translations/cocorico_meta.xxx.xliff.
Or enable admin translation by setting `cocorico.admin_translation` parameter to `true `and then access translations page through your admin dashboard.
