### ISSUE TITLE
other languages / currencies

### ISSUE THREAD

**Issue by pruffier** [Cocolabs-SAS/cocorico#57]
hello,

how can I add other languages to the platform? and also new currency?

the config came without the super admin features, translation and seo. maybe something happened from my side.

thank you.

**Comment by kroshp** [comment]
Hi,

To add currencies and languages look into Cocorico/CoreBundle/Resources/config/parameters.yml and change the following parameters : 

    cocorico.locales:
    cocorico.locales_string:
    cocorico.currencies_for_lexik:
    cocorico.currencies:
    cocorico.currencies_string: 

For super admin go to : https://yourdomain/admin/login

**Comment by pruffier** [comment]
hello!

thanks @kroshp !

my super admin looks like this: all white, and no seo, translations options as in demo.

![cocorico](https://user-images.githubusercontent.com/30707486/28949744-4263f5a4-7895-11e7-8bba-2fb498ec7325.jpg)

thanks!

**Comment by pruffier** [comment]
more complete prnt screen.

![cocorico02](https://user-images.githubusercontent.com/30707486/28949811-98ee5630-7895-11e7-9247-6df0d1a8ea88.jpg)

**Comment by La-Meche** [comment]
Hi @pruffier, I get the feeling you went ont the Cocorico Enterprise Edition demo which includes some extra bundles not included in Cocorico (such as the advanced SEO bundle). The translations however are indeed included in the Cocorico Community Edition.

**Comment by pruffier** [comment]
The fields I marked in red, all of them are not available to the Community Edition? Or I had troubles coding it? My fault?

![cocorico03](https://user-images.githubusercontent.com/30707486/28977089-04bcb632-7917-11e7-89d2-91a5dcefb49b.jpg)

Best!

**Comment by fakelefteye** [comment]
for the SEO i dont know but for the translation tab you have to set 
  cocorico.admin: admin
    cocorico.admin_translation: true
in app/config/parameter.yml
and restart apache to see the translation tab

**Comment by pruffier** [comment]
@fakelefteye and the colored blocks from the admin panel (circled in red above)? And categories field/categories field groups/characteristics type?

Just to know if the work from my side was 100% correct. Will update the translation tab.

Thank you!

**Comment by cocolabssas** [comment]
@pruffier all functionalities you are talking about are in EE not in CE except for translations and groups/characteristics type which will be in the CE in a while.

**Comment by pruffier** [comment]
@cocolabssas great! thanks for the feedback.

is there any chance to buy the admin boxed panels to implement it? those boxes give important information to the marketplace. would be great!

**Comment by pruffier** [comment]
@cocolabssas great! thanks for the feedback.

is there any chance to buy the admin boxed panels to implement it? those boxes give important information to the marketplace. would be great!

**Comment by Atranaz** [comment]
@cocolabssas can we change the base currency or add more currency?
In my case, I only need one currency not multiple, Is that possible?

**Comment by cocolabssas** [comment]
@Atranaz Yes it is possible you can change the base currency and add more currencies.
You just have to change in Cocorico/CoreBundle/Resources/config/parameters.yml  the following parameters :
```
cocorico.locales:
cocorico.locales_string:
cocorico.currencies_for_lexik:
cocorico.currencies:
cocorico.currencies_string: 
```
