### ISSUE TITLE
Custom Characteristic type

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#58]
Hello,

I cannot find a way to change the Characteristic type in admin panel : 

There is Characteristic type : 

- Yes/No

- Quantity

- Custom_1

I cannot find a way customize the Custom_1 

Thank you

**Comment by fakelefteye** [comment]
up

**Comment by fakelefteye** [comment]
![image](https://user-images.githubusercontent.com/5584130/29916466-2b34b700-8e3f-11e7-9e08-e2dfb30064b0.png)

**Comment by cocolabssas** [comment]
Hi, 

The modification of characteristic type and value through admin is not available for now. It will be added in a while. In the meanwhile you can add them directly in DB.

**Comment by fakelefteye** [comment]
Sorry what is DB? Database?

**Comment by cocolabssas** [comment]
Yes
