### ISSUE TITLE
shared hosting

### ISSUE THREAD

**Issue by scriptologist** [Cocolabs-SAS/cocorico#59]
Hi,

I just to ask if anybody here tried cocorico on shared hosting and will it work.

Thanks.

Mark

**Comment by BourAbdelhadi** [comment]
Same question ! I hope we'll get an answer

**Comment by cocolabssas** [comment]
Hi, 

You can use cocrico on a shared hosting if your hosting provider have the installation requirements (https://github.com/Cocolabs-SAS/cocorico#installation) and a SSH access.

**Comment by typo3ua** [comment]
Excuse me, I do not found information about  "installation requirements". 
I want try install "cocorico" on shared host. 
Maybe do you have instruction (manual), how do it?
