### ISSUE TITLE
ListingAlertBundle and ListingCategoryFieldBundle

### ISSUE THREAD

**Issue by gonzinho** [Cocolabs-SAS/cocorico#60]
Hello, a have a cocorico environment installed and working but I want to add ListingAlertBundle and ListingCategoryFieldBundle. How can I get them? Thanks, Gonzalo

**Comment by cocolabssas** [comment]
Hi,

Contact Cocolabs to know how to get these bundles : http://www.cocolabs.io/en/contact-us/
