### ISSUE TITLE
problem with fee amount

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#64]
![image](https://user-images.githubusercontent.com/5584130/29869586-da55f0a8-8d83-11e7-9684-b22fd6e22283.png)

Hello, 
There is a problem with the fee amount : 
I could reproduce the error both on my install and on demo.cocorico.io : 
after booking a listing ; on the last page Total amount including fees adds 100 euros of fees! 

I changed the parameters.yml in src  with the fee as asker and as offerer to different values  but still adds 100euros as  a booking fee...

clear php cache , browser cache restart apache....

I also modified in mysite.com/admin : it works only with 0

In which format do we need to put the fee : 10% ; 10 ; 0.1 ?
same question in the parameters.yml which format do we need to write?

Do we need to change both parameters.yml and /admin for it to work?

I think it's a bug 

Thank you

**Comment by cocolabssas** [comment]
Hi,

Look into the Cocorico/CoreBundle/Resources/config/parameters.yml you will see the default values and format : ex for 10% it is 0.1.
This parameters are the default fees. But you can override them through admin. The format still the same : 0.1 for 10%.

**Comment by fakelefteye** [comment]
Hello,
Tuant toi dit tout answer; this is what I entered but then the fees are
100€ even for small amounts... you can check also in demo.cocorico.io it
gives also a fee of 100€ even for small amounts . I think there is a bug
somewhere...
Thank you

**Comment by cocolabssas** [comment]
Hi,

the fees percent value in demo admin was 10 meaning 1000%. Put 0.1 or erase the value in admin and it will be resolved.
