### ISSUE TITLE
PROFILE AND LISTING DELETION

### ISSUE THREAD

**Issue by pruffier** [Cocolabs-SAS/cocorico#66]
hello,

is it my code or there are no options to delete profile and listing by user / and by admin.

thank you!

**Comment by cocolabssas** [comment]
Hello,

Indeed to avoid to lost data by inadvertence, we choose to disable deletion of important data through admin.  You can enable it by modifying xxxAdmin classes.

Look at Sonata Admin documentation to know how to do that.
