### ISSUE TITLE
Can its possible to separate the Asker & Offerer Profiles ?

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#69]
Hello, 

hope you are fine and doing good. 

Kindly guide me for a good way separate both types of users because one is asker and other is Offerer

Like in registration we have the option of check box then with help of selection we only show one profile also add validation for an individual  like for asker no email verification required but for offerer email verification required.

I will appreciate your help and guideline on it.

**Comment by cocolabssas** [comment]
Hi,

To know if an existing  user is an offerer you can check if $user->getListings()->count() is greater than 0 else he is an asker.

For your need i suppose you have to implement yourself this functionality which doesn't exist in cocorico.

**Comment by Atranaz** [comment]
Hello, 

first of all thanks and yes its possible case but it's not mandatory that offer always deposit first :)

anyways I can check my self I see in the database you create one table name with user_group I thought maybe it help me for separate both profiles.

thanks.

**Comment by cocolabssas** [comment]
Hi,

It can be a  solution :)

I close the issue as it seems to be more relevant to custom development than issue.

Thanks!
