### ISSUE TITLE
Apccache

### ISSUE THREAD

**Issue by nvirin** [Cocolabs-SAS/cocorico#70]
Fatal error: Call to undefined function Doctrine\Common\Cache\apc_fetch() in /home/shhhtournq/www/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php on line 40
Is it possible to install cocorico when you can't enable and or install apc on your server?

**Comment by cocolabssas** [comment]
Hi,

Yes it is possible. 
But you should use an opcode cache to improve performance in your Symfony applications. 
(https://symfony.com/doc/current/performance.html)
If you use PHP 5.x the op code cache is  build-in, so no need to install APC. 

If you really can't enable APC you have to disable the autoloader APC caching in app.php and comment 
the doctrine orm cache section in https://github.com/Cocolabs-SAS/cocorico/blob/master/app/config/config_prod.yml#L12
