### ISSUE TITLE
Listing permission error in Duplication 

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#71]
Hello, 

I set listing first get approved from admin in parameter.yml and its working fine but unfortunately, when I create one duplicate from unapproved listing it approved automatic and published.

kindly check its issue or not I'll check my own too

**Comment by cocolabssas** [comment]
Hi @Atranaz 

It should be resolved this week.

Thanks !

**Comment by Atranaz** [comment]
Hello @cocolabssas  

Thanks for quick reply also can you give me tell me from where I restrict user to post only one listing :)

my pleasure and thanks in advance!

**Comment by cocolabssas** [comment]
Hi @Atranaz 

After analyse your issue is not reproductible. The default status of a duplicate listing is "new" meaning not published.

About one listing deposit restriction, for now it is not possible in cocorico. Maybe we will add this functionality in the future. In the meanwhile you have to implement it yourself.

Thanks!

**Comment by Atranaz** [comment]
Hello @cocolabssas 

Yes it's become new and getting option of publishing kindly check again

In my case, I restrict for publish but when user add one listing its ok but after that, he duplicates and gets all options like he can publish it.

For one listing I wish it come soon :)

**One more thing can I add characteristics on the front list?**

**Comment by cocolabssas** [comment]
Hi @Atranaz 

Indeed in this special case the duplicated listing status should be TO_VALIDATE. It will be resolved soon.

About adding characteristic on listing deposit page, cocorico doesn't have this functionality for now. 

Thanks for your contribution!

**Comment by Atranaz** [comment]
It's my pleasure!

hope soon it will fix.

**For characteristic any chance to come soon in future?**

thanks

**Comment by cocolabssas** [comment]
The issue is resolved (742957d89ea8a6aab06dd6950cd4e50694215281). :)
