### ISSUE TITLE
Show Profession in Result

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#72]
@cocolabssas or anyone else 

It's a simple task but I don't why I can't figure out this

what I need show the profession in search result page but unfortunately, we have only id, name & image can someone guide me how can I add more parameters in the search result page

**Thanks in advance!**

**Comment by cocolabssas** [comment]
Hi,

There is no profession field in cocorico.  If you added this field in Listing entity and you want to display it in result page, you have to add it also in the fields selected by the `getFindQueryBuilder() `method in `Cocorico/CoreBundle/Repository/ListingRepository.php` file.

Hope it helps

**Comment by Atranaz** [comment]
Hello @cocolabssas 

I am talking about the field are exist in dashboard edit payment page.

[https://ibb.co/bz4U3k](url)

you can check on above link what I need show this field is also with each profile when I try to add this I got error listing.user only have **id,name,image** 

thanks

**Comment by cocolabssas** [comment]
Hi @Atranaz 

Look into the code to see what is the name of this field and add it to the query as i said in previous answer.

I close the issue as it seems to be more a support request about how to analyse code than a real issue.

Thanks for your contribution,
