### ISSUE TITLE
update bootstrap 

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#73]
Hello,

the file base.html.twig is pointing to an old bootstrap version, this caused the drop down menu to be hidden when the windows was reduced .

updating to //maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">

fixed the problem

**Comment by cocolabssas** [comment]
Hi,

Thanks for your contribution!
Could you precise which drop down menu disappears?

**Comment by fakelefteye** [comment]
Hello
The search bar with the categories .
When the location box goes under it when narrowing the window it
disappeared but now that I've updated bootstrap it works fine.

**Comment by cocolabssas** [comment]
Great. From our side we want that elements scroll when the browser window scroll. 

Thanks
