### ISSUE TITLE
Error in your demo booking payment page

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#75]
I try to check the process of booking in your demo but always get the same error when I try to pay through mango pay credit card 

[https://imgur.com/a/NOvS0](url)

I try four to five time with a different account but same error.

**Comment by cocolabssas** [comment]
On my side it works. Could you test with this card : 

Card: 3569990000000116
Expiration: 0619
CVV: 123

**Comment by Atranaz** [comment]
@cocolabssas Yes it's working with your given credentials thanks.
