### ISSUE TITLE
Swiftmailer sends 2 emails when wrting a message

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#77]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| Support request? | no

I found that when sending a message with the contact tab Swiftmailer sends 2 identicals emails instead of 1.

In /var/www/rent-a-kite.com/Symfony/src/Cocorico/ContactBundle/Controller/Frontend/ContactController.php

I found that in :

 public function newAction(Request $request)
    {
        $contact = new Contact();
        $form = $this->createCreateForm($contact);

        $submitted = $this->get('cocorico_contact.form.handler.contact')->process($form);
        if ($submitted !== false) {
            $this->get('session')->getFlashBag()->add(
                'success',
                $this->get('translator')->trans('contact.new.success', array(), 'cocorico_contact')
            );

            return $this->redirect($this->generateUrl('cocorico_contact_new'));
        }
 **<! Writing here "redirectTo route" instead of "render" corrects the problem !>**

        return $this->**redirectToRoute**(     <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            'CocoricoContactBundle:Contact:index.html.twig',
            array(
                'form' => $form->createView()
            )

Correct me if I'm wrong.

**Comment by cocolabssas** [comment]
Hi,

After verification there is no two mails send though https://cocorico.dev/en/contact/new.
And your modification create an error 500.

Thanks for your contribution

**Comment by cocolabssas** [comment]
After verification we don't have this problem from our side.
I close the issue feel free to reopen it if the problem still exist.

Thanks
