### ISSUE TITLE
Swift mailer sending tons of emails

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#78]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

Hello,
When I send a contact message using the contact tab swiftmailer  sends a lot of lots to the admin mail.
Is there a way to remove this feature ( not to send logs to admin mail )

Thank you

**Comment by fakelefteye** [comment]
Ok 
I think I found out 
 I commented out the swith section in monolog 
app/config/config_prod.yml

**Comment by fakelefteye** [comment]
I just removed the swift section in moniloh in config_dev.yml
So it doesn't send the logs anymore to admin email 
But Amazon STILL shows over 150mails sent after I use the contact form only  once...
What could it be?

**Comment by cocolabssas** [comment]
Hello,

Indeed the monolog is configured to send email if there is critical errorz. If you don't need it you can disable it.
You 150 emails might have been send when you will have monolog swift configured.

**Comment by cocolabssas** [comment]
After verification we don't have this problem from our side. 
I close the issue feel free to reopen it if the problem still exist.

Thanks
