### ISSUE TITLE
Email Not Sent or can't convert into Prod mode

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#79]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

I having issue or support during working on Cocorico when I finish work I cleared the cache and set prod = true in the controller but can't get the email also I think I am still in development mode. Can you guide me for this why this happened?

**Comment by cocolabssas** [comment]
H Atranazi,

I suggest you to look for informations about how to deploy to production a Symfony application.

- https://stackoverflow.com/questions/10904960/symfony2-how-to-change-environment
- http://symfony.com/doc/current/configuration/environments.html
- ...

I close this issue as it is more relevant to Symfony support than Cocorico.

Thanks!

**Comment by Atranaz** [comment]
@cocolabssas so you believe that's why my emails are not working on **"creating user"**, **"deposit listing"** and all another notification?

**Comment by Atranaz** [comment]
@cocolabssas  Second how can administrator notify with all activities like booking, add a listing and accept or reject listing or lesson.
