### ISSUE TITLE
Comment ajouter des traductions en BDD ?

### ISSUE THREAD

**Issue by AxelBriche** [Cocolabs-SAS/cocorico#8]
Bonjour, comment est il possible d'ajouter de nouvelles traductions en base de donnée svp ?
On peux les modifier, mais pas en ajouter depuis l'administration, j'ai trouvé les fichiers de traduction dans "app/Resources/translations/*", mais ils semblent généré et écrasé régulièrement.

Merci.

**Comment by cocolabssas** [comment]
About which database translations are you talking about?
Translations files located in app/Resources/translations/ can be modify either directly either through admin > Traduction menu.
Once modify they are no reason that they are overwritten if you do nothing to overwrite them.
