### ISSUE TITLE
Admin cannot delete ads and new listings not displayed 

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#80]
| Q                | A
| ---------------- | -----
| Bug report?      |?
| Feature request? | no
| Support request? | yes
Hello
I'm  having trouble with my install : I've noticed that when I put a new as it isn't displayed anymore in the latest listings "high rank.twig".
ALSO WHEN I try to delete an ad through the admin panel it doesn't get deleted...
What can it possibly be 
?

Thank you

**Comment by fakelefteye** [comment]
I init again mongodb and it was fine

**Comment by fakelefteye** [comment]
hello

I always have to restart mongodb in order to have the high rank section updated...

how can it be automatic?

thank you

**Comment by fakelefteye** [comment]
Hello,

When New listings are added they are not showed in the "high_rank" section ; I have to manually re init mongo... 

I changed parameters.yml   #Is new listing published by default (0 or 1)
    cocorico.listing_new_is_published: 1

but When I put it back to 0 I still need to validate the listings...

What can I do to have high rank updated automatically?

Thank you

**Comment by cocolabssas** [comment]
Hello,

`cocorico.listing_new_is_published: 1` means your listings are automatically published, 0 means listings are not published by default and admin have to change their status to published.

Before using cocorico ensure that mongo is running by running bin/start-mongodb [your path to mongo data folder] in linux.

To have listings in high_rank section your listings have to be published. See `\Cocorico\CoreBundle\Controller\Frontend\HomeController::indexAction`.

Listings can not be deleted through admin, you can change their status to deleted instead or delete them though DB.
