### ISSUE TITLE
Listing to validate

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#81]
| Q                | A
| ---------------- | -----
| Bug report?      | /no
| Feature request? | yes/no
| Support request?  Yes

Hello 

How can I set the listing to : "to validate" automatically when someone post a new listing?
Right now it is published right away I want it to be set on hold and validate later manually ...
Thank you
.
-->

**Comment by studioman** [comment]
I also have the same query... any help would be much appreciated.

**Comment by fakelefteye** [comment]
I found the workaround please correct me if I'm wrong but works for me :

in /src/Cocorico/CoreBundle/Model/Manager
ListingManager.php

  if ($this->newListingIsPublished) {
                $listing->setStatus(Listing::**STATUS_PUBLISHED**); <<<<change to STATUS_TO_VALIDATE
                $listingPublished = **true** ;  <<<<change to false
            } else {
                $listing->setStatus(Listing::STATUS_TO_VALIDATE);
            }
        } else {
            //todo: replace this tracking change by doctrine event listener. (See copost UserEntityListener)
            $uow = $this->em->getUnitOfWork();
            $uow->computeChangeSets();
            $changeSet = $uow->getEntityChangeSet($listing);
            if (array_key_exists('status', $changeSet) && $listing->getStatus() == Listing:**:STATUS_TO_VALIDATE) {
                $listingPublished = false;**  <<<<<<<<<<same here
            }

**Comment by cocolabssas** [comment]
Hi,

You just have to change the parameter "cocorico.listing_new_is_published" to 0 in  `Cocorico/CoreBundle/Resources/config/parameters.yml:99`.
