### ISSUE TITLE
How Change Mandatory to Optional or removed

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#85]
| Q                | A
| ---------------- | -----
| Bug report?      | No
| Feature request? | No
| Support request? | Yes

I have a simple question or might be support :) we have few options to book and all are mandatory we have any way to make few are optional or remove from there? for example "time"

thanks in advance

**Comment by kroshp** [comment]
You can choose between two time units in cocorico : day or hour
To remove time related things from your app, you have to pass to day mode by changing `cororico.time_unit` parameter to 1440 in
`Cocorico/CoreBundle/Resources/config/parameters.yml `

**Comment by Atranaz** [comment]
@kroshp yes I know about these options but I need few like I need same option with some fields optional like I explain on my previous comment :)

**Comment by cocolabssas** [comment]
You have to implement it yourself by removing  removing all requirements type for those fields.

**Comment by Atranaz** [comment]
@cocolabssas I only want to set time into optional rest of fields I need it now you can guide me from where I can make it optional :)

**Comment by cocolabssas** [comment]
@Atranaz,

It is not a minor modification to make times optional in hour mode. It means that day and hour mode are possible in the same time. For now we have not planned to invest times to think about how to implement this special functionality.

**Comment by Atranaz** [comment]
Hello @cocolabssas :)

Ok, I understand it's my only a question :) anyways now I should go to my other approach and I guess this is not so much complex one?

How can I set the default time value in time field like always show 12:00 instead of 00:00

Thanks in Advance!

**Comment by mmshivukumar** [comment]
Dear Atranaz,

i have tried installing the cocorico project in my local system.
 but i was getting struck in publishing new Listing
 i have followed the steps of cocorico documentation 
please help in getting solution

Thanks
shivukumar

**Comment by Atranaz** [comment]
@mmshivukumar there is two type of listing publish producer 1st you set auto approved from param in this case every submitted listing automatically publish. 2nd is needed approval permission from an administrator. In this case when someone submits a list and waiting for administrator approve its list.

**Comment by cocolabssas** [comment]
@mmshivukumar please do not ask question without relations with the current issue.

**Comment by cocolabssas** [comment]
Hi @Atranaz 

Look at time picker JS initialisation function `initTimePicker.`  There is a `defaultDate `value you can change.

**Comment by cocolabssas** [comment]
@Atranaz  I close this issue as they are many different unrelated subjects in it. Please create an issue by subject.
