### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by NJCalvo** [Cocolabs-SAS/cocorico#86]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

Hi, i have some problems when I install the marketplace.
I can't finish the installation.
I have a Ubuntu server. I install the last php version and mysql. After that I install php 5.6. But I can't install well mongodb drivers.

Can someone give me a more detailled guide? I don't know manage servers very well and I think this is my problem.

I need to have the script installed for start to modify it. Thanks.

**Comment by kroshp** [comment]
Not sure it is more easy for you but there is a docker https://github.com/acseo/docker-cocorico.

**Comment by NJCalvo** [comment]
I think I have problems to configure the server.

**Comment by cocolabssas** [comment]
Try to read some tutorials on how to install and configure a LAMP server. 
I close the issue as it is more relevant to general server install / configuration support than an application issue.
