### ISSUE TITLE
Search Function is not  working

### ISSUE THREAD

**Issue by mmshivukumar** [Cocolabs-SAS/cocorico#88]
| Support request? | yes

Dear Team,

I have installed the project in local but search function in not working may i know the solution for that ?

please help us to find solution.

Thanks in advancce

**Comment by kroshp** [comment]
Could you precise?

**Comment by cocolabssas** [comment]
We close this issue as it is not described. Feel free to reopen it if you really have an issue you can described.

**Comment by mmshivukumar** [comment]
Dear Madam,

Search Function is working in demo

http://demo.cocorico.io/en/listing/favourite.


And in local we are unable Publish the new Listing.

we are not able add new products. kindly help me out to get solution

Thanks
Shivukumar
8095898687
