### ISSUE TITLE
getting issue with UI and css path

### ISSUE THREAD

**Issue by lovepreetsingh03** [Cocolabs-SAS/cocorico#89]
I open a project in localhost then its UI is not working.
actually css path is different.
project url : http://localhost/cocorico/web/en/
its getting css path : https://cocorico.dev/css/compiled/all.css

my css path is different
So how i will change css path in project

**Comment by kroshp** [comment]
Try to have a project url like this http://localhost/en/ or http://cocorico.dev/en by modifying your .htaccess or Vhost.
Or try to follow **precisely** the installation guide.

**Comment by cocolabssas** [comment]
We close this issue as it seems to be resolvable by following the installation guide details. Feel free to reopen it if you find an issue.
