### ISSUE TITLE
Comment fonctionne le système de traduction (DEV)

### ISSUE THREAD

**Issue by AxelBriche** [Cocolabs-SAS/cocorico#9]
Bonjour, je suis développeur et aimerais savoir comment fonctionne le système de traduction.

Pouvez-vous me confirmer si les choses suivantes sont exactes:
- Quand on édite un fichier de traduction dans le dossier "translation", le contenu de celui-ci est ensuite automatiquement inséré en BDD.
- Si on modifie une traduction en BDD, les fichiers de traduction sont ensuite automatiquement mis à jour.
- Un fichier de traduction non présent dans un .gitignore, peut en écraser un plus récent et donc aboutir à une maj des traductions en bdd en écrasent les modifications précédemment faite.

Au vu des problèmes que l'on a rencontré, j'en ai déduit que le comportement que je viens de citer est celui actuellement en place, pouvez vous me le confirmer ou au contraire m'expliquer le processus de fonctionnement si ma vision du fonctionnement du système de traduction s'avèrerais inexacte svp ?

Merci.

**Comment by jeromedebeauvoir** [comment]
Hi,

Here are my answers :
- Quand on édite un fichier de traduction dans le dossier "translation", le contenu de celui-ci est ensuite automatiquement inséré en BDD.
> No. Translations files are not stored in database. What is the name of the database / table you are talking about?

- Si on modifie une traduction en BDD, les fichiers de traduction sont ensuite automatiquement mis à jour
> Neither. There is no relation between translation files and database.

- Un fichier de traduction non présent dans un .gitignore, peut en écraser un plus récent
> What do you mean? A file can be overwritten if it is versionned or not versionned. It depends on what you do on that file and / or what git commands you run.

- donc aboutir à une maj des traductions en bdd en écrasent les modifications précédemment faite.
> Always not.

- Au vu des problèmes que l'on a rencontré, j'en ai déduit que le comportement cité est celui mis en place, pouvez vous me le confirmer ou au contraire m'expliquer le processus de fonctionnement si ma vision du fonctionnement du système de traduction s'avèrerais inexacte svp ?

> The problems seems to be that you misunderstand how translation works in Symfony2 and JMS translation bundle.

Here is an explanation on how it simply works:
The translations files can be either edited manually either edited through JMS web interface in Admin > translation menu dashboard.
If you edit them manually you will find your modifications in JMS web interface.
If you modify them through JMS web interface you will find your modifications in translations files.
And these translations are not stored in database.
JMS web interface is only a web interface to edit translations files.

I suggest you to look at :
JMS translation Bundle documentation : http://jmsyst.com/bundles/JMSTranslationBundle
Symfony2 translations documentation: http://symfony.com/doc/2.8/book/translation.html
Cocorico : https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Resources/doc/index.rst#translations

Hope it helps,

**Comment by cocolabssas** [comment]
Hi,

Here are my answers :
> Quand on édite un fichier de traduction dans le dossier "translation", le contenu de celui-ci est ensuite automatiquement inséré en BDD.

 No. Translations files are not stored in database. What is the name of the database / table you are talking about?

> Si on modifie une traduction en BDD, les fichiers de traduction sont ensuite automatiquement mis à jour

Neither. There is no relation between translation files and database.

> Un fichier de traduction non présent dans un .gitignore, peut en écraser un plus récent

What do you mean? A file can be overwritten if it is versionned or not versionned. It depends on what you do on that file and / or what git commands you run.

> donc aboutir à une maj des traductions en bdd en écrasent les modifications précédemment faite.

 Always not.

> Au vu des problèmes que l'on a rencontré, j'en ai déduit que le comportement cité est celui mis en place, pouvez vous me le confirmer ou au contraire m'expliquer le processus de fonctionnement si ma vision du fonctionnement du système de traduction s'avèrerais inexacte svp ?

 The problems seems to be that you misunderstand how translation works in Symfony2 and JMS translation bundle.

Here is an explanation on how it simply works:
The translations files can be either edited manually either edited through JMS web interface in Admin > translation menu dashboard.
If you edit them manually you will find your modifications in JMS web interface.
If you modify them through JMS web interface you will find your modifications in translations files.
And these translations are not stored in database.
JMS web interface is only a web interface to edit translations files.

I suggest you to look at :
JMS translation Bundle documentation : http://jmsyst.com/bundles/JMSTranslationBundle
Symfony2 translations documentation: http://symfony.com/doc/2.8/book/translation.html
Cocorico : https://github.com/Cocolabs-SAS/cocorico/blob/master/src/Cocorico/CoreBundle/Resources/doc/index.rst#translations

Hope it helps,
