### ISSUE TITLE
Email not sent issue and get email on no-reply email address 

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#91]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| Support request? | yes

I try to set up an email address with it I create my email address and put now when I do something like create one new account. on my account, i didn't get an email but on my no-reply email I got this message 

This is the mail system at host s19940777.onlinehome-server.info.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

**Comment by mmshivukumar** [comment]
Hi Atranaz  Sir,

i have installed cocorico project in localsystem.
but im facing issues with functionalities like search , publishlisting kindly help to get solution

Thanks in advance
shivukumar

**Comment by Atranaz** [comment]
@mmshivukumar kindly check the closed issues you can get many solutions.

**Comment by mmshivukumar** [comment]
@Atranaz  Sir i checked as you informed but didnt get any solution kindly help 

hope your also working on the same project 

thanks
shivukumar

**Comment by kroshp** [comment]
It is not a bug but a misconfiguration of your smtp config.
Ask to your smtp provider informations about his smtp config then set it in app/config/parameters.yml :

    ...
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_port: null
    ....

**Comment by Atranaz** [comment]
@mmshivukumar kindly open issue with clear issues you got then maybe the group of developer here help you out :)

@kroshp  thanks for your response so, I have to add all details of my server SMTP setting to go through it. Let me check and update you.

**Comment by Atranaz** [comment]
@kroshp thanks it's working now.

**Comment by kroshp** [comment]
Great :)
