### ISSUE TITLE
Did anyone integrate Payfort as payment gateway with it?

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#92]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Support request? | yes

Hello, 
I trying to integrate the payment gateway name Payfort. Does anyone use it before or little guide about payment gateway is also appreciated :)

- https://docs.payfort.com/

thanks in Advance!

**Comment by cocolabssas** [comment]
We close it as it seems that nobody have implemented it yet and we do not plan to do it for now.
