### ISSUE TITLE
issue with multiple language slug

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#93]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Support request? | yes

Hello,
I added the spanish language to my website but when i click on a listing using the spanish language it gives me this error : 
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("slug") to generate a URL for route "es__RG__cocorico_geo_create".").

what is it due to ?
did I miss doing something ?

thank you

**Comment by cocolabssas** [comment]
Hi,

We are fixing this issue.
In the meanwhile remove these lines : Cocorico/CoreBundle/Resources/views/Frontend/Listing/show.html.twig:539-541.

Thanks

**Comment by fakelefteye** [comment]
Hello,
Thank you for your answer, however you solution did resolve the problem : 
I found how to solve it please check the pic : 
in the translations the link show {slug} instead of {id} so I just needed to modify the translation 
![slug](https://user-images.githubusercontent.com/5584130/31766023-b9a90bbe-b4c6-11e7-834b-52461693890b.PNG)
