### ISSUE TITLE
Try to Add new currency but its not working

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#94]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| Support request? | yes

I try to add new currency but it's not working I change all parameters that you mentioned in your last comment on this link - https://github.com/Cocolabs-SAS/cocorico/issues/57 

when I added new its show on dropdown but when i try to select this got error not available :/

**Comment by eshelf** [comment]
Hi Atranaz!

I suggest you to check if the desired currency is listed by the ecb:
http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

In my case, I'm trying to use CLP (Chilean Pesos) but  it's not listed there. 

@cocolabssas , what do you suggest in this case?

**Comment by Atranaz** [comment]
@eshelf well my currency is not listed in list :/ 

so its mean I have to change the adapter @cocolabssas 

my currency is AED / **United Arab Emirates**

**Comment by cocolabssas** [comment]
@eshelf and @Atranaz 

You have to find a source for your rates then change the currency adapter as described here : https://github.com/lexik/LexikCurrencyBundle#load-conversions-rate-from-another-source-custom-currencyadatpter

**Comment by Atranaz** [comment]
@cocolabssas I having an issue to implement your guide first don't have the same **AbstractCurrencyAdapter** and in my **src/Cocorico** folder I have one overridden currency adapter with a name of  **DoctrineCurrencyAdapter**, you can tell me how can I implement it.

**Comment by cocolabssas** [comment]
@Atranaz 

You need to understand how LexikCurrencyBundle work. Maybe ask to its repository.

Thanks.

**Comment by cocolabssas** [comment]
I close the issue. Feel free to reopen it if you need it.
