### ISSUE TITLE
Category link and View?

### ISSUE THREAD

**Issue by Atranaz** [Cocolabs-SAS/cocorico#96]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes
| Support request? | yes

I just curious about all categories page that we made it. wheres the link of the category that contains all listings.

**Comment by cocolabssas** [comment]
The link of your categories pages are the same than you have when you make a search with categories.

**Comment by Atranaz** [comment]
@cocolabssas without selected location I can't get the results so how can I see all result in only one specific category.

**Comment by cocolabssas** [comment]
If you work with only one country you can use the url of a search on this country and this category.
Else you have to implement this simple functionality yourself.
