### ISSUE TITLE
broken link %url%

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#98]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Support request? | yes

Hello, 
when I use a broken link checker it says that this link is a 400 bad request : 
http://demo.cocorico.io/en/listing/%url% 
same for my website .

How can we solve this ?

Also on my website I have an error with the contact form https://rent-a-kite.com/fr/contact/creer

in app/cache/prod/appProdDebugProjectContainerUrlGenerator.php at line 399   -
    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }
        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];

Do ou know where can I solve this ? 

Thank you

**Comment by cocolabssas** [comment]
1 - Add to your robots.txt the url you don't want to be indexed.

2 - You modified ContactController by adding redirectToRoute and passing to it a template instead of a route name.

I close this issue as it not an a cocorico issue  but a user one.
