### ISSUE TITLE
Publish New Listing is not working

### ISSUE THREAD

**Issue by mmshivukumar** [Cocolabs-SAS/cocorico#99]
| Support request? | yes

Dear Team,

 i have installed the project in my local in that functionalities like PUBLISH NEW LISTING is not working

Giving error something went wrong.

please help me 

thank you in advance
shivukumar

**Comment by cocolabssas** [comment]
Here the answer of @atranaz for the same question you asked in an unrelated issue :

@mmshivukumar there is two type of listing publish producer 1st you set auto approved from param in this case every submitted listing automatically publish. 2nd is needed approval permission from an administrator. In this case when someone submits a list and waiting for administrator approve its list.

**Comment by cocolabssas** [comment]
@mmshivukumar  I suggest you to describe precisely your problem.

**Comment by tereluye** [comment]
i have the same problem. it show invalid address every time i click "publish your listing" button. 
i haven't set up my google API key, does it really need google API to publish a listing. is there any way i can disable google API. Please help @cocolabssas .
